// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module LoopBranchPredictorColumn_3(
  input         clock,
                reset,
  input  [36:0] io_f2_req_idx,
  input         io_f3_req_fire,
                io_f3_pred_in,
                io_update_mispredict,
                io_update_repair,
  input  [36:0] io_update_idx,
  input  [9:0]  io_update_meta_s_cnt,
  output        io_f3_pred,
  output [9:0]  io_f3_meta_s_cnt
);

  reg              doing_reset;
  reg  [3:0]       reset_idx;
  reg  [9:0]       entries_0_tag;
  reg  [2:0]       entries_0_conf;
  reg  [2:0]       entries_0_age;
  reg  [9:0]       entries_0_p_cnt;
  reg  [9:0]       entries_0_s_cnt;
  reg  [9:0]       entries_1_tag;
  reg  [2:0]       entries_1_conf;
  reg  [2:0]       entries_1_age;
  reg  [9:0]       entries_1_p_cnt;
  reg  [9:0]       entries_1_s_cnt;
  reg  [9:0]       entries_2_tag;
  reg  [2:0]       entries_2_conf;
  reg  [2:0]       entries_2_age;
  reg  [9:0]       entries_2_p_cnt;
  reg  [9:0]       entries_2_s_cnt;
  reg  [9:0]       entries_3_tag;
  reg  [2:0]       entries_3_conf;
  reg  [2:0]       entries_3_age;
  reg  [9:0]       entries_3_p_cnt;
  reg  [9:0]       entries_3_s_cnt;
  reg  [9:0]       entries_4_tag;
  reg  [2:0]       entries_4_conf;
  reg  [2:0]       entries_4_age;
  reg  [9:0]       entries_4_p_cnt;
  reg  [9:0]       entries_4_s_cnt;
  reg  [9:0]       entries_5_tag;
  reg  [2:0]       entries_5_conf;
  reg  [2:0]       entries_5_age;
  reg  [9:0]       entries_5_p_cnt;
  reg  [9:0]       entries_5_s_cnt;
  reg  [9:0]       entries_6_tag;
  reg  [2:0]       entries_6_conf;
  reg  [2:0]       entries_6_age;
  reg  [9:0]       entries_6_p_cnt;
  reg  [9:0]       entries_6_s_cnt;
  reg  [9:0]       entries_7_tag;
  reg  [2:0]       entries_7_conf;
  reg  [2:0]       entries_7_age;
  reg  [9:0]       entries_7_p_cnt;
  reg  [9:0]       entries_7_s_cnt;
  reg  [9:0]       entries_8_tag;
  reg  [2:0]       entries_8_conf;
  reg  [2:0]       entries_8_age;
  reg  [9:0]       entries_8_p_cnt;
  reg  [9:0]       entries_8_s_cnt;
  reg  [9:0]       entries_9_tag;
  reg  [2:0]       entries_9_conf;
  reg  [2:0]       entries_9_age;
  reg  [9:0]       entries_9_p_cnt;
  reg  [9:0]       entries_9_s_cnt;
  reg  [9:0]       entries_10_tag;
  reg  [2:0]       entries_10_conf;
  reg  [2:0]       entries_10_age;
  reg  [9:0]       entries_10_p_cnt;
  reg  [9:0]       entries_10_s_cnt;
  reg  [9:0]       entries_11_tag;
  reg  [2:0]       entries_11_conf;
  reg  [2:0]       entries_11_age;
  reg  [9:0]       entries_11_p_cnt;
  reg  [9:0]       entries_11_s_cnt;
  reg  [9:0]       entries_12_tag;
  reg  [2:0]       entries_12_conf;
  reg  [2:0]       entries_12_age;
  reg  [9:0]       entries_12_p_cnt;
  reg  [9:0]       entries_12_s_cnt;
  reg  [9:0]       entries_13_tag;
  reg  [2:0]       entries_13_conf;
  reg  [2:0]       entries_13_age;
  reg  [9:0]       entries_13_p_cnt;
  reg  [9:0]       entries_13_s_cnt;
  reg  [9:0]       entries_14_tag;
  reg  [2:0]       entries_14_conf;
  reg  [2:0]       entries_14_age;
  reg  [9:0]       entries_14_p_cnt;
  reg  [9:0]       entries_14_s_cnt;
  reg  [9:0]       entries_15_tag;
  reg  [2:0]       entries_15_conf;
  reg  [2:0]       entries_15_age;
  reg  [9:0]       entries_15_p_cnt;
  reg  [9:0]       entries_15_s_cnt;
  reg  [9:0]       f3_entry_tag;
  reg  [2:0]       f3_entry_conf;
  reg  [2:0]       f3_entry_age;
  reg  [9:0]       f3_entry_p_cnt;
  reg  [9:0]       f3_entry_s_cnt;
  reg  [36:0]      f3_scnt_REG;
  wire             _f3_scnt_T_1 = io_update_repair & io_update_idx == f3_scnt_REG;
  wire [9:0]       f3_scnt = _f3_scnt_T_1 ? io_update_meta_s_cnt : f3_entry_s_cnt;
  reg  [9:0]       f3_tag;
  reg              f4_fire;
  reg  [9:0]       f4_entry_tag;
  reg  [2:0]       f4_entry_conf;
  reg  [2:0]       f4_entry_age;
  reg  [9:0]       f4_entry_p_cnt;
  reg  [9:0]       f4_tag;
  reg  [9:0]       f4_scnt;
  reg  [36:0]      f4_idx_REG;
  reg  [36:0]      f4_idx;
  wire [15:0][9:0] _GEN = {{entries_15_tag}, {entries_14_tag}, {entries_13_tag}, {entries_12_tag}, {entries_11_tag}, {entries_10_tag}, {entries_9_tag}, {entries_8_tag}, {entries_7_tag}, {entries_6_tag}, {entries_5_tag}, {entries_4_tag}, {entries_3_tag}, {entries_2_tag}, {entries_1_tag}, {entries_0_tag}};
  wire [15:0][2:0] _GEN_0 = {{entries_15_conf}, {entries_14_conf}, {entries_13_conf}, {entries_12_conf}, {entries_11_conf}, {entries_10_conf}, {entries_9_conf}, {entries_8_conf}, {entries_7_conf}, {entries_6_conf}, {entries_5_conf}, {entries_4_conf}, {entries_3_conf}, {entries_2_conf}, {entries_1_conf}, {entries_0_conf}};
  wire [15:0][2:0] _GEN_1 = {{entries_15_age}, {entries_14_age}, {entries_13_age}, {entries_12_age}, {entries_11_age}, {entries_10_age}, {entries_9_age}, {entries_8_age}, {entries_7_age}, {entries_6_age}, {entries_5_age}, {entries_4_age}, {entries_3_age}, {entries_2_age}, {entries_1_age}, {entries_0_age}};
  wire [15:0][9:0] _GEN_2 = {{entries_15_p_cnt}, {entries_14_p_cnt}, {entries_13_p_cnt}, {entries_12_p_cnt}, {entries_11_p_cnt}, {entries_10_p_cnt}, {entries_9_p_cnt}, {entries_8_p_cnt}, {entries_7_p_cnt}, {entries_6_p_cnt}, {entries_5_p_cnt}, {entries_4_p_cnt}, {entries_3_p_cnt}, {entries_2_p_cnt}, {entries_1_p_cnt}, {entries_0_p_cnt}};
  wire [15:0][9:0] _GEN_3 = {{entries_15_s_cnt}, {entries_14_s_cnt}, {entries_13_s_cnt}, {entries_12_s_cnt}, {entries_11_s_cnt}, {entries_10_s_cnt}, {entries_9_s_cnt}, {entries_8_s_cnt}, {entries_7_s_cnt}, {entries_6_s_cnt}, {entries_5_s_cnt}, {entries_4_s_cnt}, {entries_3_s_cnt}, {entries_2_s_cnt}, {entries_1_s_cnt}, {entries_0_s_cnt}};
  wire             _T_3 = io_update_idx == io_f2_req_idx;
  wire             _T_12 = f4_scnt == f4_entry_p_cnt & (&f4_entry_conf);
  wire [9:0]       _entries_s_cnt_T_1 = f4_scnt + 10'h1;
  wire             _GEN_4 = f4_fire & f4_entry_tag == f4_tag;
  wire [2:0]       _entries_age_T_2 = f4_entry_age + 3'h1;
  wire [9:0]       _GEN_5 = _GEN[io_update_idx[3:0]];
  wire [2:0]       _GEN_6 = _GEN_0[io_update_idx[3:0]];
  wire [2:0]       _GEN_7 = _GEN_1[io_update_idx[3:0]];
  wire [9:0]       _GEN_8 = _GEN_2[io_update_idx[3:0]];
  wire [9:0]       _GEN_9 = _GEN_3[io_update_idx[3:0]];
  wire             tag_match = _GEN_5 == io_update_idx[13:4];
  wire             ctr_match = _GEN_8 == io_update_meta_s_cnt;
  wire             _T_22 = io_update_mispredict & ~doing_reset;
  wire             _T_24 = (&_GEN_6) & tag_match;
  wire             _T_27 = (&_GEN_6) & ~tag_match;
  wire             _T_30 = (|_GEN_6) & tag_match & ctr_match;
  wire [2:0]       _wentry_conf_T_1 = _GEN_6 + 3'h1;
  wire             _T_34 = (|_GEN_6) & tag_match & ~ctr_match;
  wire             _T_39 = (|_GEN_6) & ~tag_match & _GEN_7 == 3'h0;
  wire             _T_44 = (|_GEN_6) & ~tag_match & (|_GEN_7);
  wire [2:0]       _wentry_age_T_1 = _GEN_7 - 3'h1;
  wire             _T_52 = _GEN_6 == 3'h0;
  wire             _T_47 = _T_52 & tag_match & ctr_match;
  wire             _T_51 = _T_52 & tag_match & ~ctr_match;
  wire             _T_54 = _T_52 & ~tag_match;
  wire             _GEN_10 = ~_T_22 | _T_24 | _T_27 | _T_30 | _T_34 | ~(_T_39 | ~(_T_44 | _T_47 | _T_51 | ~_T_54));
  wire             _GEN_11 = _T_39 | ~(_T_44 | ~(_T_47 | ~(_T_51 | ~_T_54)));
  wire             _GEN_12 = _T_51 | _T_54;
  wire             _GEN_13 = _T_47 | _GEN_12;
  wire             _GEN_14 = _T_34 | _T_39;
  wire             _GEN_15 = _T_30 | _GEN_14;
  wire             _GEN_16 = ~_T_22 | _T_24 | _T_27 | _GEN_15;
  wire             _GEN_17 = _T_24 | ~(_T_27 | ~(_GEN_15 | ~(_T_44 | ~_GEN_13)));
  wire             _GEN_18 = ~_T_22 | _T_24 | _T_27 | _T_30 | ~(_GEN_14 | ~(_T_44 | _T_47 | ~_GEN_12));
  wire             _T_58 = io_update_repair & ~doing_reset;
  wire             _T_62 = tag_match & ~(f4_fire & io_update_idx == f4_idx);
  wire             _GEN_19 = _T_58 & _T_62;
  always @(posedge clock) begin
    if (reset) begin
      doing_reset <= 1'h1;
      reset_idx <= 4'h0;
    end
    else begin
      doing_reset <= reset_idx != 4'hF & doing_reset;
      reset_idx <= reset_idx + {3'h0, doing_reset};
    end
    if (doing_reset & reset_idx == 4'h0) begin
      entries_0_tag <= 10'h0;
      entries_0_conf <= 3'h0;
      entries_0_age <= 3'h0;
      entries_0_p_cnt <= 10'h0;
      entries_0_s_cnt <= 10'h0;
    end
    else if (_T_22 ? io_update_idx[3:0] == 4'h0 : _T_58 & _T_62 & io_update_idx[3:0] == 4'h0) begin
      if (_GEN_10)
        entries_0_tag <= _GEN_5;
      else
        entries_0_tag <= io_update_idx[13:4];
      if (_T_22) begin
        if (_T_24)
          entries_0_conf <= 3'h0;
        else if (_T_27)
          entries_0_conf <= _GEN_6;
        else if (_T_30)
          entries_0_conf <= _wentry_conf_T_1;
        else if (_T_34)
          entries_0_conf <= 3'h0;
        else if (_GEN_11)
          entries_0_conf <= 3'h1;
        else
          entries_0_conf <= _GEN_6;
        if (_GEN_17)
          entries_0_s_cnt <= 10'h0;
        else
          entries_0_s_cnt <= _GEN_9;
      end
      else begin
        entries_0_conf <= _GEN_6;
        if (_GEN_19)
          entries_0_s_cnt <= io_update_meta_s_cnt;
        else
          entries_0_s_cnt <= _GEN_9;
      end
      if (_GEN_16)
        entries_0_age <= _GEN_7;
      else if (_T_44)
        entries_0_age <= _wentry_age_T_1;
      else if (_GEN_13)
        entries_0_age <= 3'h7;
      else
        entries_0_age <= _GEN_7;
      if (_GEN_18)
        entries_0_p_cnt <= _GEN_8;
      else
        entries_0_p_cnt <= io_update_meta_s_cnt;
    end
    else if (_GEN_4) begin
      if (_T_12) begin
        if (f4_idx[3:0] == 4'h0)
          entries_0_age <= 3'h7;
        if (f4_idx[3:0] == 4'h0)
          entries_0_s_cnt <= 10'h0;
      end
      else begin
        if (f4_idx[3:0] == 4'h0) begin
          if (&f4_entry_age)
            entries_0_age <= 3'h7;
          else
            entries_0_age <= _entries_age_T_2;
        end
        if (f4_idx[3:0] == 4'h0)
          entries_0_s_cnt <= _entries_s_cnt_T_1;
      end
    end
    if (doing_reset & reset_idx == 4'h1) begin
      entries_1_tag <= 10'h0;
      entries_1_conf <= 3'h0;
      entries_1_age <= 3'h0;
      entries_1_p_cnt <= 10'h0;
      entries_1_s_cnt <= 10'h0;
    end
    else if (_T_22 ? io_update_idx[3:0] == 4'h1 : _T_58 & _T_62 & io_update_idx[3:0] == 4'h1) begin
      if (_GEN_10)
        entries_1_tag <= _GEN_5;
      else
        entries_1_tag <= io_update_idx[13:4];
      if (_T_22) begin
        if (_T_24)
          entries_1_conf <= 3'h0;
        else if (_T_27)
          entries_1_conf <= _GEN_6;
        else if (_T_30)
          entries_1_conf <= _wentry_conf_T_1;
        else if (_T_34)
          entries_1_conf <= 3'h0;
        else if (_GEN_11)
          entries_1_conf <= 3'h1;
        else
          entries_1_conf <= _GEN_6;
        if (_GEN_17)
          entries_1_s_cnt <= 10'h0;
        else
          entries_1_s_cnt <= _GEN_9;
      end
      else begin
        entries_1_conf <= _GEN_6;
        if (_GEN_19)
          entries_1_s_cnt <= io_update_meta_s_cnt;
        else
          entries_1_s_cnt <= _GEN_9;
      end
      if (_GEN_16)
        entries_1_age <= _GEN_7;
      else if (_T_44)
        entries_1_age <= _wentry_age_T_1;
      else if (_GEN_13)
        entries_1_age <= 3'h7;
      else
        entries_1_age <= _GEN_7;
      if (_GEN_18)
        entries_1_p_cnt <= _GEN_8;
      else
        entries_1_p_cnt <= io_update_meta_s_cnt;
    end
    else if (_GEN_4) begin
      if (_T_12) begin
        if (f4_idx[3:0] == 4'h1)
          entries_1_age <= 3'h7;
        if (f4_idx[3:0] == 4'h1)
          entries_1_s_cnt <= 10'h0;
      end
      else begin
        if (f4_idx[3:0] == 4'h1) begin
          if (&f4_entry_age)
            entries_1_age <= 3'h7;
          else
            entries_1_age <= _entries_age_T_2;
        end
        if (f4_idx[3:0] == 4'h1)
          entries_1_s_cnt <= _entries_s_cnt_T_1;
      end
    end
    if (doing_reset & reset_idx == 4'h2) begin
      entries_2_tag <= 10'h0;
      entries_2_conf <= 3'h0;
      entries_2_age <= 3'h0;
      entries_2_p_cnt <= 10'h0;
      entries_2_s_cnt <= 10'h0;
    end
    else if (_T_22 ? io_update_idx[3:0] == 4'h2 : _T_58 & _T_62 & io_update_idx[3:0] == 4'h2) begin
      if (_GEN_10)
        entries_2_tag <= _GEN_5;
      else
        entries_2_tag <= io_update_idx[13:4];
      if (_T_22) begin
        if (_T_24)
          entries_2_conf <= 3'h0;
        else if (_T_27)
          entries_2_conf <= _GEN_6;
        else if (_T_30)
          entries_2_conf <= _wentry_conf_T_1;
        else if (_T_34)
          entries_2_conf <= 3'h0;
        else if (_GEN_11)
          entries_2_conf <= 3'h1;
        else
          entries_2_conf <= _GEN_6;
        if (_GEN_17)
          entries_2_s_cnt <= 10'h0;
        else
          entries_2_s_cnt <= _GEN_9;
      end
      else begin
        entries_2_conf <= _GEN_6;
        if (_GEN_19)
          entries_2_s_cnt <= io_update_meta_s_cnt;
        else
          entries_2_s_cnt <= _GEN_9;
      end
      if (_GEN_16)
        entries_2_age <= _GEN_7;
      else if (_T_44)
        entries_2_age <= _wentry_age_T_1;
      else if (_GEN_13)
        entries_2_age <= 3'h7;
      else
        entries_2_age <= _GEN_7;
      if (_GEN_18)
        entries_2_p_cnt <= _GEN_8;
      else
        entries_2_p_cnt <= io_update_meta_s_cnt;
    end
    else if (_GEN_4) begin
      if (_T_12) begin
        if (f4_idx[3:0] == 4'h2)
          entries_2_age <= 3'h7;
        if (f4_idx[3:0] == 4'h2)
          entries_2_s_cnt <= 10'h0;
      end
      else begin
        if (f4_idx[3:0] == 4'h2) begin
          if (&f4_entry_age)
            entries_2_age <= 3'h7;
          else
            entries_2_age <= _entries_age_T_2;
        end
        if (f4_idx[3:0] == 4'h2)
          entries_2_s_cnt <= _entries_s_cnt_T_1;
      end
    end
    if (doing_reset & reset_idx == 4'h3) begin
      entries_3_tag <= 10'h0;
      entries_3_conf <= 3'h0;
      entries_3_age <= 3'h0;
      entries_3_p_cnt <= 10'h0;
      entries_3_s_cnt <= 10'h0;
    end
    else if (_T_22 ? io_update_idx[3:0] == 4'h3 : _T_58 & _T_62 & io_update_idx[3:0] == 4'h3) begin
      if (_GEN_10)
        entries_3_tag <= _GEN_5;
      else
        entries_3_tag <= io_update_idx[13:4];
      if (_T_22) begin
        if (_T_24)
          entries_3_conf <= 3'h0;
        else if (_T_27)
          entries_3_conf <= _GEN_6;
        else if (_T_30)
          entries_3_conf <= _wentry_conf_T_1;
        else if (_T_34)
          entries_3_conf <= 3'h0;
        else if (_GEN_11)
          entries_3_conf <= 3'h1;
        else
          entries_3_conf <= _GEN_6;
        if (_GEN_17)
          entries_3_s_cnt <= 10'h0;
        else
          entries_3_s_cnt <= _GEN_9;
      end
      else begin
        entries_3_conf <= _GEN_6;
        if (_GEN_19)
          entries_3_s_cnt <= io_update_meta_s_cnt;
        else
          entries_3_s_cnt <= _GEN_9;
      end
      if (_GEN_16)
        entries_3_age <= _GEN_7;
      else if (_T_44)
        entries_3_age <= _wentry_age_T_1;
      else if (_GEN_13)
        entries_3_age <= 3'h7;
      else
        entries_3_age <= _GEN_7;
      if (_GEN_18)
        entries_3_p_cnt <= _GEN_8;
      else
        entries_3_p_cnt <= io_update_meta_s_cnt;
    end
    else if (_GEN_4) begin
      if (_T_12) begin
        if (f4_idx[3:0] == 4'h3)
          entries_3_age <= 3'h7;
        if (f4_idx[3:0] == 4'h3)
          entries_3_s_cnt <= 10'h0;
      end
      else begin
        if (f4_idx[3:0] == 4'h3) begin
          if (&f4_entry_age)
            entries_3_age <= 3'h7;
          else
            entries_3_age <= _entries_age_T_2;
        end
        if (f4_idx[3:0] == 4'h3)
          entries_3_s_cnt <= _entries_s_cnt_T_1;
      end
    end
    if (doing_reset & reset_idx == 4'h4) begin
      entries_4_tag <= 10'h0;
      entries_4_conf <= 3'h0;
      entries_4_age <= 3'h0;
      entries_4_p_cnt <= 10'h0;
      entries_4_s_cnt <= 10'h0;
    end
    else if (_T_22 ? io_update_idx[3:0] == 4'h4 : _T_58 & _T_62 & io_update_idx[3:0] == 4'h4) begin
      if (_GEN_10)
        entries_4_tag <= _GEN_5;
      else
        entries_4_tag <= io_update_idx[13:4];
      if (_T_22) begin
        if (_T_24)
          entries_4_conf <= 3'h0;
        else if (_T_27)
          entries_4_conf <= _GEN_6;
        else if (_T_30)
          entries_4_conf <= _wentry_conf_T_1;
        else if (_T_34)
          entries_4_conf <= 3'h0;
        else if (_GEN_11)
          entries_4_conf <= 3'h1;
        else
          entries_4_conf <= _GEN_6;
        if (_GEN_17)
          entries_4_s_cnt <= 10'h0;
        else
          entries_4_s_cnt <= _GEN_9;
      end
      else begin
        entries_4_conf <= _GEN_6;
        if (_GEN_19)
          entries_4_s_cnt <= io_update_meta_s_cnt;
        else
          entries_4_s_cnt <= _GEN_9;
      end
      if (_GEN_16)
        entries_4_age <= _GEN_7;
      else if (_T_44)
        entries_4_age <= _wentry_age_T_1;
      else if (_GEN_13)
        entries_4_age <= 3'h7;
      else
        entries_4_age <= _GEN_7;
      if (_GEN_18)
        entries_4_p_cnt <= _GEN_8;
      else
        entries_4_p_cnt <= io_update_meta_s_cnt;
    end
    else if (_GEN_4) begin
      if (_T_12) begin
        if (f4_idx[3:0] == 4'h4)
          entries_4_age <= 3'h7;
        if (f4_idx[3:0] == 4'h4)
          entries_4_s_cnt <= 10'h0;
      end
      else begin
        if (f4_idx[3:0] == 4'h4) begin
          if (&f4_entry_age)
            entries_4_age <= 3'h7;
          else
            entries_4_age <= _entries_age_T_2;
        end
        if (f4_idx[3:0] == 4'h4)
          entries_4_s_cnt <= _entries_s_cnt_T_1;
      end
    end
    if (doing_reset & reset_idx == 4'h5) begin
      entries_5_tag <= 10'h0;
      entries_5_conf <= 3'h0;
      entries_5_age <= 3'h0;
      entries_5_p_cnt <= 10'h0;
      entries_5_s_cnt <= 10'h0;
    end
    else if (_T_22 ? io_update_idx[3:0] == 4'h5 : _T_58 & _T_62 & io_update_idx[3:0] == 4'h5) begin
      if (_GEN_10)
        entries_5_tag <= _GEN_5;
      else
        entries_5_tag <= io_update_idx[13:4];
      if (_T_22) begin
        if (_T_24)
          entries_5_conf <= 3'h0;
        else if (_T_27)
          entries_5_conf <= _GEN_6;
        else if (_T_30)
          entries_5_conf <= _wentry_conf_T_1;
        else if (_T_34)
          entries_5_conf <= 3'h0;
        else if (_GEN_11)
          entries_5_conf <= 3'h1;
        else
          entries_5_conf <= _GEN_6;
        if (_GEN_17)
          entries_5_s_cnt <= 10'h0;
        else
          entries_5_s_cnt <= _GEN_9;
      end
      else begin
        entries_5_conf <= _GEN_6;
        if (_GEN_19)
          entries_5_s_cnt <= io_update_meta_s_cnt;
        else
          entries_5_s_cnt <= _GEN_9;
      end
      if (_GEN_16)
        entries_5_age <= _GEN_7;
      else if (_T_44)
        entries_5_age <= _wentry_age_T_1;
      else if (_GEN_13)
        entries_5_age <= 3'h7;
      else
        entries_5_age <= _GEN_7;
      if (_GEN_18)
        entries_5_p_cnt <= _GEN_8;
      else
        entries_5_p_cnt <= io_update_meta_s_cnt;
    end
    else if (_GEN_4) begin
      if (_T_12) begin
        if (f4_idx[3:0] == 4'h5)
          entries_5_age <= 3'h7;
        if (f4_idx[3:0] == 4'h5)
          entries_5_s_cnt <= 10'h0;
      end
      else begin
        if (f4_idx[3:0] == 4'h5) begin
          if (&f4_entry_age)
            entries_5_age <= 3'h7;
          else
            entries_5_age <= _entries_age_T_2;
        end
        if (f4_idx[3:0] == 4'h5)
          entries_5_s_cnt <= _entries_s_cnt_T_1;
      end
    end
    if (doing_reset & reset_idx == 4'h6) begin
      entries_6_tag <= 10'h0;
      entries_6_conf <= 3'h0;
      entries_6_age <= 3'h0;
      entries_6_p_cnt <= 10'h0;
      entries_6_s_cnt <= 10'h0;
    end
    else if (_T_22 ? io_update_idx[3:0] == 4'h6 : _T_58 & _T_62 & io_update_idx[3:0] == 4'h6) begin
      if (_GEN_10)
        entries_6_tag <= _GEN_5;
      else
        entries_6_tag <= io_update_idx[13:4];
      if (_T_22) begin
        if (_T_24)
          entries_6_conf <= 3'h0;
        else if (_T_27)
          entries_6_conf <= _GEN_6;
        else if (_T_30)
          entries_6_conf <= _wentry_conf_T_1;
        else if (_T_34)
          entries_6_conf <= 3'h0;
        else if (_GEN_11)
          entries_6_conf <= 3'h1;
        else
          entries_6_conf <= _GEN_6;
        if (_GEN_17)
          entries_6_s_cnt <= 10'h0;
        else
          entries_6_s_cnt <= _GEN_9;
      end
      else begin
        entries_6_conf <= _GEN_6;
        if (_GEN_19)
          entries_6_s_cnt <= io_update_meta_s_cnt;
        else
          entries_6_s_cnt <= _GEN_9;
      end
      if (_GEN_16)
        entries_6_age <= _GEN_7;
      else if (_T_44)
        entries_6_age <= _wentry_age_T_1;
      else if (_GEN_13)
        entries_6_age <= 3'h7;
      else
        entries_6_age <= _GEN_7;
      if (_GEN_18)
        entries_6_p_cnt <= _GEN_8;
      else
        entries_6_p_cnt <= io_update_meta_s_cnt;
    end
    else if (_GEN_4) begin
      if (_T_12) begin
        if (f4_idx[3:0] == 4'h6)
          entries_6_age <= 3'h7;
        if (f4_idx[3:0] == 4'h6)
          entries_6_s_cnt <= 10'h0;
      end
      else begin
        if (f4_idx[3:0] == 4'h6) begin
          if (&f4_entry_age)
            entries_6_age <= 3'h7;
          else
            entries_6_age <= _entries_age_T_2;
        end
        if (f4_idx[3:0] == 4'h6)
          entries_6_s_cnt <= _entries_s_cnt_T_1;
      end
    end
    if (doing_reset & reset_idx == 4'h7) begin
      entries_7_tag <= 10'h0;
      entries_7_conf <= 3'h0;
      entries_7_age <= 3'h0;
      entries_7_p_cnt <= 10'h0;
      entries_7_s_cnt <= 10'h0;
    end
    else if (_T_22 ? io_update_idx[3:0] == 4'h7 : _T_58 & _T_62 & io_update_idx[3:0] == 4'h7) begin
      if (_GEN_10)
        entries_7_tag <= _GEN_5;
      else
        entries_7_tag <= io_update_idx[13:4];
      if (_T_22) begin
        if (_T_24)
          entries_7_conf <= 3'h0;
        else if (_T_27)
          entries_7_conf <= _GEN_6;
        else if (_T_30)
          entries_7_conf <= _wentry_conf_T_1;
        else if (_T_34)
          entries_7_conf <= 3'h0;
        else if (_GEN_11)
          entries_7_conf <= 3'h1;
        else
          entries_7_conf <= _GEN_6;
        if (_GEN_17)
          entries_7_s_cnt <= 10'h0;
        else
          entries_7_s_cnt <= _GEN_9;
      end
      else begin
        entries_7_conf <= _GEN_6;
        if (_GEN_19)
          entries_7_s_cnt <= io_update_meta_s_cnt;
        else
          entries_7_s_cnt <= _GEN_9;
      end
      if (_GEN_16)
        entries_7_age <= _GEN_7;
      else if (_T_44)
        entries_7_age <= _wentry_age_T_1;
      else if (_GEN_13)
        entries_7_age <= 3'h7;
      else
        entries_7_age <= _GEN_7;
      if (_GEN_18)
        entries_7_p_cnt <= _GEN_8;
      else
        entries_7_p_cnt <= io_update_meta_s_cnt;
    end
    else if (_GEN_4) begin
      if (_T_12) begin
        if (f4_idx[3:0] == 4'h7)
          entries_7_age <= 3'h7;
        if (f4_idx[3:0] == 4'h7)
          entries_7_s_cnt <= 10'h0;
      end
      else begin
        if (f4_idx[3:0] == 4'h7) begin
          if (&f4_entry_age)
            entries_7_age <= 3'h7;
          else
            entries_7_age <= _entries_age_T_2;
        end
        if (f4_idx[3:0] == 4'h7)
          entries_7_s_cnt <= _entries_s_cnt_T_1;
      end
    end
    if (doing_reset & reset_idx == 4'h8) begin
      entries_8_tag <= 10'h0;
      entries_8_conf <= 3'h0;
      entries_8_age <= 3'h0;
      entries_8_p_cnt <= 10'h0;
      entries_8_s_cnt <= 10'h0;
    end
    else if (_T_22 ? io_update_idx[3:0] == 4'h8 : _T_58 & _T_62 & io_update_idx[3:0] == 4'h8) begin
      if (_GEN_10)
        entries_8_tag <= _GEN_5;
      else
        entries_8_tag <= io_update_idx[13:4];
      if (_T_22) begin
        if (_T_24)
          entries_8_conf <= 3'h0;
        else if (_T_27)
          entries_8_conf <= _GEN_6;
        else if (_T_30)
          entries_8_conf <= _wentry_conf_T_1;
        else if (_T_34)
          entries_8_conf <= 3'h0;
        else if (_GEN_11)
          entries_8_conf <= 3'h1;
        else
          entries_8_conf <= _GEN_6;
        if (_GEN_17)
          entries_8_s_cnt <= 10'h0;
        else
          entries_8_s_cnt <= _GEN_9;
      end
      else begin
        entries_8_conf <= _GEN_6;
        if (_GEN_19)
          entries_8_s_cnt <= io_update_meta_s_cnt;
        else
          entries_8_s_cnt <= _GEN_9;
      end
      if (_GEN_16)
        entries_8_age <= _GEN_7;
      else if (_T_44)
        entries_8_age <= _wentry_age_T_1;
      else if (_GEN_13)
        entries_8_age <= 3'h7;
      else
        entries_8_age <= _GEN_7;
      if (_GEN_18)
        entries_8_p_cnt <= _GEN_8;
      else
        entries_8_p_cnt <= io_update_meta_s_cnt;
    end
    else if (_GEN_4) begin
      if (_T_12) begin
        if (f4_idx[3:0] == 4'h8)
          entries_8_age <= 3'h7;
        if (f4_idx[3:0] == 4'h8)
          entries_8_s_cnt <= 10'h0;
      end
      else begin
        if (f4_idx[3:0] == 4'h8) begin
          if (&f4_entry_age)
            entries_8_age <= 3'h7;
          else
            entries_8_age <= _entries_age_T_2;
        end
        if (f4_idx[3:0] == 4'h8)
          entries_8_s_cnt <= _entries_s_cnt_T_1;
      end
    end
    if (doing_reset & reset_idx == 4'h9) begin
      entries_9_tag <= 10'h0;
      entries_9_conf <= 3'h0;
      entries_9_age <= 3'h0;
      entries_9_p_cnt <= 10'h0;
      entries_9_s_cnt <= 10'h0;
    end
    else if (_T_22 ? io_update_idx[3:0] == 4'h9 : _T_58 & _T_62 & io_update_idx[3:0] == 4'h9) begin
      if (_GEN_10)
        entries_9_tag <= _GEN_5;
      else
        entries_9_tag <= io_update_idx[13:4];
      if (_T_22) begin
        if (_T_24)
          entries_9_conf <= 3'h0;
        else if (_T_27)
          entries_9_conf <= _GEN_6;
        else if (_T_30)
          entries_9_conf <= _wentry_conf_T_1;
        else if (_T_34)
          entries_9_conf <= 3'h0;
        else if (_GEN_11)
          entries_9_conf <= 3'h1;
        else
          entries_9_conf <= _GEN_6;
        if (_GEN_17)
          entries_9_s_cnt <= 10'h0;
        else
          entries_9_s_cnt <= _GEN_9;
      end
      else begin
        entries_9_conf <= _GEN_6;
        if (_GEN_19)
          entries_9_s_cnt <= io_update_meta_s_cnt;
        else
          entries_9_s_cnt <= _GEN_9;
      end
      if (_GEN_16)
        entries_9_age <= _GEN_7;
      else if (_T_44)
        entries_9_age <= _wentry_age_T_1;
      else if (_GEN_13)
        entries_9_age <= 3'h7;
      else
        entries_9_age <= _GEN_7;
      if (_GEN_18)
        entries_9_p_cnt <= _GEN_8;
      else
        entries_9_p_cnt <= io_update_meta_s_cnt;
    end
    else if (_GEN_4) begin
      if (_T_12) begin
        if (f4_idx[3:0] == 4'h9)
          entries_9_age <= 3'h7;
        if (f4_idx[3:0] == 4'h9)
          entries_9_s_cnt <= 10'h0;
      end
      else begin
        if (f4_idx[3:0] == 4'h9) begin
          if (&f4_entry_age)
            entries_9_age <= 3'h7;
          else
            entries_9_age <= _entries_age_T_2;
        end
        if (f4_idx[3:0] == 4'h9)
          entries_9_s_cnt <= _entries_s_cnt_T_1;
      end
    end
    if (doing_reset & reset_idx == 4'hA) begin
      entries_10_tag <= 10'h0;
      entries_10_conf <= 3'h0;
      entries_10_age <= 3'h0;
      entries_10_p_cnt <= 10'h0;
      entries_10_s_cnt <= 10'h0;
    end
    else if (_T_22 ? io_update_idx[3:0] == 4'hA : _T_58 & _T_62 & io_update_idx[3:0] == 4'hA) begin
      if (_GEN_10)
        entries_10_tag <= _GEN_5;
      else
        entries_10_tag <= io_update_idx[13:4];
      if (_T_22) begin
        if (_T_24)
          entries_10_conf <= 3'h0;
        else if (_T_27)
          entries_10_conf <= _GEN_6;
        else if (_T_30)
          entries_10_conf <= _wentry_conf_T_1;
        else if (_T_34)
          entries_10_conf <= 3'h0;
        else if (_GEN_11)
          entries_10_conf <= 3'h1;
        else
          entries_10_conf <= _GEN_6;
        if (_GEN_17)
          entries_10_s_cnt <= 10'h0;
        else
          entries_10_s_cnt <= _GEN_9;
      end
      else begin
        entries_10_conf <= _GEN_6;
        if (_GEN_19)
          entries_10_s_cnt <= io_update_meta_s_cnt;
        else
          entries_10_s_cnt <= _GEN_9;
      end
      if (_GEN_16)
        entries_10_age <= _GEN_7;
      else if (_T_44)
        entries_10_age <= _wentry_age_T_1;
      else if (_GEN_13)
        entries_10_age <= 3'h7;
      else
        entries_10_age <= _GEN_7;
      if (_GEN_18)
        entries_10_p_cnt <= _GEN_8;
      else
        entries_10_p_cnt <= io_update_meta_s_cnt;
    end
    else if (_GEN_4) begin
      if (_T_12) begin
        if (f4_idx[3:0] == 4'hA)
          entries_10_age <= 3'h7;
        if (f4_idx[3:0] == 4'hA)
          entries_10_s_cnt <= 10'h0;
      end
      else begin
        if (f4_idx[3:0] == 4'hA) begin
          if (&f4_entry_age)
            entries_10_age <= 3'h7;
          else
            entries_10_age <= _entries_age_T_2;
        end
        if (f4_idx[3:0] == 4'hA)
          entries_10_s_cnt <= _entries_s_cnt_T_1;
      end
    end
    if (doing_reset & reset_idx == 4'hB) begin
      entries_11_tag <= 10'h0;
      entries_11_conf <= 3'h0;
      entries_11_age <= 3'h0;
      entries_11_p_cnt <= 10'h0;
      entries_11_s_cnt <= 10'h0;
    end
    else if (_T_22 ? io_update_idx[3:0] == 4'hB : _T_58 & _T_62 & io_update_idx[3:0] == 4'hB) begin
      if (_GEN_10)
        entries_11_tag <= _GEN_5;
      else
        entries_11_tag <= io_update_idx[13:4];
      if (_T_22) begin
        if (_T_24)
          entries_11_conf <= 3'h0;
        else if (_T_27)
          entries_11_conf <= _GEN_6;
        else if (_T_30)
          entries_11_conf <= _wentry_conf_T_1;
        else if (_T_34)
          entries_11_conf <= 3'h0;
        else if (_GEN_11)
          entries_11_conf <= 3'h1;
        else
          entries_11_conf <= _GEN_6;
        if (_GEN_17)
          entries_11_s_cnt <= 10'h0;
        else
          entries_11_s_cnt <= _GEN_9;
      end
      else begin
        entries_11_conf <= _GEN_6;
        if (_GEN_19)
          entries_11_s_cnt <= io_update_meta_s_cnt;
        else
          entries_11_s_cnt <= _GEN_9;
      end
      if (_GEN_16)
        entries_11_age <= _GEN_7;
      else if (_T_44)
        entries_11_age <= _wentry_age_T_1;
      else if (_GEN_13)
        entries_11_age <= 3'h7;
      else
        entries_11_age <= _GEN_7;
      if (_GEN_18)
        entries_11_p_cnt <= _GEN_8;
      else
        entries_11_p_cnt <= io_update_meta_s_cnt;
    end
    else if (_GEN_4) begin
      if (_T_12) begin
        if (f4_idx[3:0] == 4'hB)
          entries_11_age <= 3'h7;
        if (f4_idx[3:0] == 4'hB)
          entries_11_s_cnt <= 10'h0;
      end
      else begin
        if (f4_idx[3:0] == 4'hB) begin
          if (&f4_entry_age)
            entries_11_age <= 3'h7;
          else
            entries_11_age <= _entries_age_T_2;
        end
        if (f4_idx[3:0] == 4'hB)
          entries_11_s_cnt <= _entries_s_cnt_T_1;
      end
    end
    if (doing_reset & reset_idx == 4'hC) begin
      entries_12_tag <= 10'h0;
      entries_12_conf <= 3'h0;
      entries_12_age <= 3'h0;
      entries_12_p_cnt <= 10'h0;
      entries_12_s_cnt <= 10'h0;
    end
    else if (_T_22 ? io_update_idx[3:0] == 4'hC : _T_58 & _T_62 & io_update_idx[3:0] == 4'hC) begin
      if (_GEN_10)
        entries_12_tag <= _GEN_5;
      else
        entries_12_tag <= io_update_idx[13:4];
      if (_T_22) begin
        if (_T_24)
          entries_12_conf <= 3'h0;
        else if (_T_27)
          entries_12_conf <= _GEN_6;
        else if (_T_30)
          entries_12_conf <= _wentry_conf_T_1;
        else if (_T_34)
          entries_12_conf <= 3'h0;
        else if (_GEN_11)
          entries_12_conf <= 3'h1;
        else
          entries_12_conf <= _GEN_6;
        if (_GEN_17)
          entries_12_s_cnt <= 10'h0;
        else
          entries_12_s_cnt <= _GEN_9;
      end
      else begin
        entries_12_conf <= _GEN_6;
        if (_GEN_19)
          entries_12_s_cnt <= io_update_meta_s_cnt;
        else
          entries_12_s_cnt <= _GEN_9;
      end
      if (_GEN_16)
        entries_12_age <= _GEN_7;
      else if (_T_44)
        entries_12_age <= _wentry_age_T_1;
      else if (_GEN_13)
        entries_12_age <= 3'h7;
      else
        entries_12_age <= _GEN_7;
      if (_GEN_18)
        entries_12_p_cnt <= _GEN_8;
      else
        entries_12_p_cnt <= io_update_meta_s_cnt;
    end
    else if (_GEN_4) begin
      if (_T_12) begin
        if (f4_idx[3:0] == 4'hC)
          entries_12_age <= 3'h7;
        if (f4_idx[3:0] == 4'hC)
          entries_12_s_cnt <= 10'h0;
      end
      else begin
        if (f4_idx[3:0] == 4'hC) begin
          if (&f4_entry_age)
            entries_12_age <= 3'h7;
          else
            entries_12_age <= _entries_age_T_2;
        end
        if (f4_idx[3:0] == 4'hC)
          entries_12_s_cnt <= _entries_s_cnt_T_1;
      end
    end
    if (doing_reset & reset_idx == 4'hD) begin
      entries_13_tag <= 10'h0;
      entries_13_conf <= 3'h0;
      entries_13_age <= 3'h0;
      entries_13_p_cnt <= 10'h0;
      entries_13_s_cnt <= 10'h0;
    end
    else if (_T_22 ? io_update_idx[3:0] == 4'hD : _T_58 & _T_62 & io_update_idx[3:0] == 4'hD) begin
      if (_GEN_10)
        entries_13_tag <= _GEN_5;
      else
        entries_13_tag <= io_update_idx[13:4];
      if (_T_22) begin
        if (_T_24)
          entries_13_conf <= 3'h0;
        else if (_T_27)
          entries_13_conf <= _GEN_6;
        else if (_T_30)
          entries_13_conf <= _wentry_conf_T_1;
        else if (_T_34)
          entries_13_conf <= 3'h0;
        else if (_GEN_11)
          entries_13_conf <= 3'h1;
        else
          entries_13_conf <= _GEN_6;
        if (_GEN_17)
          entries_13_s_cnt <= 10'h0;
        else
          entries_13_s_cnt <= _GEN_9;
      end
      else begin
        entries_13_conf <= _GEN_6;
        if (_GEN_19)
          entries_13_s_cnt <= io_update_meta_s_cnt;
        else
          entries_13_s_cnt <= _GEN_9;
      end
      if (_GEN_16)
        entries_13_age <= _GEN_7;
      else if (_T_44)
        entries_13_age <= _wentry_age_T_1;
      else if (_GEN_13)
        entries_13_age <= 3'h7;
      else
        entries_13_age <= _GEN_7;
      if (_GEN_18)
        entries_13_p_cnt <= _GEN_8;
      else
        entries_13_p_cnt <= io_update_meta_s_cnt;
    end
    else if (_GEN_4) begin
      if (_T_12) begin
        if (f4_idx[3:0] == 4'hD)
          entries_13_age <= 3'h7;
        if (f4_idx[3:0] == 4'hD)
          entries_13_s_cnt <= 10'h0;
      end
      else begin
        if (f4_idx[3:0] == 4'hD) begin
          if (&f4_entry_age)
            entries_13_age <= 3'h7;
          else
            entries_13_age <= _entries_age_T_2;
        end
        if (f4_idx[3:0] == 4'hD)
          entries_13_s_cnt <= _entries_s_cnt_T_1;
      end
    end
    if (doing_reset & reset_idx == 4'hE) begin
      entries_14_tag <= 10'h0;
      entries_14_conf <= 3'h0;
      entries_14_age <= 3'h0;
      entries_14_p_cnt <= 10'h0;
      entries_14_s_cnt <= 10'h0;
    end
    else if (_T_22 ? io_update_idx[3:0] == 4'hE : _T_58 & _T_62 & io_update_idx[3:0] == 4'hE) begin
      if (_GEN_10)
        entries_14_tag <= _GEN_5;
      else
        entries_14_tag <= io_update_idx[13:4];
      if (_T_22) begin
        if (_T_24)
          entries_14_conf <= 3'h0;
        else if (_T_27)
          entries_14_conf <= _GEN_6;
        else if (_T_30)
          entries_14_conf <= _wentry_conf_T_1;
        else if (_T_34)
          entries_14_conf <= 3'h0;
        else if (_GEN_11)
          entries_14_conf <= 3'h1;
        else
          entries_14_conf <= _GEN_6;
        if (_GEN_17)
          entries_14_s_cnt <= 10'h0;
        else
          entries_14_s_cnt <= _GEN_9;
      end
      else begin
        entries_14_conf <= _GEN_6;
        if (_GEN_19)
          entries_14_s_cnt <= io_update_meta_s_cnt;
        else
          entries_14_s_cnt <= _GEN_9;
      end
      if (_GEN_16)
        entries_14_age <= _GEN_7;
      else if (_T_44)
        entries_14_age <= _wentry_age_T_1;
      else if (_GEN_13)
        entries_14_age <= 3'h7;
      else
        entries_14_age <= _GEN_7;
      if (_GEN_18)
        entries_14_p_cnt <= _GEN_8;
      else
        entries_14_p_cnt <= io_update_meta_s_cnt;
    end
    else if (_GEN_4) begin
      if (_T_12) begin
        if (f4_idx[3:0] == 4'hE)
          entries_14_age <= 3'h7;
        if (f4_idx[3:0] == 4'hE)
          entries_14_s_cnt <= 10'h0;
      end
      else begin
        if (f4_idx[3:0] == 4'hE) begin
          if (&f4_entry_age)
            entries_14_age <= 3'h7;
          else
            entries_14_age <= _entries_age_T_2;
        end
        if (f4_idx[3:0] == 4'hE)
          entries_14_s_cnt <= _entries_s_cnt_T_1;
      end
    end
    if (doing_reset & (&reset_idx)) begin
      entries_15_tag <= 10'h0;
      entries_15_conf <= 3'h0;
      entries_15_age <= 3'h0;
      entries_15_p_cnt <= 10'h0;
      entries_15_s_cnt <= 10'h0;
    end
    else if (_T_22 ? (&(io_update_idx[3:0])) : _T_58 & _T_62 & (&(io_update_idx[3:0]))) begin
      if (_GEN_10)
        entries_15_tag <= _GEN_5;
      else
        entries_15_tag <= io_update_idx[13:4];
      if (_T_22) begin
        if (_T_24)
          entries_15_conf <= 3'h0;
        else if (_T_27)
          entries_15_conf <= _GEN_6;
        else if (_T_30)
          entries_15_conf <= _wentry_conf_T_1;
        else if (_T_34)
          entries_15_conf <= 3'h0;
        else if (_GEN_11)
          entries_15_conf <= 3'h1;
        else
          entries_15_conf <= _GEN_6;
        if (_GEN_17)
          entries_15_s_cnt <= 10'h0;
        else
          entries_15_s_cnt <= _GEN_9;
      end
      else begin
        entries_15_conf <= _GEN_6;
        if (_GEN_19)
          entries_15_s_cnt <= io_update_meta_s_cnt;
        else
          entries_15_s_cnt <= _GEN_9;
      end
      if (_GEN_16)
        entries_15_age <= _GEN_7;
      else if (_T_44)
        entries_15_age <= _wentry_age_T_1;
      else if (_GEN_13)
        entries_15_age <= 3'h7;
      else
        entries_15_age <= _GEN_7;
      if (_GEN_18)
        entries_15_p_cnt <= _GEN_8;
      else
        entries_15_p_cnt <= io_update_meta_s_cnt;
    end
    else if (_GEN_4) begin
      if (_T_12) begin
        if (&(f4_idx[3:0]))
          entries_15_age <= 3'h7;
        if (&(f4_idx[3:0]))
          entries_15_s_cnt <= 10'h0;
      end
      else begin
        if (&(f4_idx[3:0])) begin
          if (&f4_entry_age)
            entries_15_age <= 3'h7;
          else
            entries_15_age <= _entries_age_T_2;
        end
        if (&(f4_idx[3:0]))
          entries_15_s_cnt <= _entries_s_cnt_T_1;
      end
    end
    f3_entry_tag <= _GEN[io_f2_req_idx[3:0]];
    f3_entry_conf <= _GEN_0[io_f2_req_idx[3:0]];
    f3_entry_age <= _GEN_1[io_f2_req_idx[3:0]];
    f3_entry_p_cnt <= _GEN_2[io_f2_req_idx[3:0]];
    if (io_update_repair & _T_3)
      f3_entry_s_cnt <= io_update_meta_s_cnt;
    else if (io_update_mispredict & _T_3)
      f3_entry_s_cnt <= 10'h0;
    else
      f3_entry_s_cnt <= _GEN_3[io_f2_req_idx[3:0]];
    f3_scnt_REG <= io_f2_req_idx;
    f3_tag <= io_f2_req_idx[13:4];
    f4_fire <= io_f3_req_fire;
    f4_entry_tag <= f3_entry_tag;
    f4_entry_conf <= f3_entry_conf;
    f4_entry_age <= f3_entry_age;
    f4_entry_p_cnt <= f3_entry_p_cnt;
    f4_tag <= f3_tag;
    if (_f3_scnt_T_1)
      f4_scnt <= io_update_meta_s_cnt;
    else
      f4_scnt <= f3_entry_s_cnt;
    f4_idx_REG <= io_f2_req_idx;
    f4_idx <= f4_idx_REG;
  end // always @(posedge)
  `ifndef SYNTHESIS
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM_0;
    logic [31:0] _RANDOM_1;
    logic [31:0] _RANDOM_2;
    logic [31:0] _RANDOM_3;
    logic [31:0] _RANDOM_4;
    logic [31:0] _RANDOM_5;
    logic [31:0] _RANDOM_6;
    logic [31:0] _RANDOM_7;
    logic [31:0] _RANDOM_8;
    logic [31:0] _RANDOM_9;
    logic [31:0] _RANDOM_10;
    logic [31:0] _RANDOM_11;
    logic [31:0] _RANDOM_12;
    logic [31:0] _RANDOM_13;
    logic [31:0] _RANDOM_14;
    logic [31:0] _RANDOM_15;
    logic [31:0] _RANDOM_16;
    logic [31:0] _RANDOM_17;
    logic [31:0] _RANDOM_18;
    logic [31:0] _RANDOM_19;
    logic [31:0] _RANDOM_20;
    logic [31:0] _RANDOM_21;
    logic [31:0] _RANDOM_22;
    logic [31:0] _RANDOM_23;
    logic [31:0] _RANDOM_24;
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM_0 = `RANDOM;
        _RANDOM_1 = `RANDOM;
        _RANDOM_2 = `RANDOM;
        _RANDOM_3 = `RANDOM;
        _RANDOM_4 = `RANDOM;
        _RANDOM_5 = `RANDOM;
        _RANDOM_6 = `RANDOM;
        _RANDOM_7 = `RANDOM;
        _RANDOM_8 = `RANDOM;
        _RANDOM_9 = `RANDOM;
        _RANDOM_10 = `RANDOM;
        _RANDOM_11 = `RANDOM;
        _RANDOM_12 = `RANDOM;
        _RANDOM_13 = `RANDOM;
        _RANDOM_14 = `RANDOM;
        _RANDOM_15 = `RANDOM;
        _RANDOM_16 = `RANDOM;
        _RANDOM_17 = `RANDOM;
        _RANDOM_18 = `RANDOM;
        _RANDOM_19 = `RANDOM;
        _RANDOM_20 = `RANDOM;
        _RANDOM_21 = `RANDOM;
        _RANDOM_22 = `RANDOM;
        _RANDOM_23 = `RANDOM;
        _RANDOM_24 = `RANDOM;
        doing_reset = _RANDOM_0[0];
        reset_idx = _RANDOM_0[4:1];
        entries_0_tag = _RANDOM_0[14:5];
        entries_0_conf = _RANDOM_0[17:15];
        entries_0_age = _RANDOM_0[20:18];
        entries_0_p_cnt = _RANDOM_0[30:21];
        entries_0_s_cnt = {_RANDOM_0[31], _RANDOM_1[8:0]};
        entries_1_tag = _RANDOM_1[18:9];
        entries_1_conf = _RANDOM_1[21:19];
        entries_1_age = _RANDOM_1[24:22];
        entries_1_p_cnt = {_RANDOM_1[31:25], _RANDOM_2[2:0]};
        entries_1_s_cnt = _RANDOM_2[12:3];
        entries_2_tag = _RANDOM_2[22:13];
        entries_2_conf = _RANDOM_2[25:23];
        entries_2_age = _RANDOM_2[28:26];
        entries_2_p_cnt = {_RANDOM_2[31:29], _RANDOM_3[6:0]};
        entries_2_s_cnt = _RANDOM_3[16:7];
        entries_3_tag = _RANDOM_3[26:17];
        entries_3_conf = _RANDOM_3[29:27];
        entries_3_age = {_RANDOM_3[31:30], _RANDOM_4[0]};
        entries_3_p_cnt = _RANDOM_4[10:1];
        entries_3_s_cnt = _RANDOM_4[20:11];
        entries_4_tag = _RANDOM_4[30:21];
        entries_4_conf = {_RANDOM_4[31], _RANDOM_5[1:0]};
        entries_4_age = _RANDOM_5[4:2];
        entries_4_p_cnt = _RANDOM_5[14:5];
        entries_4_s_cnt = _RANDOM_5[24:15];
        entries_5_tag = {_RANDOM_5[31:25], _RANDOM_6[2:0]};
        entries_5_conf = _RANDOM_6[5:3];
        entries_5_age = _RANDOM_6[8:6];
        entries_5_p_cnt = _RANDOM_6[18:9];
        entries_5_s_cnt = _RANDOM_6[28:19];
        entries_6_tag = {_RANDOM_6[31:29], _RANDOM_7[6:0]};
        entries_6_conf = _RANDOM_7[9:7];
        entries_6_age = _RANDOM_7[12:10];
        entries_6_p_cnt = _RANDOM_7[22:13];
        entries_6_s_cnt = {_RANDOM_7[31:23], _RANDOM_8[0]};
        entries_7_tag = _RANDOM_8[10:1];
        entries_7_conf = _RANDOM_8[13:11];
        entries_7_age = _RANDOM_8[16:14];
        entries_7_p_cnt = _RANDOM_8[26:17];
        entries_7_s_cnt = {_RANDOM_8[31:27], _RANDOM_9[4:0]};
        entries_8_tag = _RANDOM_9[14:5];
        entries_8_conf = _RANDOM_9[17:15];
        entries_8_age = _RANDOM_9[20:18];
        entries_8_p_cnt = _RANDOM_9[30:21];
        entries_8_s_cnt = {_RANDOM_9[31], _RANDOM_10[8:0]};
        entries_9_tag = _RANDOM_10[18:9];
        entries_9_conf = _RANDOM_10[21:19];
        entries_9_age = _RANDOM_10[24:22];
        entries_9_p_cnt = {_RANDOM_10[31:25], _RANDOM_11[2:0]};
        entries_9_s_cnt = _RANDOM_11[12:3];
        entries_10_tag = _RANDOM_11[22:13];
        entries_10_conf = _RANDOM_11[25:23];
        entries_10_age = _RANDOM_11[28:26];
        entries_10_p_cnt = {_RANDOM_11[31:29], _RANDOM_12[6:0]};
        entries_10_s_cnt = _RANDOM_12[16:7];
        entries_11_tag = _RANDOM_12[26:17];
        entries_11_conf = _RANDOM_12[29:27];
        entries_11_age = {_RANDOM_12[31:30], _RANDOM_13[0]};
        entries_11_p_cnt = _RANDOM_13[10:1];
        entries_11_s_cnt = _RANDOM_13[20:11];
        entries_12_tag = _RANDOM_13[30:21];
        entries_12_conf = {_RANDOM_13[31], _RANDOM_14[1:0]};
        entries_12_age = _RANDOM_14[4:2];
        entries_12_p_cnt = _RANDOM_14[14:5];
        entries_12_s_cnt = _RANDOM_14[24:15];
        entries_13_tag = {_RANDOM_14[31:25], _RANDOM_15[2:0]};
        entries_13_conf = _RANDOM_15[5:3];
        entries_13_age = _RANDOM_15[8:6];
        entries_13_p_cnt = _RANDOM_15[18:9];
        entries_13_s_cnt = _RANDOM_15[28:19];
        entries_14_tag = {_RANDOM_15[31:29], _RANDOM_16[6:0]};
        entries_14_conf = _RANDOM_16[9:7];
        entries_14_age = _RANDOM_16[12:10];
        entries_14_p_cnt = _RANDOM_16[22:13];
        entries_14_s_cnt = {_RANDOM_16[31:23], _RANDOM_17[0]};
        entries_15_tag = _RANDOM_17[10:1];
        entries_15_conf = _RANDOM_17[13:11];
        entries_15_age = _RANDOM_17[16:14];
        entries_15_p_cnt = _RANDOM_17[26:17];
        entries_15_s_cnt = {_RANDOM_17[31:27], _RANDOM_18[4:0]};
        f3_entry_tag = _RANDOM_18[14:5];
        f3_entry_conf = _RANDOM_18[17:15];
        f3_entry_age = _RANDOM_18[20:18];
        f3_entry_p_cnt = _RANDOM_18[30:21];
        f3_entry_s_cnt = {_RANDOM_18[31], _RANDOM_19[8:0]};
        f3_scnt_REG = {_RANDOM_19[31:9], _RANDOM_20[13:0]};
        f3_tag = _RANDOM_20[23:14];
        f4_fire = _RANDOM_20[24];
        f4_entry_tag = {_RANDOM_20[31:25], _RANDOM_21[2:0]};
        f4_entry_conf = _RANDOM_21[5:3];
        f4_entry_age = _RANDOM_21[8:6];
        f4_entry_p_cnt = _RANDOM_21[18:9];
        f4_tag = {_RANDOM_21[31:29], _RANDOM_22[6:0]};
        f4_scnt = _RANDOM_22[16:7];
        f4_idx_REG = {_RANDOM_22[31:17], _RANDOM_23[21:0]};
        f4_idx = {_RANDOM_23[31:22], _RANDOM_24[26:0]};
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  assign io_f3_pred = f3_entry_tag == f3_tag & f3_scnt == f3_entry_p_cnt & (&f3_entry_conf) ^ io_f3_pred_in;
  assign io_f3_meta_s_cnt = f3_scnt;
endmodule

