// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module RenameStage(
  input         clock,
                reset,
                io_kill,
                io_dec_fire_0,
  input  [6:0]  io_dec_uops_0_uopc,
  input  [31:0] io_dec_uops_0_inst,
                io_dec_uops_0_debug_inst,
  input         io_dec_uops_0_is_rvc,
  input  [39:0] io_dec_uops_0_debug_pc,
  input  [2:0]  io_dec_uops_0_iq_type,
  input  [9:0]  io_dec_uops_0_fu_code,
  input  [3:0]  io_dec_uops_0_ctrl_br_type,
  input  [1:0]  io_dec_uops_0_ctrl_op1_sel,
  input  [2:0]  io_dec_uops_0_ctrl_op2_sel,
                io_dec_uops_0_ctrl_imm_sel,
  input  [3:0]  io_dec_uops_0_ctrl_op_fcn,
  input         io_dec_uops_0_ctrl_fcn_dw,
  input  [2:0]  io_dec_uops_0_ctrl_csr_cmd,
  input         io_dec_uops_0_ctrl_is_load,
                io_dec_uops_0_ctrl_is_sta,
                io_dec_uops_0_ctrl_is_std,
  input  [1:0]  io_dec_uops_0_iw_state,
  input         io_dec_uops_0_iw_p1_poisoned,
                io_dec_uops_0_iw_p2_poisoned,
                io_dec_uops_0_is_br,
                io_dec_uops_0_is_jalr,
                io_dec_uops_0_is_jal,
                io_dec_uops_0_is_sfb,
  input  [7:0]  io_dec_uops_0_br_mask,
  input  [2:0]  io_dec_uops_0_br_tag,
  input  [3:0]  io_dec_uops_0_ftq_idx,
  input         io_dec_uops_0_edge_inst,
  input  [5:0]  io_dec_uops_0_pc_lob,
  input         io_dec_uops_0_taken,
  input  [19:0] io_dec_uops_0_imm_packed,
  input  [11:0] io_dec_uops_0_csr_addr,
  input  [1:0]  io_dec_uops_0_rxq_idx,
  input         io_dec_uops_0_exception,
  input  [63:0] io_dec_uops_0_exc_cause,
  input         io_dec_uops_0_bypassable,
  input  [4:0]  io_dec_uops_0_mem_cmd,
  input  [1:0]  io_dec_uops_0_mem_size,
  input         io_dec_uops_0_mem_signed,
                io_dec_uops_0_is_fence,
                io_dec_uops_0_is_fencei,
                io_dec_uops_0_is_amo,
                io_dec_uops_0_uses_ldq,
                io_dec_uops_0_uses_stq,
                io_dec_uops_0_is_sys_pc2epc,
                io_dec_uops_0_is_unique,
                io_dec_uops_0_flush_on_commit,
  input  [5:0]  io_dec_uops_0_ldst,
                io_dec_uops_0_lrs1,
                io_dec_uops_0_lrs2,
                io_dec_uops_0_lrs3,
  input         io_dec_uops_0_ldst_val,
  input  [1:0]  io_dec_uops_0_dst_rtype,
                io_dec_uops_0_lrs1_rtype,
                io_dec_uops_0_lrs2_rtype,
  input         io_dec_uops_0_frs3_en,
                io_dec_uops_0_fp_val,
                io_dec_uops_0_fp_single,
                io_dec_uops_0_xcpt_pf_if,
                io_dec_uops_0_xcpt_ae_if,
                io_dec_uops_0_xcpt_ma_if,
                io_dec_uops_0_bp_debug_if,
                io_dec_uops_0_bp_xcpt_if,
  input  [1:0]  io_dec_uops_0_debug_fsrc,
                io_dec_uops_0_debug_tsrc,
  input  [7:0]  io_brupdate_b1_resolve_mask,
  input  [2:0]  io_brupdate_b2_uop_br_tag,
  input         io_brupdate_b2_mispredict,
                io_dis_fire_0,
                io_dis_ready,
                io_wakeups_0_valid,
  input  [5:0]  io_wakeups_0_bits_uop_pdst,
  input  [1:0]  io_wakeups_0_bits_uop_dst_rtype,
  input         io_wakeups_1_valid,
  input  [5:0]  io_wakeups_1_bits_uop_pdst,
  input  [1:0]  io_wakeups_1_bits_uop_dst_rtype,
  input         io_wakeups_2_valid,
  input  [5:0]  io_wakeups_2_bits_uop_pdst,
  input  [1:0]  io_wakeups_2_bits_uop_dst_rtype,
  input         io_com_valids_0,
  input  [5:0]  io_com_uops_0_pdst,
                io_com_uops_0_stale_pdst,
                io_com_uops_0_ldst,
  input         io_com_uops_0_ldst_val,
  input  [1:0]  io_com_uops_0_dst_rtype,
  input         io_rbk_valids_0,
                io_rollback,
                io_debug_rob_empty,
  output        io_ren_stalls_0,
                io_ren2_mask_0,
  output [6:0]  io_ren2_uops_0_uopc,
  output [31:0] io_ren2_uops_0_inst,
                io_ren2_uops_0_debug_inst,
  output        io_ren2_uops_0_is_rvc,
  output [39:0] io_ren2_uops_0_debug_pc,
  output [2:0]  io_ren2_uops_0_iq_type,
  output [9:0]  io_ren2_uops_0_fu_code,
  output [3:0]  io_ren2_uops_0_ctrl_br_type,
  output [1:0]  io_ren2_uops_0_ctrl_op1_sel,
  output [2:0]  io_ren2_uops_0_ctrl_op2_sel,
                io_ren2_uops_0_ctrl_imm_sel,
  output [3:0]  io_ren2_uops_0_ctrl_op_fcn,
  output        io_ren2_uops_0_ctrl_fcn_dw,
  output [2:0]  io_ren2_uops_0_ctrl_csr_cmd,
  output        io_ren2_uops_0_ctrl_is_load,
                io_ren2_uops_0_ctrl_is_sta,
                io_ren2_uops_0_ctrl_is_std,
  output [1:0]  io_ren2_uops_0_iw_state,
  output        io_ren2_uops_0_iw_p1_poisoned,
                io_ren2_uops_0_iw_p2_poisoned,
                io_ren2_uops_0_is_br,
                io_ren2_uops_0_is_jalr,
                io_ren2_uops_0_is_jal,
                io_ren2_uops_0_is_sfb,
  output [7:0]  io_ren2_uops_0_br_mask,
  output [2:0]  io_ren2_uops_0_br_tag,
  output [3:0]  io_ren2_uops_0_ftq_idx,
  output        io_ren2_uops_0_edge_inst,
  output [5:0]  io_ren2_uops_0_pc_lob,
  output        io_ren2_uops_0_taken,
  output [19:0] io_ren2_uops_0_imm_packed,
  output [11:0] io_ren2_uops_0_csr_addr,
  output [1:0]  io_ren2_uops_0_rxq_idx,
  output [5:0]  io_ren2_uops_0_pdst,
                io_ren2_uops_0_prs1,
                io_ren2_uops_0_prs2,
  output        io_ren2_uops_0_prs1_busy,
                io_ren2_uops_0_prs2_busy,
  output [5:0]  io_ren2_uops_0_stale_pdst,
  output        io_ren2_uops_0_exception,
  output [63:0] io_ren2_uops_0_exc_cause,
  output        io_ren2_uops_0_bypassable,
  output [4:0]  io_ren2_uops_0_mem_cmd,
  output [1:0]  io_ren2_uops_0_mem_size,
  output        io_ren2_uops_0_mem_signed,
                io_ren2_uops_0_is_fence,
                io_ren2_uops_0_is_fencei,
                io_ren2_uops_0_is_amo,
                io_ren2_uops_0_uses_ldq,
                io_ren2_uops_0_uses_stq,
                io_ren2_uops_0_is_sys_pc2epc,
                io_ren2_uops_0_is_unique,
                io_ren2_uops_0_flush_on_commit,
                io_ren2_uops_0_ldst_is_rs1,
  output [5:0]  io_ren2_uops_0_ldst,
                io_ren2_uops_0_lrs1,
                io_ren2_uops_0_lrs2,
                io_ren2_uops_0_lrs3,
  output        io_ren2_uops_0_ldst_val,
  output [1:0]  io_ren2_uops_0_dst_rtype,
                io_ren2_uops_0_lrs1_rtype,
                io_ren2_uops_0_lrs2_rtype,
  output        io_ren2_uops_0_frs3_en,
                io_ren2_uops_0_fp_val,
                io_ren2_uops_0_fp_single,
                io_ren2_uops_0_xcpt_pf_if,
                io_ren2_uops_0_xcpt_ae_if,
                io_ren2_uops_0_xcpt_ma_if,
                io_ren2_uops_0_bp_debug_if,
                io_ren2_uops_0_bp_xcpt_if,
  output [1:0]  io_ren2_uops_0_debug_fsrc,
                io_ren2_uops_0_debug_tsrc
);

  wire [5:0]  io_ren2_uops_0_newuop_pdst;
  wire        _busytable_io_busy_resps_0_prs1_busy;
  wire        _busytable_io_busy_resps_0_prs2_busy;
  wire        _freelist_io_alloc_pregs_0_valid;
  wire [5:0]  _freelist_io_alloc_pregs_0_bits;
  wire [5:0]  _maptable_io_map_resps_0_prs1;
  wire [5:0]  _maptable_io_map_resps_0_prs2;
  wire [5:0]  _maptable_io_map_resps_0_stale_pdst;
  reg         r_valid;
  reg  [6:0]  r_uop_uopc;
  reg  [31:0] r_uop_inst;
  reg  [31:0] r_uop_debug_inst;
  reg         r_uop_is_rvc;
  reg  [39:0] r_uop_debug_pc;
  reg  [2:0]  r_uop_iq_type;
  reg  [9:0]  r_uop_fu_code;
  reg  [3:0]  r_uop_ctrl_br_type;
  reg  [1:0]  r_uop_ctrl_op1_sel;
  reg  [2:0]  r_uop_ctrl_op2_sel;
  reg  [2:0]  r_uop_ctrl_imm_sel;
  reg  [3:0]  r_uop_ctrl_op_fcn;
  reg         r_uop_ctrl_fcn_dw;
  reg  [2:0]  r_uop_ctrl_csr_cmd;
  reg         r_uop_ctrl_is_load;
  reg         r_uop_ctrl_is_sta;
  reg         r_uop_ctrl_is_std;
  reg  [1:0]  r_uop_iw_state;
  reg         r_uop_iw_p1_poisoned;
  reg         r_uop_iw_p2_poisoned;
  reg         r_uop_is_br;
  reg         r_uop_is_jalr;
  reg         r_uop_is_jal;
  reg         r_uop_is_sfb;
  reg  [7:0]  r_uop_br_mask;
  reg  [2:0]  r_uop_br_tag;
  reg  [3:0]  r_uop_ftq_idx;
  reg         r_uop_edge_inst;
  reg  [5:0]  r_uop_pc_lob;
  reg         r_uop_taken;
  reg  [19:0] r_uop_imm_packed;
  reg  [11:0] r_uop_csr_addr;
  reg  [1:0]  r_uop_rxq_idx;
  reg  [5:0]  r_uop_prs1;
  reg  [5:0]  r_uop_prs2;
  reg  [5:0]  r_uop_stale_pdst;
  reg         r_uop_exception;
  reg  [63:0] r_uop_exc_cause;
  reg         r_uop_bypassable;
  reg  [4:0]  r_uop_mem_cmd;
  reg  [1:0]  r_uop_mem_size;
  reg         r_uop_mem_signed;
  reg         r_uop_is_fence;
  reg         r_uop_is_fencei;
  reg         r_uop_is_amo;
  reg         r_uop_uses_ldq;
  reg         r_uop_uses_stq;
  reg         r_uop_is_sys_pc2epc;
  reg         r_uop_is_unique;
  reg         r_uop_flush_on_commit;
  reg         r_uop_ldst_is_rs1;
  reg  [5:0]  r_uop_ldst;
  reg  [5:0]  r_uop_lrs1;
  reg  [5:0]  r_uop_lrs2;
  reg  [5:0]  r_uop_lrs3;
  reg         r_uop_ldst_val;
  reg  [1:0]  r_uop_dst_rtype;
  reg  [1:0]  r_uop_lrs1_rtype;
  reg  [1:0]  r_uop_lrs2_rtype;
  reg         r_uop_frs3_en;
  reg         r_uop_fp_val;
  reg         r_uop_fp_single;
  reg         r_uop_xcpt_pf_if;
  reg         r_uop_xcpt_ae_if;
  reg         r_uop_xcpt_ma_if;
  reg         r_uop_bp_debug_if;
  reg         r_uop_bp_xcpt_if;
  reg  [1:0]  r_uop_debug_fsrc;
  reg  [1:0]  r_uop_debug_tsrc;
  wire        _io_ren_stalls_0_T = r_uop_dst_rtype == 2'h0;
  wire        ren2_alloc_reqs_0 = r_uop_ldst_val & _io_ren_stalls_0_T & io_dis_fire_0;
  wire        ren2_br_tags_0_valid = io_dis_fire_0 & (r_uop_is_br & ~r_uop_is_sfb | r_uop_is_jalr);
  wire        _rbk_valids_0_T = io_com_uops_0_dst_rtype == 2'h0;
  wire        rbk_valids_0 = io_com_uops_0_ldst_val & _rbk_valids_0_T & io_rbk_valids_0;
  assign io_ren2_uops_0_newuop_pdst = (|r_uop_ldst) ? _freelist_io_alloc_pregs_0_bits : 6'h0;
  wire        _GEN = io_kill | ~io_dis_ready;
  always @(posedge clock) begin
    if (reset)
      r_valid <= 1'h0;
    else
      r_valid <= ~io_kill & (io_dis_ready ? io_dec_fire_0 : r_valid & ~io_dis_fire_0);
    if (_GEN) begin
    end
    else begin
      r_uop_uopc <= io_dec_uops_0_uopc;
      r_uop_inst <= io_dec_uops_0_inst;
      r_uop_debug_inst <= io_dec_uops_0_debug_inst;
      r_uop_is_rvc <= io_dec_uops_0_is_rvc;
      r_uop_debug_pc <= io_dec_uops_0_debug_pc;
      r_uop_iq_type <= io_dec_uops_0_iq_type;
      r_uop_fu_code <= io_dec_uops_0_fu_code;
      r_uop_ctrl_br_type <= io_dec_uops_0_ctrl_br_type;
      r_uop_ctrl_op1_sel <= io_dec_uops_0_ctrl_op1_sel;
      r_uop_ctrl_op2_sel <= io_dec_uops_0_ctrl_op2_sel;
      r_uop_ctrl_imm_sel <= io_dec_uops_0_ctrl_imm_sel;
      r_uop_ctrl_op_fcn <= io_dec_uops_0_ctrl_op_fcn;
      r_uop_ctrl_fcn_dw <= io_dec_uops_0_ctrl_fcn_dw;
      r_uop_ctrl_csr_cmd <= io_dec_uops_0_ctrl_csr_cmd;
      r_uop_ctrl_is_load <= io_dec_uops_0_ctrl_is_load;
      r_uop_ctrl_is_sta <= io_dec_uops_0_ctrl_is_sta;
      r_uop_ctrl_is_std <= io_dec_uops_0_ctrl_is_std;
      r_uop_iw_state <= io_dec_uops_0_iw_state;
      r_uop_iw_p1_poisoned <= io_dec_uops_0_iw_p1_poisoned;
      r_uop_iw_p2_poisoned <= io_dec_uops_0_iw_p2_poisoned;
      r_uop_is_br <= io_dec_uops_0_is_br;
      r_uop_is_jalr <= io_dec_uops_0_is_jalr;
      r_uop_is_jal <= io_dec_uops_0_is_jal;
      r_uop_is_sfb <= io_dec_uops_0_is_sfb;
      r_uop_br_tag <= io_dec_uops_0_br_tag;
      r_uop_ftq_idx <= io_dec_uops_0_ftq_idx;
      r_uop_edge_inst <= io_dec_uops_0_edge_inst;
      r_uop_pc_lob <= io_dec_uops_0_pc_lob;
      r_uop_taken <= io_dec_uops_0_taken;
      r_uop_imm_packed <= io_dec_uops_0_imm_packed;
      r_uop_csr_addr <= io_dec_uops_0_csr_addr;
      r_uop_rxq_idx <= io_dec_uops_0_rxq_idx;
      r_uop_exception <= io_dec_uops_0_exception;
      r_uop_exc_cause <= io_dec_uops_0_exc_cause;
      r_uop_bypassable <= io_dec_uops_0_bypassable;
      r_uop_mem_cmd <= io_dec_uops_0_mem_cmd;
      r_uop_mem_size <= io_dec_uops_0_mem_size;
      r_uop_mem_signed <= io_dec_uops_0_mem_signed;
      r_uop_is_fence <= io_dec_uops_0_is_fence;
      r_uop_is_fencei <= io_dec_uops_0_is_fencei;
      r_uop_is_amo <= io_dec_uops_0_is_amo;
      r_uop_uses_ldq <= io_dec_uops_0_uses_ldq;
      r_uop_uses_stq <= io_dec_uops_0_uses_stq;
      r_uop_is_sys_pc2epc <= io_dec_uops_0_is_sys_pc2epc;
      r_uop_is_unique <= io_dec_uops_0_is_unique;
      r_uop_flush_on_commit <= io_dec_uops_0_flush_on_commit;
      r_uop_ldst <= io_dec_uops_0_ldst;
      r_uop_lrs1 <= io_dec_uops_0_lrs1;
      r_uop_lrs2 <= io_dec_uops_0_lrs2;
      r_uop_lrs3 <= io_dec_uops_0_lrs3;
      r_uop_ldst_val <= io_dec_uops_0_ldst_val;
      r_uop_dst_rtype <= io_dec_uops_0_dst_rtype;
      r_uop_lrs1_rtype <= io_dec_uops_0_lrs1_rtype;
      r_uop_lrs2_rtype <= io_dec_uops_0_lrs2_rtype;
      r_uop_frs3_en <= io_dec_uops_0_frs3_en;
      r_uop_fp_val <= io_dec_uops_0_fp_val;
      r_uop_fp_single <= io_dec_uops_0_fp_single;
      r_uop_xcpt_pf_if <= io_dec_uops_0_xcpt_pf_if;
      r_uop_xcpt_ae_if <= io_dec_uops_0_xcpt_ae_if;
      r_uop_xcpt_ma_if <= io_dec_uops_0_xcpt_ma_if;
      r_uop_bp_debug_if <= io_dec_uops_0_bp_debug_if;
      r_uop_bp_xcpt_if <= io_dec_uops_0_bp_xcpt_if;
      r_uop_debug_fsrc <= io_dec_uops_0_debug_fsrc;
      r_uop_debug_tsrc <= io_dec_uops_0_debug_tsrc;
    end
    r_uop_br_mask <= (_GEN ? r_uop_br_mask : io_dec_uops_0_br_mask) & ~io_brupdate_b1_resolve_mask;
    if (ren2_alloc_reqs_0 & r_uop_ldst == (_GEN ? r_uop_lrs1 : io_dec_uops_0_lrs1)) begin
      if (|r_uop_ldst)
        r_uop_prs1 <= _freelist_io_alloc_pregs_0_bits;
      else
        r_uop_prs1 <= 6'h0;
    end
    else if (_GEN) begin
    end
    else
      r_uop_prs1 <= _maptable_io_map_resps_0_prs1;
    if (ren2_alloc_reqs_0 & r_uop_ldst == (_GEN ? r_uop_lrs2 : io_dec_uops_0_lrs2)) begin
      if (|r_uop_ldst)
        r_uop_prs2 <= _freelist_io_alloc_pregs_0_bits;
      else
        r_uop_prs2 <= 6'h0;
    end
    else if (_GEN) begin
    end
    else
      r_uop_prs2 <= _maptable_io_map_resps_0_prs2;
    if (ren2_alloc_reqs_0 & r_uop_ldst == (_GEN ? r_uop_ldst : io_dec_uops_0_ldst)) begin
      if (|r_uop_ldst)
        r_uop_stale_pdst <= _freelist_io_alloc_pregs_0_bits;
      else
        r_uop_stale_pdst <= 6'h0;
    end
    else if (_GEN) begin
    end
    else
      r_uop_stale_pdst <= _maptable_io_map_resps_0_stale_pdst;
    r_uop_ldst_is_rs1 <= _GEN & r_uop_ldst_is_rs1;
  end // always @(posedge)
  `ifndef SYNTHESIS
    always @(posedge clock) begin
      if (~reset & ~(~ren2_alloc_reqs_0 | (|_freelist_io_alloc_pregs_0_bits))) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed: [rename-stage] A uop is trying to allocate the zero physical register.\n    at rename-stage.scala:297 assert (ren2_alloc_reqs zip freelist.io.alloc_pregs map {case (r,p) => !r || p.bits =/= 0.U} reduce (_&&_),\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & (io_wakeups_0_valid & (|io_wakeups_0_bits_uop_dst_rtype) | io_wakeups_1_valid & (|io_wakeups_1_bits_uop_dst_rtype) | io_wakeups_2_valid & (|io_wakeups_2_bits_uop_dst_rtype))) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed: [rename] Wakeup has wrong rtype.\n    at rename-stage.scala:314 assert (!(io.wakeups.map(x => x.valid && x.bits.uop.dst_rtype =/= rtype).reduce(_||_)),\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & r_valid & _busytable_io_busy_resps_0_prs1_busy & r_uop_lrs1 == 6'h0) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed: [rename] x0 is busy??\n    at rename-stage.scala:325 assert (!(valid && busy.prs1_busy && rtype === RT_FIX && uop.lrs1 === 0.U), \"[rename] x0 is busy??\")\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & r_valid & _busytable_io_busy_resps_0_prs2_busy & r_uop_lrs2 == 6'h0) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed: [rename] x0 is busy??\n    at rename-stage.scala:326 assert (!(valid && busy.prs2_busy && rtype === RT_FIX && uop.lrs2 === 0.U), \"[rename] x0 is busy??\")\n");
        if (`STOP_COND_)
          $fatal;
      end
    end // always @(posedge)
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM_0;
    logic [31:0] _RANDOM_1;
    logic [31:0] _RANDOM_2;
    logic [31:0] _RANDOM_3;
    logic [31:0] _RANDOM_4;
    logic [31:0] _RANDOM_5;
    logic [31:0] _RANDOM_6;
    logic [31:0] _RANDOM_7;
    logic [31:0] _RANDOM_8;
    logic [31:0] _RANDOM_9;
    logic [31:0] _RANDOM_10;
    logic [31:0] _RANDOM_11;
    logic [31:0] _RANDOM_12;
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM_0 = `RANDOM;
        _RANDOM_1 = `RANDOM;
        _RANDOM_2 = `RANDOM;
        _RANDOM_3 = `RANDOM;
        _RANDOM_4 = `RANDOM;
        _RANDOM_5 = `RANDOM;
        _RANDOM_6 = `RANDOM;
        _RANDOM_7 = `RANDOM;
        _RANDOM_8 = `RANDOM;
        _RANDOM_9 = `RANDOM;
        _RANDOM_10 = `RANDOM;
        _RANDOM_11 = `RANDOM;
        _RANDOM_12 = `RANDOM;
        r_valid = _RANDOM_0[0];
        r_uop_uopc = _RANDOM_0[7:1];
        r_uop_inst = {_RANDOM_0[31:8], _RANDOM_1[7:0]};
        r_uop_debug_inst = {_RANDOM_1[31:8], _RANDOM_2[7:0]};
        r_uop_is_rvc = _RANDOM_2[8];
        r_uop_debug_pc = {_RANDOM_2[31:9], _RANDOM_3[16:0]};
        r_uop_iq_type = _RANDOM_3[19:17];
        r_uop_fu_code = _RANDOM_3[29:20];
        r_uop_ctrl_br_type = {_RANDOM_3[31:30], _RANDOM_4[1:0]};
        r_uop_ctrl_op1_sel = _RANDOM_4[3:2];
        r_uop_ctrl_op2_sel = _RANDOM_4[6:4];
        r_uop_ctrl_imm_sel = _RANDOM_4[9:7];
        r_uop_ctrl_op_fcn = _RANDOM_4[13:10];
        r_uop_ctrl_fcn_dw = _RANDOM_4[14];
        r_uop_ctrl_csr_cmd = _RANDOM_4[17:15];
        r_uop_ctrl_is_load = _RANDOM_4[18];
        r_uop_ctrl_is_sta = _RANDOM_4[19];
        r_uop_ctrl_is_std = _RANDOM_4[20];
        r_uop_iw_state = _RANDOM_4[22:21];
        r_uop_iw_p1_poisoned = _RANDOM_4[23];
        r_uop_iw_p2_poisoned = _RANDOM_4[24];
        r_uop_is_br = _RANDOM_4[25];
        r_uop_is_jalr = _RANDOM_4[26];
        r_uop_is_jal = _RANDOM_4[27];
        r_uop_is_sfb = _RANDOM_4[28];
        r_uop_br_mask = {_RANDOM_4[31:29], _RANDOM_5[4:0]};
        r_uop_br_tag = _RANDOM_5[7:5];
        r_uop_ftq_idx = _RANDOM_5[11:8];
        r_uop_edge_inst = _RANDOM_5[12];
        r_uop_pc_lob = _RANDOM_5[18:13];
        r_uop_taken = _RANDOM_5[19];
        r_uop_imm_packed = {_RANDOM_5[31:20], _RANDOM_6[7:0]};
        r_uop_csr_addr = _RANDOM_6[19:8];
        r_uop_rxq_idx = {_RANDOM_6[31], _RANDOM_7[0]};
        r_uop_prs1 = _RANDOM_7[12:7];
        r_uop_prs2 = _RANDOM_7[18:13];
        r_uop_stale_pdst = _RANDOM_8[6:1];
        r_uop_exception = _RANDOM_8[7];
        r_uop_exc_cause = {_RANDOM_8[31:8], _RANDOM_9, _RANDOM_10[7:0]};
        r_uop_bypassable = _RANDOM_10[8];
        r_uop_mem_cmd = _RANDOM_10[13:9];
        r_uop_mem_size = _RANDOM_10[15:14];
        r_uop_mem_signed = _RANDOM_10[16];
        r_uop_is_fence = _RANDOM_10[17];
        r_uop_is_fencei = _RANDOM_10[18];
        r_uop_is_amo = _RANDOM_10[19];
        r_uop_uses_ldq = _RANDOM_10[20];
        r_uop_uses_stq = _RANDOM_10[21];
        r_uop_is_sys_pc2epc = _RANDOM_10[22];
        r_uop_is_unique = _RANDOM_10[23];
        r_uop_flush_on_commit = _RANDOM_10[24];
        r_uop_ldst_is_rs1 = _RANDOM_10[25];
        r_uop_ldst = _RANDOM_10[31:26];
        r_uop_lrs1 = _RANDOM_11[5:0];
        r_uop_lrs2 = _RANDOM_11[11:6];
        r_uop_lrs3 = _RANDOM_11[17:12];
        r_uop_ldst_val = _RANDOM_11[18];
        r_uop_dst_rtype = _RANDOM_11[20:19];
        r_uop_lrs1_rtype = _RANDOM_11[22:21];
        r_uop_lrs2_rtype = _RANDOM_11[24:23];
        r_uop_frs3_en = _RANDOM_11[25];
        r_uop_fp_val = _RANDOM_11[26];
        r_uop_fp_single = _RANDOM_11[27];
        r_uop_xcpt_pf_if = _RANDOM_11[28];
        r_uop_xcpt_ae_if = _RANDOM_11[29];
        r_uop_xcpt_ma_if = _RANDOM_11[30];
        r_uop_bp_debug_if = _RANDOM_11[31];
        r_uop_bp_xcpt_if = _RANDOM_12[0];
        r_uop_debug_fsrc = _RANDOM_12[2:1];
        r_uop_debug_tsrc = _RANDOM_12[4:3];
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  RenameMapTable maptable (
    .clock                     (clock),
    .reset                     (reset),
    .io_map_reqs_0_lrs1        (io_dec_uops_0_lrs1),
    .io_map_reqs_0_lrs2        (io_dec_uops_0_lrs2),
    .io_map_reqs_0_ldst        (io_dec_uops_0_ldst),
    .io_remap_reqs_0_ldst      (io_rollback ? io_com_uops_0_ldst : r_uop_ldst),
    .io_remap_reqs_0_pdst      (io_rollback ? io_com_uops_0_stale_pdst : io_ren2_uops_0_newuop_pdst),
    .io_remap_reqs_0_valid     (ren2_alloc_reqs_0 | rbk_valids_0),
    .io_ren_br_tags_0_valid    (ren2_br_tags_0_valid),
    .io_ren_br_tags_0_bits     (r_uop_br_tag),
    .io_brupdate_b2_uop_br_tag (io_brupdate_b2_uop_br_tag),
    .io_brupdate_b2_mispredict (io_brupdate_b2_mispredict),
    .io_rollback               (io_rollback),
    .io_map_resps_0_prs1       (_maptable_io_map_resps_0_prs1),
    .io_map_resps_0_prs2       (_maptable_io_map_resps_0_prs2),
    .io_map_resps_0_stale_pdst (_maptable_io_map_resps_0_stale_pdst)
  );
  RenameFreeList freelist (
    .clock                     (clock),
    .reset                     (reset),
    .io_reqs_0                 (ren2_alloc_reqs_0),
    .io_dealloc_pregs_0_valid  (io_com_uops_0_ldst_val & _rbk_valids_0_T & io_com_valids_0 | rbk_valids_0),
    .io_dealloc_pregs_0_bits   (io_rollback ? io_com_uops_0_pdst : io_com_uops_0_stale_pdst),
    .io_ren_br_tags_0_valid    (ren2_br_tags_0_valid),
    .io_ren_br_tags_0_bits     (r_uop_br_tag),
    .io_brupdate_b2_uop_br_tag (io_brupdate_b2_uop_br_tag),
    .io_brupdate_b2_mispredict (io_brupdate_b2_mispredict),
    .io_debug_pipeline_empty   (io_debug_rob_empty),
    .io_alloc_pregs_0_valid    (_freelist_io_alloc_pregs_0_valid),
    .io_alloc_pregs_0_bits     (_freelist_io_alloc_pregs_0_bits)
  );
  RenameBusyTable busytable (
    .clock                     (clock),
    .reset                     (reset),
    .io_ren_uops_0_pdst        (io_ren2_uops_0_newuop_pdst),
    .io_ren_uops_0_prs1        (r_uop_prs1),
    .io_ren_uops_0_prs2        (r_uop_prs2),
    .io_rebusy_reqs_0          (ren2_alloc_reqs_0),
    .io_wb_pdsts_0             (io_wakeups_0_bits_uop_pdst),
    .io_wb_pdsts_1             (io_wakeups_1_bits_uop_pdst),
    .io_wb_pdsts_2             (io_wakeups_2_bits_uop_pdst),
    .io_wb_valids_0            (io_wakeups_0_valid),
    .io_wb_valids_1            (io_wakeups_1_valid),
    .io_wb_valids_2            (io_wakeups_2_valid),
    .io_busy_resps_0_prs1_busy (_busytable_io_busy_resps_0_prs1_busy),
    .io_busy_resps_0_prs2_busy (_busytable_io_busy_resps_0_prs2_busy)
  );
  assign io_ren_stalls_0 = _io_ren_stalls_0_T & ~_freelist_io_alloc_pregs_0_valid;
  assign io_ren2_mask_0 = r_valid;
  assign io_ren2_uops_0_uopc = r_uop_uopc;
  assign io_ren2_uops_0_inst = r_uop_inst;
  assign io_ren2_uops_0_debug_inst = r_uop_debug_inst;
  assign io_ren2_uops_0_is_rvc = r_uop_is_rvc;
  assign io_ren2_uops_0_debug_pc = r_uop_debug_pc;
  assign io_ren2_uops_0_iq_type = r_uop_iq_type;
  assign io_ren2_uops_0_fu_code = r_uop_fu_code;
  assign io_ren2_uops_0_ctrl_br_type = r_uop_ctrl_br_type;
  assign io_ren2_uops_0_ctrl_op1_sel = r_uop_ctrl_op1_sel;
  assign io_ren2_uops_0_ctrl_op2_sel = r_uop_ctrl_op2_sel;
  assign io_ren2_uops_0_ctrl_imm_sel = r_uop_ctrl_imm_sel;
  assign io_ren2_uops_0_ctrl_op_fcn = r_uop_ctrl_op_fcn;
  assign io_ren2_uops_0_ctrl_fcn_dw = r_uop_ctrl_fcn_dw;
  assign io_ren2_uops_0_ctrl_csr_cmd = r_uop_ctrl_csr_cmd;
  assign io_ren2_uops_0_ctrl_is_load = r_uop_ctrl_is_load;
  assign io_ren2_uops_0_ctrl_is_sta = r_uop_ctrl_is_sta;
  assign io_ren2_uops_0_ctrl_is_std = r_uop_ctrl_is_std;
  assign io_ren2_uops_0_iw_state = r_uop_iw_state;
  assign io_ren2_uops_0_iw_p1_poisoned = r_uop_iw_p1_poisoned;
  assign io_ren2_uops_0_iw_p2_poisoned = r_uop_iw_p2_poisoned;
  assign io_ren2_uops_0_is_br = r_uop_is_br;
  assign io_ren2_uops_0_is_jalr = r_uop_is_jalr;
  assign io_ren2_uops_0_is_jal = r_uop_is_jal;
  assign io_ren2_uops_0_is_sfb = r_uop_is_sfb;
  assign io_ren2_uops_0_br_mask = r_uop_br_mask & ~io_brupdate_b1_resolve_mask;
  assign io_ren2_uops_0_br_tag = r_uop_br_tag;
  assign io_ren2_uops_0_ftq_idx = r_uop_ftq_idx;
  assign io_ren2_uops_0_edge_inst = r_uop_edge_inst;
  assign io_ren2_uops_0_pc_lob = r_uop_pc_lob;
  assign io_ren2_uops_0_taken = r_uop_taken;
  assign io_ren2_uops_0_imm_packed = r_uop_imm_packed;
  assign io_ren2_uops_0_csr_addr = r_uop_csr_addr;
  assign io_ren2_uops_0_rxq_idx = r_uop_rxq_idx;
  assign io_ren2_uops_0_pdst = io_ren2_uops_0_newuop_pdst;
  assign io_ren2_uops_0_prs1 = r_uop_prs1;
  assign io_ren2_uops_0_prs2 = r_uop_prs2;
  assign io_ren2_uops_0_prs1_busy = r_uop_lrs1_rtype == 2'h0 & _busytable_io_busy_resps_0_prs1_busy;
  assign io_ren2_uops_0_prs2_busy = r_uop_lrs2_rtype == 2'h0 & _busytable_io_busy_resps_0_prs2_busy;
  assign io_ren2_uops_0_stale_pdst = r_uop_stale_pdst;
  assign io_ren2_uops_0_exception = r_uop_exception;
  assign io_ren2_uops_0_exc_cause = r_uop_exc_cause;
  assign io_ren2_uops_0_bypassable = r_uop_bypassable;
  assign io_ren2_uops_0_mem_cmd = r_uop_mem_cmd;
  assign io_ren2_uops_0_mem_size = r_uop_mem_size;
  assign io_ren2_uops_0_mem_signed = r_uop_mem_signed;
  assign io_ren2_uops_0_is_fence = r_uop_is_fence;
  assign io_ren2_uops_0_is_fencei = r_uop_is_fencei;
  assign io_ren2_uops_0_is_amo = r_uop_is_amo;
  assign io_ren2_uops_0_uses_ldq = r_uop_uses_ldq;
  assign io_ren2_uops_0_uses_stq = r_uop_uses_stq;
  assign io_ren2_uops_0_is_sys_pc2epc = r_uop_is_sys_pc2epc;
  assign io_ren2_uops_0_is_unique = r_uop_is_unique;
  assign io_ren2_uops_0_flush_on_commit = r_uop_flush_on_commit;
  assign io_ren2_uops_0_ldst_is_rs1 = r_uop_ldst_is_rs1;
  assign io_ren2_uops_0_ldst = r_uop_ldst;
  assign io_ren2_uops_0_lrs1 = r_uop_lrs1;
  assign io_ren2_uops_0_lrs2 = r_uop_lrs2;
  assign io_ren2_uops_0_lrs3 = r_uop_lrs3;
  assign io_ren2_uops_0_ldst_val = r_uop_ldst_val;
  assign io_ren2_uops_0_dst_rtype = r_uop_dst_rtype;
  assign io_ren2_uops_0_lrs1_rtype = r_uop_lrs1_rtype;
  assign io_ren2_uops_0_lrs2_rtype = r_uop_lrs2_rtype;
  assign io_ren2_uops_0_frs3_en = r_uop_frs3_en;
  assign io_ren2_uops_0_fp_val = r_uop_fp_val;
  assign io_ren2_uops_0_fp_single = r_uop_fp_single;
  assign io_ren2_uops_0_xcpt_pf_if = r_uop_xcpt_pf_if;
  assign io_ren2_uops_0_xcpt_ae_if = r_uop_xcpt_ae_if;
  assign io_ren2_uops_0_xcpt_ma_if = r_uop_xcpt_ma_if;
  assign io_ren2_uops_0_bp_debug_if = r_uop_bp_debug_if;
  assign io_ren2_uops_0_bp_xcpt_if = r_uop_bp_xcpt_if;
  assign io_ren2_uops_0_debug_fsrc = r_uop_debug_fsrc;
  assign io_ren2_uops_0_debug_tsrc = r_uop_debug_tsrc;
endmodule

