// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module TLXbar(
  input         clock,
                reset,
                auto_in_1_a_valid,
  input  [2:0]  auto_in_1_a_bits_opcode,
                auto_in_1_a_bits_param,
  input  [3:0]  auto_in_1_a_bits_size,
  input  [2:0]  auto_in_1_a_bits_source,
  input  [31:0] auto_in_1_a_bits_address,
  input  [7:0]  auto_in_1_a_bits_mask,
  input  [63:0] auto_in_1_a_bits_data,
  input         auto_in_1_a_bits_corrupt,
                auto_in_1_b_ready,
                auto_in_1_c_valid,
  input  [2:0]  auto_in_1_c_bits_opcode,
                auto_in_1_c_bits_param,
  input  [3:0]  auto_in_1_c_bits_size,
  input  [2:0]  auto_in_1_c_bits_source,
  input  [31:0] auto_in_1_c_bits_address,
  input  [63:0] auto_in_1_c_bits_data,
  input         auto_in_1_c_bits_corrupt,
                auto_in_1_d_ready,
                auto_in_1_e_valid,
  input  [2:0]  auto_in_1_e_bits_sink,
  input         auto_in_0_a_valid,
  input  [2:0]  auto_in_0_a_bits_opcode,
                auto_in_0_a_bits_param,
  input  [3:0]  auto_in_0_a_bits_size,
  input         auto_in_0_a_bits_source,
  input  [31:0] auto_in_0_a_bits_address,
  input  [7:0]  auto_in_0_a_bits_mask,
  input  [63:0] auto_in_0_a_bits_data,
  input         auto_in_0_a_bits_corrupt,
                auto_in_0_d_ready,
                auto_out_1_a_ready,
                auto_out_1_b_valid,
  input  [1:0]  auto_out_1_b_bits_param,
  input  [31:0] auto_out_1_b_bits_address,
  input         auto_out_1_c_ready,
                auto_out_1_d_valid,
  input  [2:0]  auto_out_1_d_bits_opcode,
  input  [1:0]  auto_out_1_d_bits_param,
  input  [2:0]  auto_out_1_d_bits_size,
  input  [3:0]  auto_out_1_d_bits_source,
  input  [2:0]  auto_out_1_d_bits_sink,
  input         auto_out_1_d_bits_denied,
  input  [63:0] auto_out_1_d_bits_data,
  input         auto_out_1_d_bits_corrupt,
                auto_out_0_a_ready,
                auto_out_0_d_valid,
  input  [2:0]  auto_out_0_d_bits_opcode,
  input  [1:0]  auto_out_0_d_bits_param,
  input  [3:0]  auto_out_0_d_bits_size,
                auto_out_0_d_bits_source,
  input         auto_out_0_d_bits_sink,
                auto_out_0_d_bits_denied,
  input  [63:0] auto_out_0_d_bits_data,
  input         auto_out_0_d_bits_corrupt,
  output        auto_in_1_a_ready,
                auto_in_1_b_valid,
  output [1:0]  auto_in_1_b_bits_param,
  output [31:0] auto_in_1_b_bits_address,
  output        auto_in_1_c_ready,
                auto_in_1_d_valid,
  output [2:0]  auto_in_1_d_bits_opcode,
  output [1:0]  auto_in_1_d_bits_param,
  output [3:0]  auto_in_1_d_bits_size,
  output [2:0]  auto_in_1_d_bits_source,
                auto_in_1_d_bits_sink,
  output        auto_in_1_d_bits_denied,
  output [63:0] auto_in_1_d_bits_data,
  output        auto_in_1_d_bits_corrupt,
                auto_in_0_a_ready,
                auto_in_0_d_valid,
  output [2:0]  auto_in_0_d_bits_opcode,
  output [1:0]  auto_in_0_d_bits_param,
  output [3:0]  auto_in_0_d_bits_size,
  output [2:0]  auto_in_0_d_bits_sink,
  output        auto_in_0_d_bits_denied,
  output [63:0] auto_in_0_d_bits_data,
  output        auto_in_0_d_bits_corrupt,
                auto_out_1_a_valid,
  output [2:0]  auto_out_1_a_bits_opcode,
                auto_out_1_a_bits_param,
                auto_out_1_a_bits_size,
  output [3:0]  auto_out_1_a_bits_source,
  output [31:0] auto_out_1_a_bits_address,
  output [7:0]  auto_out_1_a_bits_mask,
  output [63:0] auto_out_1_a_bits_data,
  output        auto_out_1_a_bits_corrupt,
                auto_out_1_b_ready,
                auto_out_1_c_valid,
  output [2:0]  auto_out_1_c_bits_opcode,
                auto_out_1_c_bits_param,
                auto_out_1_c_bits_size,
  output [3:0]  auto_out_1_c_bits_source,
  output [31:0] auto_out_1_c_bits_address,
  output [63:0] auto_out_1_c_bits_data,
  output        auto_out_1_c_bits_corrupt,
                auto_out_1_d_ready,
                auto_out_1_e_valid,
  output [2:0]  auto_out_1_e_bits_sink,
  output        auto_out_0_a_valid,
  output [2:0]  auto_out_0_a_bits_opcode,
                auto_out_0_a_bits_param,
  output [3:0]  auto_out_0_a_bits_size,
                auto_out_0_a_bits_source,
  output [30:0] auto_out_0_a_bits_address,
  output [7:0]  auto_out_0_a_bits_mask,
  output [63:0] auto_out_0_a_bits_data,
  output        auto_out_0_a_bits_corrupt,
                auto_out_0_d_ready
);

  wire        allowed_3_1;
  wire        allowed_3_0;
  wire        allowed_2_1;
  wire        allowed_2_0;
  wire        allowed_1_1;
  wire        allowed_1_0;
  wire        allowed_1;
  wire        allowed_0;
  wire [3:0]  portsAOI_filtered_1_bits_source = {3'h4, auto_in_0_a_bits_source};
  wire [3:0]  portsAOI_filtered_1_1_bits_source = {1'h0, auto_in_1_a_bits_source};
  wire [2:0]  out_15_bits_sink = {2'h0, auto_out_0_d_bits_sink};
  wire [3:0]  out_16_bits_size = {1'h0, auto_out_1_d_bits_size};
  wire [2:0]  _GEN = auto_in_0_a_bits_address[28:26] ^ 3'h5;
  wire        requestAIO_0_0 = {auto_in_0_a_bits_address[31], auto_in_0_a_bits_address[28], auto_in_0_a_bits_address[26], auto_in_0_a_bits_address[17]} == 4'h0 | {auto_in_0_a_bits_address[31], auto_in_0_a_bits_address[28], ~(auto_in_0_a_bits_address[26])} == 3'h0 | {auto_in_0_a_bits_address[31], _GEN[2], _GEN[0], auto_in_0_a_bits_address[17:16]} == 5'h0;
  wire        requestAIO_0_1 = {auto_in_0_a_bits_address[31], auto_in_0_a_bits_address[28], auto_in_0_a_bits_address[26], auto_in_0_a_bits_address[17:16] ^ 2'h2} == 5'h0 | {auto_in_0_a_bits_address[31], ~(auto_in_0_a_bits_address[28]), auto_in_0_a_bits_address[26], auto_in_0_a_bits_address[17:16]} == 5'h0 | {~(auto_in_0_a_bits_address[31]), auto_in_0_a_bits_address[28]} == 2'h0;
  wire [2:0]  _GEN_0 = auto_in_1_a_bits_address[28:26] ^ 3'h5;
  wire        requestAIO_1_0 = {auto_in_1_a_bits_address[31], auto_in_1_a_bits_address[28], auto_in_1_a_bits_address[26], auto_in_1_a_bits_address[17]} == 4'h0 | {auto_in_1_a_bits_address[31], auto_in_1_a_bits_address[28], ~(auto_in_1_a_bits_address[26])} == 3'h0 | {auto_in_1_a_bits_address[31], _GEN_0[2], _GEN_0[0], auto_in_1_a_bits_address[17:16]} == 5'h0;
  wire        requestAIO_1_1 = {auto_in_1_a_bits_address[31], auto_in_1_a_bits_address[28], auto_in_1_a_bits_address[26], auto_in_1_a_bits_address[17:16] ^ 2'h2} == 5'h0 | {auto_in_1_a_bits_address[31], ~(auto_in_1_a_bits_address[28]), auto_in_1_a_bits_address[26], auto_in_1_a_bits_address[17:16]} == 5'h0 | {~(auto_in_1_a_bits_address[31]), auto_in_1_a_bits_address[28]} == 2'h0;
  wire        requestDOI_0_0 = auto_out_0_d_bits_source == 4'h8;
  wire        requestDOI_1_0 = auto_out_1_d_bits_source == 4'h8;
  wire        portsAOI_filtered_0_earlyValid = auto_in_0_a_valid & requestAIO_0_0;
  wire        portsAOI_filtered_1_earlyValid = auto_in_0_a_valid & requestAIO_0_1;
  wire        _portsAOI_in_0_a_ready_WIRE = requestAIO_0_0 & auto_out_0_a_ready & allowed_0 | requestAIO_0_1 & auto_out_1_a_ready & allowed_1_0;
  wire        portsAOI_filtered_1_0_earlyValid = auto_in_1_a_valid & requestAIO_1_0;
  wire        portsAOI_filtered_1_1_earlyValid = auto_in_1_a_valid & requestAIO_1_1;
  wire        _portsAOI_in_1_a_ready_WIRE = requestAIO_1_0 & auto_out_0_a_ready & allowed_1 | requestAIO_1_1 & auto_out_1_a_ready & allowed_1_1;
  wire        out_10_earlyValid = auto_out_0_d_valid & requestDOI_0_0;
  wire        out_15_earlyValid = auto_out_0_d_valid & ~(auto_out_0_d_bits_source[3]);
  wire        out_11_earlyValid = auto_out_1_d_valid & requestDOI_1_0;
  wire        out_16_earlyValid = auto_out_1_d_valid & ~(auto_out_1_d_bits_source[3]);
  reg  [8:0]  beatsLeft;
  wire        idle = beatsLeft == 9'h0;
  wire [1:0]  readys_valid = {portsAOI_filtered_1_0_earlyValid, portsAOI_filtered_0_earlyValid};
  reg  [1:0]  readys_mask;
  wire [1:0]  _readys_filter_T_1 = readys_valid & ~readys_mask;
  wire [1:0]  readys_readys = ~({readys_mask[1], _readys_filter_T_1[1] | readys_mask[0]} & {|_readys_filter_T_1, portsAOI_filtered_1_0_earlyValid | _readys_filter_T_1[0]});
  wire        earlyWinner_0 = readys_readys[0] & portsAOI_filtered_0_earlyValid;
  wire        earlyWinner_1 = readys_readys[1] & portsAOI_filtered_1_0_earlyValid;
  wire        _out_0_a_earlyValid_T = portsAOI_filtered_0_earlyValid | portsAOI_filtered_1_0_earlyValid;
  reg         state_0;
  reg         state_1;
  wire        muxStateEarly_0 = idle ? earlyWinner_0 : state_0;
  wire        muxStateEarly_1 = idle ? earlyWinner_1 : state_1;
  assign allowed_0 = idle ? readys_readys[0] : state_0;
  assign allowed_1 = idle ? readys_readys[1] : state_1;
  wire        x1_out_1_valid = idle ? _out_0_a_earlyValid_T : state_0 & portsAOI_filtered_0_earlyValid | state_1 & portsAOI_filtered_1_0_earlyValid;
  reg  [8:0]  beatsLeft_1;
  wire        idle_1 = beatsLeft_1 == 9'h0;
  wire [1:0]  readys_valid_1 = {portsAOI_filtered_1_1_earlyValid, portsAOI_filtered_1_earlyValid};
  reg  [1:0]  readys_mask_1;
  wire [1:0]  _readys_filter_T_3 = readys_valid_1 & ~readys_mask_1;
  wire [1:0]  readys_readys_1 = ~({readys_mask_1[1], _readys_filter_T_3[1] | readys_mask_1[0]} & {|_readys_filter_T_3, portsAOI_filtered_1_1_earlyValid | _readys_filter_T_3[0]});
  wire        earlyWinner_1_0 = readys_readys_1[0] & portsAOI_filtered_1_earlyValid;
  wire        earlyWinner_1_1 = readys_readys_1[1] & portsAOI_filtered_1_1_earlyValid;
  wire        _out_1_a_earlyValid_T = portsAOI_filtered_1_earlyValid | portsAOI_filtered_1_1_earlyValid;
  reg         state_1_0;
  reg         state_1_1;
  wire        muxStateEarly_1_0 = idle_1 ? earlyWinner_1_0 : state_1_0;
  wire        muxStateEarly_1_1 = idle_1 ? earlyWinner_1_1 : state_1_1;
  assign allowed_1_0 = idle_1 ? readys_readys_1[0] : state_1_0;
  assign allowed_1_1 = idle_1 ? readys_readys_1[1] : state_1_1;
  wire        bundleOut_1_out_1_valid = idle_1 ? _out_1_a_earlyValid_T : state_1_0 & portsAOI_filtered_1_earlyValid | state_1_1 & portsAOI_filtered_1_1_earlyValid;
  reg  [8:0]  beatsLeft_2;
  wire        idle_2 = beatsLeft_2 == 9'h0;
  wire [1:0]  readys_valid_2 = {out_11_earlyValid, out_10_earlyValid};
  reg  [1:0]  readys_mask_2;
  wire [1:0]  _readys_filter_T_5 = readys_valid_2 & ~readys_mask_2;
  wire [1:0]  readys_readys_2 = ~({readys_mask_2[1], _readys_filter_T_5[1] | readys_mask_2[0]} & {|_readys_filter_T_5, out_11_earlyValid | _readys_filter_T_5[0]});
  wire        earlyWinner_2_0 = readys_readys_2[0] & out_10_earlyValid;
  wire        earlyWinner_2_1 = readys_readys_2[1] & out_11_earlyValid;
  wire        _sink_ACancel_earlyValid_T = out_10_earlyValid | out_11_earlyValid;
  reg         state_2_0;
  reg         state_2_1;
  wire        muxStateEarly_2_0 = idle_2 ? earlyWinner_2_0 : state_2_0;
  wire        muxStateEarly_2_1 = idle_2 ? earlyWinner_2_1 : state_2_1;
  assign allowed_2_0 = idle_2 ? readys_readys_2[0] : state_2_0;
  assign allowed_2_1 = idle_2 ? readys_readys_2[1] : state_2_1;
  wire        out_12_valid = idle_2 ? _sink_ACancel_earlyValid_T : state_2_0 & out_10_earlyValid | state_2_1 & out_11_earlyValid;
  wire        out_12_bits_corrupt = muxStateEarly_2_0 & auto_out_0_d_bits_corrupt | muxStateEarly_2_1 & auto_out_1_d_bits_corrupt;
  wire        out_12_bits_denied = muxStateEarly_2_0 & auto_out_0_d_bits_denied | muxStateEarly_2_1 & auto_out_1_d_bits_denied;
  wire [2:0]  out_12_bits_sink = (muxStateEarly_2_0 ? out_15_bits_sink : 3'h0) | (muxStateEarly_2_1 ? auto_out_1_d_bits_sink : 3'h0);
  wire [3:0]  out_12_bits_size = (muxStateEarly_2_0 ? auto_out_0_d_bits_size : 4'h0) | (muxStateEarly_2_1 ? out_16_bits_size : 4'h0);
  wire [1:0]  out_12_bits_param = (muxStateEarly_2_0 ? auto_out_0_d_bits_param : 2'h0) | (muxStateEarly_2_1 ? auto_out_1_d_bits_param : 2'h0);
  wire [2:0]  out_12_bits_opcode = (muxStateEarly_2_0 ? auto_out_0_d_bits_opcode : 3'h0) | (muxStateEarly_2_1 ? auto_out_1_d_bits_opcode : 3'h0);
  reg  [8:0]  beatsLeft_3;
  wire        idle_3 = beatsLeft_3 == 9'h0;
  wire [1:0]  readys_valid_3 = {out_16_earlyValid, out_15_earlyValid};
  reg  [1:0]  readys_mask_3;
  wire [1:0]  _readys_filter_T_7 = readys_valid_3 & ~readys_mask_3;
  wire [1:0]  readys_readys_3 = ~({readys_mask_3[1], _readys_filter_T_7[1] | readys_mask_3[0]} & {|_readys_filter_T_7, out_16_earlyValid | _readys_filter_T_7[0]});
  wire        earlyWinner_3_0 = readys_readys_3[0] & out_15_earlyValid;
  wire        earlyWinner_3_1 = readys_readys_3[1] & out_16_earlyValid;
  wire        _sink_ACancel_earlyValid_T_5 = out_15_earlyValid | out_16_earlyValid;
  reg         state_3_0;
  reg         state_3_1;
  wire        muxStateEarly_3_0 = idle_3 ? earlyWinner_3_0 : state_3_0;
  wire        muxStateEarly_3_1 = idle_3 ? earlyWinner_3_1 : state_3_1;
  assign allowed_3_0 = idle_3 ? readys_readys_3[0] : state_3_0;
  assign allowed_3_1 = idle_3 ? readys_readys_3[1] : state_3_1;
  wire        out_17_valid = idle_3 ? _sink_ACancel_earlyValid_T_5 : state_3_0 & out_15_earlyValid | state_3_1 & out_16_earlyValid;
  wire        out_17_bits_corrupt = muxStateEarly_3_0 & auto_out_0_d_bits_corrupt | muxStateEarly_3_1 & auto_out_1_d_bits_corrupt;
  wire        out_17_bits_denied = muxStateEarly_3_0 & auto_out_0_d_bits_denied | muxStateEarly_3_1 & auto_out_1_d_bits_denied;
  wire [2:0]  out_17_bits_sink = (muxStateEarly_3_0 ? out_15_bits_sink : 3'h0) | (muxStateEarly_3_1 ? auto_out_1_d_bits_sink : 3'h0);
  wire [2:0]  out_1_d_bits_source = (muxStateEarly_3_0 ? auto_out_0_d_bits_source[2:0] : 3'h0) | (muxStateEarly_3_1 ? auto_out_1_d_bits_source[2:0] : 3'h0);
  wire [3:0]  out_17_bits_size = (muxStateEarly_3_0 ? auto_out_0_d_bits_size : 4'h0) | (muxStateEarly_3_1 ? out_16_bits_size : 4'h0);
  wire [1:0]  out_17_bits_param = (muxStateEarly_3_0 ? auto_out_0_d_bits_param : 2'h0) | (muxStateEarly_3_1 ? auto_out_1_d_bits_param : 2'h0);
  wire [2:0]  out_17_bits_opcode = (muxStateEarly_3_0 ? auto_out_0_d_bits_opcode : 3'h0) | (muxStateEarly_3_1 ? auto_out_1_d_bits_opcode : 3'h0);
  wire [1:0]  _readys_mask_T = readys_readys & readys_valid;
  wire [1:0]  _readys_mask_T_5 = readys_readys_1 & readys_valid_1;
  wire [1:0]  _readys_mask_T_10 = readys_readys_2 & readys_valid_2;
  wire [1:0]  _readys_mask_T_15 = readys_readys_3 & readys_valid_3;
  wire [26:0] _beatsAI_decode_T_1 = 27'hFFF << auto_in_0_a_bits_size;
  wire [26:0] _beatsAI_decode_T_5 = 27'hFFF << auto_in_1_a_bits_size;
  wire [26:0] _beatsDO_decode_T_1 = 27'hFFF << auto_out_0_d_bits_size;
  wire [20:0] _beatsDO_decode_T_5 = 21'h3F << auto_out_1_d_bits_size;
  wire        latch = idle & auto_out_0_a_ready;
  wire        winnerQual_0 = readys_readys[0] & portsAOI_filtered_0_earlyValid;
  wire        winnerQual_1 = readys_readys[1] & portsAOI_filtered_1_0_earlyValid;
  wire        latch_1 = idle_1 & auto_out_1_a_ready;
  wire        winnerQual_1_0 = readys_readys_1[0] & portsAOI_filtered_1_earlyValid;
  wire        winnerQual_1_1 = readys_readys_1[1] & portsAOI_filtered_1_1_earlyValid;
  wire        latch_2 = idle_2 & auto_in_0_d_ready;
  wire        winnerQual_2_0 = readys_readys_2[0] & out_10_earlyValid;
  wire        winnerQual_2_1 = readys_readys_2[1] & out_11_earlyValid;
  wire        latch_3 = idle_3 & auto_in_1_d_ready;
  wire        winnerQual_3_0 = readys_readys_3[0] & out_15_earlyValid;
  wire        winnerQual_3_1 = readys_readys_3[1] & out_16_earlyValid;
  always @(posedge clock) begin
    if (reset) begin
      beatsLeft <= 9'h0;
      readys_mask <= 2'h3;
      state_0 <= 1'h0;
      state_1 <= 1'h0;
      beatsLeft_1 <= 9'h0;
      readys_mask_1 <= 2'h3;
      state_1_0 <= 1'h0;
      state_1_1 <= 1'h0;
      beatsLeft_2 <= 9'h0;
      readys_mask_2 <= 2'h3;
      state_2_0 <= 1'h0;
      state_2_1 <= 1'h0;
      beatsLeft_3 <= 9'h0;
      readys_mask_3 <= 2'h3;
      state_3_0 <= 1'h0;
      state_3_1 <= 1'h0;
    end
    else begin
      if (latch)
        beatsLeft <= (winnerQual_0 & ~(auto_in_0_a_bits_opcode[2]) ? ~(_beatsAI_decode_T_1[11:3]) : 9'h0) | (winnerQual_1 & ~(auto_in_1_a_bits_opcode[2]) ? ~(_beatsAI_decode_T_5[11:3]) : 9'h0);
      else
        beatsLeft <= beatsLeft - {8'h0, auto_out_0_a_ready & x1_out_1_valid};
      if (latch & (|readys_valid))
        readys_mask <= _readys_mask_T | {_readys_mask_T[0], 1'h0};
      if (idle) begin
        state_0 <= winnerQual_0;
        state_1 <= winnerQual_1;
      end
      if (latch_1)
        beatsLeft_1 <= (winnerQual_1_0 & ~(auto_in_0_a_bits_opcode[2]) ? ~(_beatsAI_decode_T_1[11:3]) : 9'h0) | (winnerQual_1_1 & ~(auto_in_1_a_bits_opcode[2]) ? ~(_beatsAI_decode_T_5[11:3]) : 9'h0);
      else
        beatsLeft_1 <= beatsLeft_1 - {8'h0, auto_out_1_a_ready & bundleOut_1_out_1_valid};
      if (latch_1 & (|readys_valid_1))
        readys_mask_1 <= _readys_mask_T_5 | {_readys_mask_T_5[0], 1'h0};
      if (idle_1) begin
        state_1_0 <= winnerQual_1_0;
        state_1_1 <= winnerQual_1_1;
      end
      if (latch_2)
        beatsLeft_2 <= (winnerQual_2_0 & auto_out_0_d_bits_opcode[0] ? ~(_beatsDO_decode_T_1[11:3]) : 9'h0) | {6'h0, winnerQual_2_1 & auto_out_1_d_bits_opcode[0] ? ~(_beatsDO_decode_T_5[5:3]) : 3'h0};
      else
        beatsLeft_2 <= beatsLeft_2 - {8'h0, auto_in_0_d_ready & out_12_valid};
      if (latch_2 & (|readys_valid_2))
        readys_mask_2 <= _readys_mask_T_10 | {_readys_mask_T_10[0], 1'h0};
      if (idle_2) begin
        state_2_0 <= winnerQual_2_0;
        state_2_1 <= winnerQual_2_1;
      end
      if (latch_3)
        beatsLeft_3 <= (winnerQual_3_0 & auto_out_0_d_bits_opcode[0] ? ~(_beatsDO_decode_T_1[11:3]) : 9'h0) | {6'h0, winnerQual_3_1 & auto_out_1_d_bits_opcode[0] ? ~(_beatsDO_decode_T_5[5:3]) : 3'h0};
      else
        beatsLeft_3 <= beatsLeft_3 - {8'h0, auto_in_1_d_ready & out_17_valid};
      if (latch_3 & (|readys_valid_3))
        readys_mask_3 <= _readys_mask_T_15 | {_readys_mask_T_15[0], 1'h0};
      if (idle_3) begin
        state_3_0 <= winnerQual_3_0;
        state_3_1 <= winnerQual_3_1;
      end
    end
  end // always @(posedge)
  `ifndef SYNTHESIS
    always @(posedge clock) begin
      if (~reset & ~(~earlyWinner_0 | ~earlyWinner_1)) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed\n    at Arbiter.scala:106 assert((prefixOR zip earlyWinner) map { case (p,w) => !p || !w } reduce {_ && _})\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & ~(~_out_0_a_earlyValid_T | earlyWinner_0 | earlyWinner_1)) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed\n    at Arbiter.scala:108 assert (!earlyValids.reduce(_||_) || earlyWinner.reduce(_||_))\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & ~(~earlyWinner_1_0 | ~earlyWinner_1_1)) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed\n    at Arbiter.scala:106 assert((prefixOR zip earlyWinner) map { case (p,w) => !p || !w } reduce {_ && _})\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & ~(~_out_1_a_earlyValid_T | earlyWinner_1_0 | earlyWinner_1_1)) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed\n    at Arbiter.scala:108 assert (!earlyValids.reduce(_||_) || earlyWinner.reduce(_||_))\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & ~(~earlyWinner_2_0 | ~earlyWinner_2_1)) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed\n    at Arbiter.scala:106 assert((prefixOR zip earlyWinner) map { case (p,w) => !p || !w } reduce {_ && _})\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & ~(~_sink_ACancel_earlyValid_T | earlyWinner_2_0 | earlyWinner_2_1)) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed\n    at Arbiter.scala:108 assert (!earlyValids.reduce(_||_) || earlyWinner.reduce(_||_))\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & ~(~earlyWinner_3_0 | ~earlyWinner_3_1)) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed\n    at Arbiter.scala:106 assert((prefixOR zip earlyWinner) map { case (p,w) => !p || !w } reduce {_ && _})\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & ~(~_sink_ACancel_earlyValid_T_5 | earlyWinner_3_0 | earlyWinner_3_1)) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed\n    at Arbiter.scala:108 assert (!earlyValids.reduce(_||_) || earlyWinner.reduce(_||_))\n");
        if (`STOP_COND_)
          $fatal;
      end
    end // always @(posedge)
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM_0;
    logic [31:0] _RANDOM_1;
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM_0 = `RANDOM;
        _RANDOM_1 = `RANDOM;
        beatsLeft = _RANDOM_0[8:0];
        readys_mask = _RANDOM_0[10:9];
        state_0 = _RANDOM_0[11];
        state_1 = _RANDOM_0[12];
        beatsLeft_1 = _RANDOM_0[21:13];
        readys_mask_1 = _RANDOM_0[23:22];
        state_1_0 = _RANDOM_0[24];
        state_1_1 = _RANDOM_0[25];
        beatsLeft_2 = {_RANDOM_0[31:26], _RANDOM_1[2:0]};
        readys_mask_2 = _RANDOM_1[4:3];
        state_2_0 = _RANDOM_1[5];
        state_2_1 = _RANDOM_1[6];
        beatsLeft_3 = _RANDOM_1[15:7];
        readys_mask_3 = _RANDOM_1[17:16];
        state_3_0 = _RANDOM_1[18];
        state_3_1 = _RANDOM_1[19];
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  TLMonitor monitor (
    .clock                (clock),
    .reset                (reset),
    .io_in_a_ready        (_portsAOI_in_0_a_ready_WIRE),
    .io_in_a_valid        (auto_in_0_a_valid),
    .io_in_a_bits_opcode  (auto_in_0_a_bits_opcode),
    .io_in_a_bits_param   (auto_in_0_a_bits_param),
    .io_in_a_bits_size    (auto_in_0_a_bits_size),
    .io_in_a_bits_source  (auto_in_0_a_bits_source),
    .io_in_a_bits_address (auto_in_0_a_bits_address),
    .io_in_a_bits_mask    (auto_in_0_a_bits_mask),
    .io_in_a_bits_corrupt (auto_in_0_a_bits_corrupt),
    .io_in_d_ready        (auto_in_0_d_ready),
    .io_in_d_valid        (out_12_valid),
    .io_in_d_bits_opcode  (out_12_bits_opcode),
    .io_in_d_bits_param   (out_12_bits_param),
    .io_in_d_bits_size    (out_12_bits_size),
    .io_in_d_bits_sink    (out_12_bits_sink),
    .io_in_d_bits_denied  (out_12_bits_denied),
    .io_in_d_bits_corrupt (out_12_bits_corrupt)
  );
  TLMonitor_1 monitor_1 (
    .clock                (clock),
    .reset                (reset),
    .io_in_a_ready        (_portsAOI_in_1_a_ready_WIRE),
    .io_in_a_valid        (auto_in_1_a_valid),
    .io_in_a_bits_opcode  (auto_in_1_a_bits_opcode),
    .io_in_a_bits_param   (auto_in_1_a_bits_param),
    .io_in_a_bits_size    (auto_in_1_a_bits_size),
    .io_in_a_bits_source  (auto_in_1_a_bits_source),
    .io_in_a_bits_address (auto_in_1_a_bits_address),
    .io_in_a_bits_mask    (auto_in_1_a_bits_mask),
    .io_in_a_bits_corrupt (auto_in_1_a_bits_corrupt),
    .io_in_b_valid        (auto_out_1_b_valid),
    .io_in_b_bits_param   (auto_out_1_b_bits_param),
    .io_in_b_bits_address (auto_out_1_b_bits_address),
    .io_in_c_ready        (auto_out_1_c_ready),
    .io_in_c_valid        (auto_in_1_c_valid),
    .io_in_c_bits_opcode  (auto_in_1_c_bits_opcode),
    .io_in_c_bits_param   (auto_in_1_c_bits_param),
    .io_in_c_bits_size    (auto_in_1_c_bits_size),
    .io_in_c_bits_source  (auto_in_1_c_bits_source),
    .io_in_c_bits_address (auto_in_1_c_bits_address),
    .io_in_c_bits_corrupt (auto_in_1_c_bits_corrupt),
    .io_in_d_ready        (auto_in_1_d_ready),
    .io_in_d_valid        (out_17_valid),
    .io_in_d_bits_opcode  (out_17_bits_opcode),
    .io_in_d_bits_param   (out_17_bits_param),
    .io_in_d_bits_size    (out_17_bits_size),
    .io_in_d_bits_source  (out_1_d_bits_source),
    .io_in_d_bits_sink    (out_17_bits_sink),
    .io_in_d_bits_denied  (out_17_bits_denied),
    .io_in_d_bits_corrupt (out_17_bits_corrupt),
    .io_in_e_valid        (auto_in_1_e_valid),
    .io_in_e_bits_sink    (auto_in_1_e_bits_sink)
  );
  assign auto_in_1_a_ready = _portsAOI_in_1_a_ready_WIRE;
  assign auto_in_1_b_valid = auto_out_1_b_valid;
  assign auto_in_1_b_bits_param = auto_out_1_b_bits_param;
  assign auto_in_1_b_bits_address = auto_out_1_b_bits_address;
  assign auto_in_1_c_ready = auto_out_1_c_ready;
  assign auto_in_1_d_valid = out_17_valid;
  assign auto_in_1_d_bits_opcode = out_17_bits_opcode;
  assign auto_in_1_d_bits_param = out_17_bits_param;
  assign auto_in_1_d_bits_size = out_17_bits_size;
  assign auto_in_1_d_bits_source = out_1_d_bits_source;
  assign auto_in_1_d_bits_sink = out_17_bits_sink;
  assign auto_in_1_d_bits_denied = out_17_bits_denied;
  assign auto_in_1_d_bits_data = (muxStateEarly_3_0 ? auto_out_0_d_bits_data : 64'h0) | (muxStateEarly_3_1 ? auto_out_1_d_bits_data : 64'h0);
  assign auto_in_1_d_bits_corrupt = out_17_bits_corrupt;
  assign auto_in_0_a_ready = _portsAOI_in_0_a_ready_WIRE;
  assign auto_in_0_d_valid = out_12_valid;
  assign auto_in_0_d_bits_opcode = out_12_bits_opcode;
  assign auto_in_0_d_bits_param = out_12_bits_param;
  assign auto_in_0_d_bits_size = out_12_bits_size;
  assign auto_in_0_d_bits_sink = out_12_bits_sink;
  assign auto_in_0_d_bits_denied = out_12_bits_denied;
  assign auto_in_0_d_bits_data = (muxStateEarly_2_0 ? auto_out_0_d_bits_data : 64'h0) | (muxStateEarly_2_1 ? auto_out_1_d_bits_data : 64'h0);
  assign auto_in_0_d_bits_corrupt = out_12_bits_corrupt;
  assign auto_out_1_a_valid = bundleOut_1_out_1_valid;
  assign auto_out_1_a_bits_opcode = (muxStateEarly_1_0 ? auto_in_0_a_bits_opcode : 3'h0) | (muxStateEarly_1_1 ? auto_in_1_a_bits_opcode : 3'h0);
  assign auto_out_1_a_bits_param = (muxStateEarly_1_0 ? auto_in_0_a_bits_param : 3'h0) | (muxStateEarly_1_1 ? auto_in_1_a_bits_param : 3'h0);
  assign auto_out_1_a_bits_size = (muxStateEarly_1_0 ? auto_in_0_a_bits_size[2:0] : 3'h0) | (muxStateEarly_1_1 ? auto_in_1_a_bits_size[2:0] : 3'h0);
  assign auto_out_1_a_bits_source = (muxStateEarly_1_0 ? portsAOI_filtered_1_bits_source : 4'h0) | (muxStateEarly_1_1 ? portsAOI_filtered_1_1_bits_source : 4'h0);
  assign auto_out_1_a_bits_address = (muxStateEarly_1_0 ? auto_in_0_a_bits_address : 32'h0) | (muxStateEarly_1_1 ? auto_in_1_a_bits_address : 32'h0);
  assign auto_out_1_a_bits_mask = (muxStateEarly_1_0 ? auto_in_0_a_bits_mask : 8'h0) | (muxStateEarly_1_1 ? auto_in_1_a_bits_mask : 8'h0);
  assign auto_out_1_a_bits_data = (muxStateEarly_1_0 ? auto_in_0_a_bits_data : 64'h0) | (muxStateEarly_1_1 ? auto_in_1_a_bits_data : 64'h0);
  assign auto_out_1_a_bits_corrupt = muxStateEarly_1_0 & auto_in_0_a_bits_corrupt | muxStateEarly_1_1 & auto_in_1_a_bits_corrupt;
  assign auto_out_1_b_ready = auto_in_1_b_ready;
  assign auto_out_1_c_valid = auto_in_1_c_valid;
  assign auto_out_1_c_bits_opcode = auto_in_1_c_bits_opcode;
  assign auto_out_1_c_bits_param = auto_in_1_c_bits_param;
  assign auto_out_1_c_bits_size = auto_in_1_c_bits_size[2:0];
  assign auto_out_1_c_bits_source = {1'h0, auto_in_1_c_bits_source};
  assign auto_out_1_c_bits_address = auto_in_1_c_bits_address;
  assign auto_out_1_c_bits_data = auto_in_1_c_bits_data;
  assign auto_out_1_c_bits_corrupt = auto_in_1_c_bits_corrupt;
  assign auto_out_1_d_ready = requestDOI_1_0 & auto_in_0_d_ready & allowed_2_1 | ~(auto_out_1_d_bits_source[3]) & auto_in_1_d_ready & allowed_3_1;
  assign auto_out_1_e_valid = auto_in_1_e_valid;
  assign auto_out_1_e_bits_sink = auto_in_1_e_bits_sink;
  assign auto_out_0_a_valid = x1_out_1_valid;
  assign auto_out_0_a_bits_opcode = (muxStateEarly_0 ? auto_in_0_a_bits_opcode : 3'h0) | (muxStateEarly_1 ? auto_in_1_a_bits_opcode : 3'h0);
  assign auto_out_0_a_bits_param = (muxStateEarly_0 ? auto_in_0_a_bits_param : 3'h0) | (muxStateEarly_1 ? auto_in_1_a_bits_param : 3'h0);
  assign auto_out_0_a_bits_size = (muxStateEarly_0 ? auto_in_0_a_bits_size : 4'h0) | (muxStateEarly_1 ? auto_in_1_a_bits_size : 4'h0);
  assign auto_out_0_a_bits_source = (muxStateEarly_0 ? portsAOI_filtered_1_bits_source : 4'h0) | (muxStateEarly_1 ? portsAOI_filtered_1_1_bits_source : 4'h0);
  assign auto_out_0_a_bits_address = (muxStateEarly_0 ? auto_in_0_a_bits_address[30:0] : 31'h0) | (muxStateEarly_1 ? auto_in_1_a_bits_address[30:0] : 31'h0);
  assign auto_out_0_a_bits_mask = (muxStateEarly_0 ? auto_in_0_a_bits_mask : 8'h0) | (muxStateEarly_1 ? auto_in_1_a_bits_mask : 8'h0);
  assign auto_out_0_a_bits_data = (muxStateEarly_0 ? auto_in_0_a_bits_data : 64'h0) | (muxStateEarly_1 ? auto_in_1_a_bits_data : 64'h0);
  assign auto_out_0_a_bits_corrupt = muxStateEarly_0 & auto_in_0_a_bits_corrupt | muxStateEarly_1 & auto_in_1_a_bits_corrupt;
  assign auto_out_0_d_ready = requestDOI_0_0 & auto_in_0_d_ready & allowed_2_0 | ~(auto_out_0_d_bits_source[3]) & auto_in_1_d_ready & allowed_3_0;
endmodule

