// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module RocketTile(
  input         clock,
                reset,
                auto_slave_in_a_valid,
  input  [2:0]  auto_slave_in_a_bits_opcode,
                auto_slave_in_a_bits_param,
                auto_slave_in_a_bits_size,
                auto_slave_in_a_bits_source,
  input  [31:0] auto_slave_in_a_bits_address,
  input  [3:0]  auto_slave_in_a_bits_mask,
  input  [31:0] auto_slave_in_a_bits_data,
  input         auto_slave_in_d_ready,
                auto_int_local_in_2_0,
                auto_int_local_in_1_0,
                auto_int_local_in_1_1,
                auto_int_local_in_0_0,
                auto_tl_other_masters_out_a_ready,
                auto_tl_other_masters_out_d_valid,
  input  [2:0]  auto_tl_other_masters_out_d_bits_opcode,
  input  [1:0]  auto_tl_other_masters_out_d_bits_param,
  input  [3:0]  auto_tl_other_masters_out_d_bits_size,
  input         auto_tl_other_masters_out_d_bits_source,
                auto_tl_other_masters_out_d_bits_sink,
                auto_tl_other_masters_out_d_bits_denied,
  input  [31:0] auto_tl_other_masters_out_d_bits_data,
  input         auto_tl_other_masters_out_d_bits_corrupt,
  output        auto_slave_in_a_ready,
                auto_slave_in_d_valid,
  output [2:0]  auto_slave_in_d_bits_opcode,
                auto_slave_in_d_bits_size,
                auto_slave_in_d_bits_source,
  output [31:0] auto_slave_in_d_bits_data,
  output        auto_tl_other_masters_out_a_valid,
  output [2:0]  auto_tl_other_masters_out_a_bits_opcode,
                auto_tl_other_masters_out_a_bits_param,
  output [3:0]  auto_tl_other_masters_out_a_bits_size,
  output        auto_tl_other_masters_out_a_bits_source,
  output [31:0] auto_tl_other_masters_out_a_bits_address,
  output [3:0]  auto_tl_other_masters_out_a_bits_mask,
  output [31:0] auto_tl_other_masters_out_a_bits_data,
  output        auto_tl_other_masters_out_d_ready
);

  wire        _core_io_imem_might_request;	// RocketTile.scala:128:20
  wire        _core_io_imem_req_valid;	// RocketTile.scala:128:20
  wire [31:0] _core_io_imem_req_bits_pc;	// RocketTile.scala:128:20
  wire        _core_io_imem_req_bits_speculative;	// RocketTile.scala:128:20
  wire        _core_io_imem_sfence_valid;	// RocketTile.scala:128:20
  wire        _core_io_imem_resp_ready;	// RocketTile.scala:128:20
  wire        _core_io_imem_btb_update_valid;	// RocketTile.scala:128:20
  wire        _core_io_imem_bht_update_valid;	// RocketTile.scala:128:20
  wire        _core_io_imem_flush_icache;	// RocketTile.scala:128:20
  wire        _core_io_dmem_req_valid;	// RocketTile.scala:128:20
  wire [31:0] _core_io_dmem_req_bits_addr;	// RocketTile.scala:128:20
  wire [6:0]  _core_io_dmem_req_bits_tag;	// RocketTile.scala:128:20
  wire [4:0]  _core_io_dmem_req_bits_cmd;	// RocketTile.scala:128:20
  wire [1:0]  _core_io_dmem_req_bits_size;	// RocketTile.scala:128:20
  wire        _core_io_dmem_req_bits_signed;	// RocketTile.scala:128:20
  wire [1:0]  _core_io_dmem_req_bits_dprv;	// RocketTile.scala:128:20
  wire        _core_io_dmem_s1_kill;	// RocketTile.scala:128:20
  wire [31:0] _core_io_dmem_s1_data_data;	// RocketTile.scala:128:20
  wire        _core_io_ptw_status_debug;	// RocketTile.scala:128:20
  wire        _core_io_ptw_pmp_0_cfg_l;	// RocketTile.scala:128:20
  wire [1:0]  _core_io_ptw_pmp_0_cfg_a;	// RocketTile.scala:128:20
  wire        _core_io_ptw_pmp_0_cfg_x;	// RocketTile.scala:128:20
  wire        _core_io_ptw_pmp_0_cfg_w;	// RocketTile.scala:128:20
  wire        _core_io_ptw_pmp_0_cfg_r;	// RocketTile.scala:128:20
  wire [29:0] _core_io_ptw_pmp_0_addr;	// RocketTile.scala:128:20
  wire [31:0] _core_io_ptw_pmp_0_mask;	// RocketTile.scala:128:20
  wire        _core_io_ptw_pmp_1_cfg_l;	// RocketTile.scala:128:20
  wire [1:0]  _core_io_ptw_pmp_1_cfg_a;	// RocketTile.scala:128:20
  wire        _core_io_ptw_pmp_1_cfg_x;	// RocketTile.scala:128:20
  wire        _core_io_ptw_pmp_1_cfg_w;	// RocketTile.scala:128:20
  wire        _core_io_ptw_pmp_1_cfg_r;	// RocketTile.scala:128:20
  wire [29:0] _core_io_ptw_pmp_1_addr;	// RocketTile.scala:128:20
  wire [31:0] _core_io_ptw_pmp_1_mask;	// RocketTile.scala:128:20
  wire        _core_io_ptw_pmp_2_cfg_l;	// RocketTile.scala:128:20
  wire [1:0]  _core_io_ptw_pmp_2_cfg_a;	// RocketTile.scala:128:20
  wire        _core_io_ptw_pmp_2_cfg_x;	// RocketTile.scala:128:20
  wire        _core_io_ptw_pmp_2_cfg_w;	// RocketTile.scala:128:20
  wire        _core_io_ptw_pmp_2_cfg_r;	// RocketTile.scala:128:20
  wire [29:0] _core_io_ptw_pmp_2_addr;	// RocketTile.scala:128:20
  wire [31:0] _core_io_ptw_pmp_2_mask;	// RocketTile.scala:128:20
  wire        _core_io_ptw_pmp_3_cfg_l;	// RocketTile.scala:128:20
  wire [1:0]  _core_io_ptw_pmp_3_cfg_a;	// RocketTile.scala:128:20
  wire        _core_io_ptw_pmp_3_cfg_x;	// RocketTile.scala:128:20
  wire        _core_io_ptw_pmp_3_cfg_w;	// RocketTile.scala:128:20
  wire        _core_io_ptw_pmp_3_cfg_r;	// RocketTile.scala:128:20
  wire [29:0] _core_io_ptw_pmp_3_addr;	// RocketTile.scala:128:20
  wire [31:0] _core_io_ptw_pmp_3_mask;	// RocketTile.scala:128:20
  wire        _core_io_ptw_pmp_4_cfg_l;	// RocketTile.scala:128:20
  wire [1:0]  _core_io_ptw_pmp_4_cfg_a;	// RocketTile.scala:128:20
  wire        _core_io_ptw_pmp_4_cfg_x;	// RocketTile.scala:128:20
  wire        _core_io_ptw_pmp_4_cfg_w;	// RocketTile.scala:128:20
  wire        _core_io_ptw_pmp_4_cfg_r;	// RocketTile.scala:128:20
  wire [29:0] _core_io_ptw_pmp_4_addr;	// RocketTile.scala:128:20
  wire [31:0] _core_io_ptw_pmp_4_mask;	// RocketTile.scala:128:20
  wire        _core_io_ptw_pmp_5_cfg_l;	// RocketTile.scala:128:20
  wire [1:0]  _core_io_ptw_pmp_5_cfg_a;	// RocketTile.scala:128:20
  wire        _core_io_ptw_pmp_5_cfg_x;	// RocketTile.scala:128:20
  wire        _core_io_ptw_pmp_5_cfg_w;	// RocketTile.scala:128:20
  wire        _core_io_ptw_pmp_5_cfg_r;	// RocketTile.scala:128:20
  wire [29:0] _core_io_ptw_pmp_5_addr;	// RocketTile.scala:128:20
  wire [31:0] _core_io_ptw_pmp_5_mask;	// RocketTile.scala:128:20
  wire        _core_io_ptw_pmp_6_cfg_l;	// RocketTile.scala:128:20
  wire [1:0]  _core_io_ptw_pmp_6_cfg_a;	// RocketTile.scala:128:20
  wire        _core_io_ptw_pmp_6_cfg_x;	// RocketTile.scala:128:20
  wire        _core_io_ptw_pmp_6_cfg_w;	// RocketTile.scala:128:20
  wire        _core_io_ptw_pmp_6_cfg_r;	// RocketTile.scala:128:20
  wire [29:0] _core_io_ptw_pmp_6_addr;	// RocketTile.scala:128:20
  wire [31:0] _core_io_ptw_pmp_6_mask;	// RocketTile.scala:128:20
  wire        _core_io_ptw_pmp_7_cfg_l;	// RocketTile.scala:128:20
  wire [1:0]  _core_io_ptw_pmp_7_cfg_a;	// RocketTile.scala:128:20
  wire        _core_io_ptw_pmp_7_cfg_x;	// RocketTile.scala:128:20
  wire        _core_io_ptw_pmp_7_cfg_w;	// RocketTile.scala:128:20
  wire        _core_io_ptw_pmp_7_cfg_r;	// RocketTile.scala:128:20
  wire [29:0] _core_io_ptw_pmp_7_addr;	// RocketTile.scala:128:20
  wire [31:0] _core_io_ptw_pmp_7_mask;	// RocketTile.scala:128:20
  wire [31:0] _core_io_ptw_customCSRs_csrs_0_value;	// RocketTile.scala:128:20
  wire        _ptw_io_requestor_0_status_debug;	// PTW.scala:793:19
  wire        _ptw_io_requestor_0_pmp_0_cfg_l;	// PTW.scala:793:19
  wire [1:0]  _ptw_io_requestor_0_pmp_0_cfg_a;	// PTW.scala:793:19
  wire        _ptw_io_requestor_0_pmp_0_cfg_w;	// PTW.scala:793:19
  wire        _ptw_io_requestor_0_pmp_0_cfg_r;	// PTW.scala:793:19
  wire [29:0] _ptw_io_requestor_0_pmp_0_addr;	// PTW.scala:793:19
  wire [31:0] _ptw_io_requestor_0_pmp_0_mask;	// PTW.scala:793:19
  wire        _ptw_io_requestor_0_pmp_1_cfg_l;	// PTW.scala:793:19
  wire [1:0]  _ptw_io_requestor_0_pmp_1_cfg_a;	// PTW.scala:793:19
  wire        _ptw_io_requestor_0_pmp_1_cfg_w;	// PTW.scala:793:19
  wire        _ptw_io_requestor_0_pmp_1_cfg_r;	// PTW.scala:793:19
  wire [29:0] _ptw_io_requestor_0_pmp_1_addr;	// PTW.scala:793:19
  wire [31:0] _ptw_io_requestor_0_pmp_1_mask;	// PTW.scala:793:19
  wire        _ptw_io_requestor_0_pmp_2_cfg_l;	// PTW.scala:793:19
  wire [1:0]  _ptw_io_requestor_0_pmp_2_cfg_a;	// PTW.scala:793:19
  wire        _ptw_io_requestor_0_pmp_2_cfg_w;	// PTW.scala:793:19
  wire        _ptw_io_requestor_0_pmp_2_cfg_r;	// PTW.scala:793:19
  wire [29:0] _ptw_io_requestor_0_pmp_2_addr;	// PTW.scala:793:19
  wire [31:0] _ptw_io_requestor_0_pmp_2_mask;	// PTW.scala:793:19
  wire        _ptw_io_requestor_0_pmp_3_cfg_l;	// PTW.scala:793:19
  wire [1:0]  _ptw_io_requestor_0_pmp_3_cfg_a;	// PTW.scala:793:19
  wire        _ptw_io_requestor_0_pmp_3_cfg_w;	// PTW.scala:793:19
  wire        _ptw_io_requestor_0_pmp_3_cfg_r;	// PTW.scala:793:19
  wire [29:0] _ptw_io_requestor_0_pmp_3_addr;	// PTW.scala:793:19
  wire [31:0] _ptw_io_requestor_0_pmp_3_mask;	// PTW.scala:793:19
  wire        _ptw_io_requestor_0_pmp_4_cfg_l;	// PTW.scala:793:19
  wire [1:0]  _ptw_io_requestor_0_pmp_4_cfg_a;	// PTW.scala:793:19
  wire        _ptw_io_requestor_0_pmp_4_cfg_w;	// PTW.scala:793:19
  wire        _ptw_io_requestor_0_pmp_4_cfg_r;	// PTW.scala:793:19
  wire [29:0] _ptw_io_requestor_0_pmp_4_addr;	// PTW.scala:793:19
  wire [31:0] _ptw_io_requestor_0_pmp_4_mask;	// PTW.scala:793:19
  wire        _ptw_io_requestor_0_pmp_5_cfg_l;	// PTW.scala:793:19
  wire [1:0]  _ptw_io_requestor_0_pmp_5_cfg_a;	// PTW.scala:793:19
  wire        _ptw_io_requestor_0_pmp_5_cfg_w;	// PTW.scala:793:19
  wire        _ptw_io_requestor_0_pmp_5_cfg_r;	// PTW.scala:793:19
  wire [29:0] _ptw_io_requestor_0_pmp_5_addr;	// PTW.scala:793:19
  wire [31:0] _ptw_io_requestor_0_pmp_5_mask;	// PTW.scala:793:19
  wire        _ptw_io_requestor_0_pmp_6_cfg_l;	// PTW.scala:793:19
  wire [1:0]  _ptw_io_requestor_0_pmp_6_cfg_a;	// PTW.scala:793:19
  wire        _ptw_io_requestor_0_pmp_6_cfg_w;	// PTW.scala:793:19
  wire        _ptw_io_requestor_0_pmp_6_cfg_r;	// PTW.scala:793:19
  wire [29:0] _ptw_io_requestor_0_pmp_6_addr;	// PTW.scala:793:19
  wire [31:0] _ptw_io_requestor_0_pmp_6_mask;	// PTW.scala:793:19
  wire        _ptw_io_requestor_0_pmp_7_cfg_l;	// PTW.scala:793:19
  wire [1:0]  _ptw_io_requestor_0_pmp_7_cfg_a;	// PTW.scala:793:19
  wire        _ptw_io_requestor_0_pmp_7_cfg_w;	// PTW.scala:793:19
  wire        _ptw_io_requestor_0_pmp_7_cfg_r;	// PTW.scala:793:19
  wire [29:0] _ptw_io_requestor_0_pmp_7_addr;	// PTW.scala:793:19
  wire [31:0] _ptw_io_requestor_0_pmp_7_mask;	// PTW.scala:793:19
  wire        _ptw_io_requestor_1_status_debug;	// PTW.scala:793:19
  wire        _ptw_io_requestor_1_pmp_0_cfg_l;	// PTW.scala:793:19
  wire [1:0]  _ptw_io_requestor_1_pmp_0_cfg_a;	// PTW.scala:793:19
  wire        _ptw_io_requestor_1_pmp_0_cfg_x;	// PTW.scala:793:19
  wire [29:0] _ptw_io_requestor_1_pmp_0_addr;	// PTW.scala:793:19
  wire [31:0] _ptw_io_requestor_1_pmp_0_mask;	// PTW.scala:793:19
  wire        _ptw_io_requestor_1_pmp_1_cfg_l;	// PTW.scala:793:19
  wire [1:0]  _ptw_io_requestor_1_pmp_1_cfg_a;	// PTW.scala:793:19
  wire        _ptw_io_requestor_1_pmp_1_cfg_x;	// PTW.scala:793:19
  wire [29:0] _ptw_io_requestor_1_pmp_1_addr;	// PTW.scala:793:19
  wire [31:0] _ptw_io_requestor_1_pmp_1_mask;	// PTW.scala:793:19
  wire        _ptw_io_requestor_1_pmp_2_cfg_l;	// PTW.scala:793:19
  wire [1:0]  _ptw_io_requestor_1_pmp_2_cfg_a;	// PTW.scala:793:19
  wire        _ptw_io_requestor_1_pmp_2_cfg_x;	// PTW.scala:793:19
  wire [29:0] _ptw_io_requestor_1_pmp_2_addr;	// PTW.scala:793:19
  wire [31:0] _ptw_io_requestor_1_pmp_2_mask;	// PTW.scala:793:19
  wire        _ptw_io_requestor_1_pmp_3_cfg_l;	// PTW.scala:793:19
  wire [1:0]  _ptw_io_requestor_1_pmp_3_cfg_a;	// PTW.scala:793:19
  wire        _ptw_io_requestor_1_pmp_3_cfg_x;	// PTW.scala:793:19
  wire [29:0] _ptw_io_requestor_1_pmp_3_addr;	// PTW.scala:793:19
  wire [31:0] _ptw_io_requestor_1_pmp_3_mask;	// PTW.scala:793:19
  wire        _ptw_io_requestor_1_pmp_4_cfg_l;	// PTW.scala:793:19
  wire [1:0]  _ptw_io_requestor_1_pmp_4_cfg_a;	// PTW.scala:793:19
  wire        _ptw_io_requestor_1_pmp_4_cfg_x;	// PTW.scala:793:19
  wire [29:0] _ptw_io_requestor_1_pmp_4_addr;	// PTW.scala:793:19
  wire [31:0] _ptw_io_requestor_1_pmp_4_mask;	// PTW.scala:793:19
  wire        _ptw_io_requestor_1_pmp_5_cfg_l;	// PTW.scala:793:19
  wire [1:0]  _ptw_io_requestor_1_pmp_5_cfg_a;	// PTW.scala:793:19
  wire        _ptw_io_requestor_1_pmp_5_cfg_x;	// PTW.scala:793:19
  wire [29:0] _ptw_io_requestor_1_pmp_5_addr;	// PTW.scala:793:19
  wire [31:0] _ptw_io_requestor_1_pmp_5_mask;	// PTW.scala:793:19
  wire        _ptw_io_requestor_1_pmp_6_cfg_l;	// PTW.scala:793:19
  wire [1:0]  _ptw_io_requestor_1_pmp_6_cfg_a;	// PTW.scala:793:19
  wire        _ptw_io_requestor_1_pmp_6_cfg_x;	// PTW.scala:793:19
  wire [29:0] _ptw_io_requestor_1_pmp_6_addr;	// PTW.scala:793:19
  wire [31:0] _ptw_io_requestor_1_pmp_6_mask;	// PTW.scala:793:19
  wire        _ptw_io_requestor_1_pmp_7_cfg_l;	// PTW.scala:793:19
  wire [1:0]  _ptw_io_requestor_1_pmp_7_cfg_a;	// PTW.scala:793:19
  wire        _ptw_io_requestor_1_pmp_7_cfg_x;	// PTW.scala:793:19
  wire [29:0] _ptw_io_requestor_1_pmp_7_addr;	// PTW.scala:793:19
  wire [31:0] _ptw_io_requestor_1_pmp_7_mask;	// PTW.scala:793:19
  wire [31:0] _ptw_io_requestor_1_customCSRs_csrs_0_value;	// PTW.scala:793:19
  wire        _dcacheArb_io_requestor_0_req_ready;	// HellaCache.scala:278:25
  wire        _dcacheArb_io_requestor_0_s2_nack;	// HellaCache.scala:278:25
  wire        _dcacheArb_io_requestor_0_resp_valid;	// HellaCache.scala:278:25
  wire [6:0]  _dcacheArb_io_requestor_0_resp_bits_tag;	// HellaCache.scala:278:25
  wire [31:0] _dcacheArb_io_requestor_0_resp_bits_data;	// HellaCache.scala:278:25
  wire        _dcacheArb_io_requestor_0_resp_bits_replay;	// HellaCache.scala:278:25
  wire        _dcacheArb_io_requestor_0_resp_bits_has_data;	// HellaCache.scala:278:25
  wire [31:0] _dcacheArb_io_requestor_0_resp_bits_data_word_bypass;	// HellaCache.scala:278:25
  wire        _dcacheArb_io_requestor_0_replay_next;	// HellaCache.scala:278:25
  wire        _dcacheArb_io_requestor_0_s2_xcpt_ma_ld;	// HellaCache.scala:278:25
  wire        _dcacheArb_io_requestor_0_s2_xcpt_ma_st;	// HellaCache.scala:278:25
  wire        _dcacheArb_io_requestor_0_s2_xcpt_pf_ld;	// HellaCache.scala:278:25
  wire        _dcacheArb_io_requestor_0_s2_xcpt_pf_st;	// HellaCache.scala:278:25
  wire        _dcacheArb_io_requestor_0_s2_xcpt_gf_ld;	// HellaCache.scala:278:25
  wire        _dcacheArb_io_requestor_0_s2_xcpt_gf_st;	// HellaCache.scala:278:25
  wire        _dcacheArb_io_requestor_0_s2_xcpt_ae_ld;	// HellaCache.scala:278:25
  wire        _dcacheArb_io_requestor_0_s2_xcpt_ae_st;	// HellaCache.scala:278:25
  wire        _dcacheArb_io_requestor_0_ordered;	// HellaCache.scala:278:25
  wire        _dcacheArb_io_requestor_0_perf_grant;	// HellaCache.scala:278:25
  wire        _dcacheArb_io_requestor_1_req_ready;	// HellaCache.scala:278:25
  wire        _dcacheArb_io_requestor_1_s2_nack;	// HellaCache.scala:278:25
  wire        _dcacheArb_io_requestor_1_resp_valid;	// HellaCache.scala:278:25
  wire [31:0] _dcacheArb_io_requestor_1_resp_bits_data_raw;	// HellaCache.scala:278:25
  wire        _dcacheArb_io_mem_req_valid;	// HellaCache.scala:278:25
  wire [31:0] _dcacheArb_io_mem_req_bits_addr;	// HellaCache.scala:278:25
  wire [6:0]  _dcacheArb_io_mem_req_bits_tag;	// HellaCache.scala:278:25
  wire [4:0]  _dcacheArb_io_mem_req_bits_cmd;	// HellaCache.scala:278:25
  wire [1:0]  _dcacheArb_io_mem_req_bits_size;	// HellaCache.scala:278:25
  wire        _dcacheArb_io_mem_req_bits_signed;	// HellaCache.scala:278:25
  wire [1:0]  _dcacheArb_io_mem_req_bits_dprv;	// HellaCache.scala:278:25
  wire        _dcacheArb_io_mem_req_bits_no_xcpt;	// HellaCache.scala:278:25
  wire        _dcacheArb_io_mem_s1_kill;	// HellaCache.scala:278:25
  wire [31:0] _dcacheArb_io_mem_s1_data_data;	// HellaCache.scala:278:25
  wire [3:0]  _dcacheArb_io_mem_s1_data_mask;	// HellaCache.scala:278:25
  wire        _fragmenter_1_auto_in_a_ready;	// Fragmenter.scala:334:34
  wire        _fragmenter_1_auto_in_d_valid;	// Fragmenter.scala:334:34
  wire [2:0]  _fragmenter_1_auto_in_d_bits_opcode;	// Fragmenter.scala:334:34
  wire [2:0]  _fragmenter_1_auto_in_d_bits_size;	// Fragmenter.scala:334:34
  wire [2:0]  _fragmenter_1_auto_in_d_bits_source;	// Fragmenter.scala:334:34
  wire [31:0] _fragmenter_1_auto_in_d_bits_data;	// Fragmenter.scala:334:34
  wire        _fragmenter_1_auto_out_a_valid;	// Fragmenter.scala:334:34
  wire [2:0]  _fragmenter_1_auto_out_a_bits_opcode;	// Fragmenter.scala:334:34
  wire [2:0]  _fragmenter_1_auto_out_a_bits_param;	// Fragmenter.scala:334:34
  wire [1:0]  _fragmenter_1_auto_out_a_bits_size;	// Fragmenter.scala:334:34
  wire [8:0]  _fragmenter_1_auto_out_a_bits_source;	// Fragmenter.scala:334:34
  wire [31:0] _fragmenter_1_auto_out_a_bits_address;	// Fragmenter.scala:334:34
  wire [3:0]  _fragmenter_1_auto_out_a_bits_mask;	// Fragmenter.scala:334:34
  wire [31:0] _fragmenter_1_auto_out_a_bits_data;	// Fragmenter.scala:334:34
  wire        _fragmenter_1_auto_out_d_ready;	// Fragmenter.scala:334:34
  wire        _dtim_adapter_auto_in_a_ready;	// RocketTile.scala:59:15
  wire        _dtim_adapter_auto_in_d_valid;	// RocketTile.scala:59:15
  wire [2:0]  _dtim_adapter_auto_in_d_bits_opcode;	// RocketTile.scala:59:15
  wire [1:0]  _dtim_adapter_auto_in_d_bits_size;	// RocketTile.scala:59:15
  wire [8:0]  _dtim_adapter_auto_in_d_bits_source;	// RocketTile.scala:59:15
  wire [31:0] _dtim_adapter_auto_in_d_bits_data;	// RocketTile.scala:59:15
  wire        _dtim_adapter_io_dmem_req_valid;	// RocketTile.scala:59:15
  wire [31:0] _dtim_adapter_io_dmem_req_bits_addr;	// RocketTile.scala:59:15
  wire [4:0]  _dtim_adapter_io_dmem_req_bits_cmd;	// RocketTile.scala:59:15
  wire [1:0]  _dtim_adapter_io_dmem_req_bits_size;	// RocketTile.scala:59:15
  wire        _dtim_adapter_io_dmem_s1_kill;	// RocketTile.scala:59:15
  wire [31:0] _dtim_adapter_io_dmem_s1_data_data;	// RocketTile.scala:59:15
  wire [3:0]  _dtim_adapter_io_dmem_s1_data_mask;	// RocketTile.scala:59:15
  wire        _frontend_auto_icache_master_out_a_valid;	// Frontend.scala:385:28
  wire [31:0] _frontend_auto_icache_master_out_a_bits_address;	// Frontend.scala:385:28
  wire        _frontend_io_cpu_resp_valid;	// Frontend.scala:385:28
  wire        _frontend_io_cpu_resp_bits_btb_taken;	// Frontend.scala:385:28
  wire        _frontend_io_cpu_resp_bits_btb_bridx;	// Frontend.scala:385:28
  wire [31:0] _frontend_io_cpu_resp_bits_pc;	// Frontend.scala:385:28
  wire [31:0] _frontend_io_cpu_resp_bits_data;	// Frontend.scala:385:28
  wire        _frontend_io_cpu_resp_bits_xcpt_pf_inst;	// Frontend.scala:385:28
  wire        _frontend_io_cpu_resp_bits_xcpt_gf_inst;	// Frontend.scala:385:28
  wire        _frontend_io_cpu_resp_bits_xcpt_ae_inst;	// Frontend.scala:385:28
  wire        _frontend_io_cpu_resp_bits_replay;	// Frontend.scala:385:28
  wire        _frontend_io_cpu_gpa_valid;	// Frontend.scala:385:28
  wire        _dcache_auto_out_a_valid;	// HellaCache.scala:267:43
  wire [2:0]  _dcache_auto_out_a_bits_opcode;	// HellaCache.scala:267:43
  wire [2:0]  _dcache_auto_out_a_bits_param;	// HellaCache.scala:267:43
  wire [3:0]  _dcache_auto_out_a_bits_size;	// HellaCache.scala:267:43
  wire [31:0] _dcache_auto_out_a_bits_address;	// HellaCache.scala:267:43
  wire [3:0]  _dcache_auto_out_a_bits_mask;	// HellaCache.scala:267:43
  wire [31:0] _dcache_auto_out_a_bits_data;	// HellaCache.scala:267:43
  wire        _dcache_auto_out_d_ready;	// HellaCache.scala:267:43
  wire        _dcache_io_cpu_req_ready;	// HellaCache.scala:267:43
  wire        _dcache_io_cpu_s2_nack;	// HellaCache.scala:267:43
  wire        _dcache_io_cpu_resp_valid;	// HellaCache.scala:267:43
  wire [6:0]  _dcache_io_cpu_resp_bits_tag;	// HellaCache.scala:267:43
  wire [31:0] _dcache_io_cpu_resp_bits_data;	// HellaCache.scala:267:43
  wire        _dcache_io_cpu_resp_bits_replay;	// HellaCache.scala:267:43
  wire        _dcache_io_cpu_resp_bits_has_data;	// HellaCache.scala:267:43
  wire [31:0] _dcache_io_cpu_resp_bits_data_word_bypass;	// HellaCache.scala:267:43
  wire [31:0] _dcache_io_cpu_resp_bits_data_raw;	// HellaCache.scala:267:43
  wire        _dcache_io_cpu_replay_next;	// HellaCache.scala:267:43
  wire        _dcache_io_cpu_s2_xcpt_ma_ld;	// HellaCache.scala:267:43
  wire        _dcache_io_cpu_s2_xcpt_ma_st;	// HellaCache.scala:267:43
  wire        _dcache_io_cpu_s2_xcpt_pf_ld;	// HellaCache.scala:267:43
  wire        _dcache_io_cpu_s2_xcpt_pf_st;	// HellaCache.scala:267:43
  wire        _dcache_io_cpu_s2_xcpt_gf_ld;	// HellaCache.scala:267:43
  wire        _dcache_io_cpu_s2_xcpt_gf_st;	// HellaCache.scala:267:43
  wire        _dcache_io_cpu_s2_xcpt_ae_ld;	// HellaCache.scala:267:43
  wire        _dcache_io_cpu_s2_xcpt_ae_st;	// HellaCache.scala:267:43
  wire        _dcache_io_cpu_ordered;	// HellaCache.scala:267:43
  wire        _dcache_io_cpu_perf_grant;	// HellaCache.scala:267:43
  wire        _intXbar_auto_int_out_0;	// BaseTile.scala:224:37
  wire        _intXbar_auto_int_out_1;	// BaseTile.scala:224:37
  wire        _intXbar_auto_int_out_2;	// BaseTile.scala:224:37
  wire        _intXbar_auto_int_out_3;	// BaseTile.scala:224:37
  wire        _tlSlaveXbar_auto_out_a_valid;	// BaseTile.scala:223:41
  wire [2:0]  _tlSlaveXbar_auto_out_a_bits_opcode;	// BaseTile.scala:223:41
  wire [2:0]  _tlSlaveXbar_auto_out_a_bits_param;	// BaseTile.scala:223:41
  wire [2:0]  _tlSlaveXbar_auto_out_a_bits_size;	// BaseTile.scala:223:41
  wire [2:0]  _tlSlaveXbar_auto_out_a_bits_source;	// BaseTile.scala:223:41
  wire [31:0] _tlSlaveXbar_auto_out_a_bits_address;	// BaseTile.scala:223:41
  wire [3:0]  _tlSlaveXbar_auto_out_a_bits_mask;	// BaseTile.scala:223:41
  wire [31:0] _tlSlaveXbar_auto_out_a_bits_data;	// BaseTile.scala:223:41
  wire        _tlSlaveXbar_auto_out_d_ready;	// BaseTile.scala:223:41
  wire        _tlMasterXbar_auto_in_1_a_ready;	// BaseTile.scala:222:42
  wire        _tlMasterXbar_auto_in_1_d_valid;	// BaseTile.scala:222:42
  wire [2:0]  _tlMasterXbar_auto_in_1_d_bits_opcode;	// BaseTile.scala:222:42
  wire [3:0]  _tlMasterXbar_auto_in_1_d_bits_size;	// BaseTile.scala:222:42
  wire [31:0] _tlMasterXbar_auto_in_1_d_bits_data;	// BaseTile.scala:222:42
  wire        _tlMasterXbar_auto_in_1_d_bits_corrupt;	// BaseTile.scala:222:42
  wire        _tlMasterXbar_auto_in_0_a_ready;	// BaseTile.scala:222:42
  wire        _tlMasterXbar_auto_in_0_d_valid;	// BaseTile.scala:222:42
  wire [2:0]  _tlMasterXbar_auto_in_0_d_bits_opcode;	// BaseTile.scala:222:42
  wire [3:0]  _tlMasterXbar_auto_in_0_d_bits_size;	// BaseTile.scala:222:42
  wire        _tlMasterXbar_auto_in_0_d_bits_denied;	// BaseTile.scala:222:42
  wire [31:0] _tlMasterXbar_auto_in_0_d_bits_data;	// BaseTile.scala:222:42
  TLXbar_6 tlMasterXbar (	// BaseTile.scala:222:42
    .clock                    (clock),
    .reset                    (reset),
    .auto_in_1_a_valid        (_frontend_auto_icache_master_out_a_valid),	// Frontend.scala:385:28
    .auto_in_1_a_bits_address (_frontend_auto_icache_master_out_a_bits_address),	// Frontend.scala:385:28
    .auto_in_0_a_valid        (_dcache_auto_out_a_valid),	// HellaCache.scala:267:43
    .auto_in_0_a_bits_opcode  (_dcache_auto_out_a_bits_opcode),	// HellaCache.scala:267:43
    .auto_in_0_a_bits_param   (_dcache_auto_out_a_bits_param),	// HellaCache.scala:267:43
    .auto_in_0_a_bits_size    (_dcache_auto_out_a_bits_size),	// HellaCache.scala:267:43
    .auto_in_0_a_bits_address (_dcache_auto_out_a_bits_address),	// HellaCache.scala:267:43
    .auto_in_0_a_bits_mask    (_dcache_auto_out_a_bits_mask),	// HellaCache.scala:267:43
    .auto_in_0_a_bits_data    (_dcache_auto_out_a_bits_data),	// HellaCache.scala:267:43
    .auto_in_0_d_ready        (_dcache_auto_out_d_ready),	// HellaCache.scala:267:43
    .auto_out_a_ready         (auto_tl_other_masters_out_a_ready),
    .auto_out_d_valid         (auto_tl_other_masters_out_d_valid),
    .auto_out_d_bits_opcode   (auto_tl_other_masters_out_d_bits_opcode),
    .auto_out_d_bits_param    (auto_tl_other_masters_out_d_bits_param),
    .auto_out_d_bits_size     (auto_tl_other_masters_out_d_bits_size),
    .auto_out_d_bits_source   (auto_tl_other_masters_out_d_bits_source),
    .auto_out_d_bits_sink     (auto_tl_other_masters_out_d_bits_sink),
    .auto_out_d_bits_denied   (auto_tl_other_masters_out_d_bits_denied),
    .auto_out_d_bits_data     (auto_tl_other_masters_out_d_bits_data),
    .auto_out_d_bits_corrupt  (auto_tl_other_masters_out_d_bits_corrupt),
    .auto_in_1_a_ready        (_tlMasterXbar_auto_in_1_a_ready),
    .auto_in_1_d_valid        (_tlMasterXbar_auto_in_1_d_valid),
    .auto_in_1_d_bits_opcode  (_tlMasterXbar_auto_in_1_d_bits_opcode),
    .auto_in_1_d_bits_size    (_tlMasterXbar_auto_in_1_d_bits_size),
    .auto_in_1_d_bits_data    (_tlMasterXbar_auto_in_1_d_bits_data),
    .auto_in_1_d_bits_corrupt (_tlMasterXbar_auto_in_1_d_bits_corrupt),
    .auto_in_0_a_ready        (_tlMasterXbar_auto_in_0_a_ready),
    .auto_in_0_d_valid        (_tlMasterXbar_auto_in_0_d_valid),
    .auto_in_0_d_bits_opcode  (_tlMasterXbar_auto_in_0_d_bits_opcode),
    .auto_in_0_d_bits_size    (_tlMasterXbar_auto_in_0_d_bits_size),
    .auto_in_0_d_bits_denied  (_tlMasterXbar_auto_in_0_d_bits_denied),
    .auto_in_0_d_bits_data    (_tlMasterXbar_auto_in_0_d_bits_data),
    .auto_out_a_valid         (auto_tl_other_masters_out_a_valid),
    .auto_out_a_bits_opcode   (auto_tl_other_masters_out_a_bits_opcode),
    .auto_out_a_bits_param    (auto_tl_other_masters_out_a_bits_param),
    .auto_out_a_bits_size     (auto_tl_other_masters_out_a_bits_size),
    .auto_out_a_bits_source   (auto_tl_other_masters_out_a_bits_source),
    .auto_out_a_bits_address  (auto_tl_other_masters_out_a_bits_address),
    .auto_out_a_bits_mask     (auto_tl_other_masters_out_a_bits_mask),
    .auto_out_a_bits_data     (auto_tl_other_masters_out_a_bits_data),
    .auto_out_d_ready         (auto_tl_other_masters_out_d_ready)
  );
  TLXbar_7 tlSlaveXbar (	// BaseTile.scala:223:41
    .auto_in_a_valid         (auto_slave_in_a_valid),
    .auto_in_a_bits_opcode   (auto_slave_in_a_bits_opcode),
    .auto_in_a_bits_param    (auto_slave_in_a_bits_param),
    .auto_in_a_bits_size     (auto_slave_in_a_bits_size),
    .auto_in_a_bits_source   (auto_slave_in_a_bits_source),
    .auto_in_a_bits_address  (auto_slave_in_a_bits_address),
    .auto_in_a_bits_mask     (auto_slave_in_a_bits_mask),
    .auto_in_a_bits_data     (auto_slave_in_a_bits_data),
    .auto_in_d_ready         (auto_slave_in_d_ready),
    .auto_out_a_ready        (_fragmenter_1_auto_in_a_ready),	// Fragmenter.scala:334:34
    .auto_out_d_valid        (_fragmenter_1_auto_in_d_valid),	// Fragmenter.scala:334:34
    .auto_out_d_bits_opcode  (_fragmenter_1_auto_in_d_bits_opcode),	// Fragmenter.scala:334:34
    .auto_out_d_bits_size    (_fragmenter_1_auto_in_d_bits_size),	// Fragmenter.scala:334:34
    .auto_out_d_bits_source  (_fragmenter_1_auto_in_d_bits_source),	// Fragmenter.scala:334:34
    .auto_out_d_bits_data    (_fragmenter_1_auto_in_d_bits_data),	// Fragmenter.scala:334:34
    .auto_in_a_ready         (auto_slave_in_a_ready),
    .auto_in_d_valid         (auto_slave_in_d_valid),
    .auto_in_d_bits_opcode   (auto_slave_in_d_bits_opcode),
    .auto_in_d_bits_size     (auto_slave_in_d_bits_size),
    .auto_in_d_bits_source   (auto_slave_in_d_bits_source),
    .auto_in_d_bits_data     (auto_slave_in_d_bits_data),
    .auto_out_a_valid        (_tlSlaveXbar_auto_out_a_valid),
    .auto_out_a_bits_opcode  (_tlSlaveXbar_auto_out_a_bits_opcode),
    .auto_out_a_bits_param   (_tlSlaveXbar_auto_out_a_bits_param),
    .auto_out_a_bits_size    (_tlSlaveXbar_auto_out_a_bits_size),
    .auto_out_a_bits_source  (_tlSlaveXbar_auto_out_a_bits_source),
    .auto_out_a_bits_address (_tlSlaveXbar_auto_out_a_bits_address),
    .auto_out_a_bits_mask    (_tlSlaveXbar_auto_out_a_bits_mask),
    .auto_out_a_bits_data    (_tlSlaveXbar_auto_out_a_bits_data),
    .auto_out_d_ready        (_tlSlaveXbar_auto_out_d_ready)
  );
  IntXbar_1 intXbar (	// BaseTile.scala:224:37
    .auto_int_in_2_0 (auto_int_local_in_2_0),
    .auto_int_in_1_0 (auto_int_local_in_1_0),
    .auto_int_in_1_1 (auto_int_local_in_1_1),
    .auto_int_in_0_0 (auto_int_local_in_0_0),
    .auto_int_out_0  (_intXbar_auto_int_out_0),
    .auto_int_out_1  (_intXbar_auto_int_out_1),
    .auto_int_out_2  (_intXbar_auto_int_out_2),
    .auto_int_out_3  (_intXbar_auto_int_out_3)
  );
  DCache dcache (	// HellaCache.scala:267:43
    .clock                             (clock),
    .reset                             (reset),
    .auto_out_a_ready                  (_tlMasterXbar_auto_in_0_a_ready),	// BaseTile.scala:222:42
    .auto_out_d_valid                  (_tlMasterXbar_auto_in_0_d_valid),	// BaseTile.scala:222:42
    .auto_out_d_bits_opcode            (_tlMasterXbar_auto_in_0_d_bits_opcode),	// BaseTile.scala:222:42
    .auto_out_d_bits_size              (_tlMasterXbar_auto_in_0_d_bits_size),	// BaseTile.scala:222:42
    .auto_out_d_bits_denied            (_tlMasterXbar_auto_in_0_d_bits_denied),	// BaseTile.scala:222:42
    .auto_out_d_bits_data              (_tlMasterXbar_auto_in_0_d_bits_data),	// BaseTile.scala:222:42
    .io_cpu_req_valid                  (_dcacheArb_io_mem_req_valid),	// HellaCache.scala:278:25
    .io_cpu_req_bits_addr              (_dcacheArb_io_mem_req_bits_addr),	// HellaCache.scala:278:25
    .io_cpu_req_bits_tag               (_dcacheArb_io_mem_req_bits_tag),	// HellaCache.scala:278:25
    .io_cpu_req_bits_cmd               (_dcacheArb_io_mem_req_bits_cmd),	// HellaCache.scala:278:25
    .io_cpu_req_bits_size              (_dcacheArb_io_mem_req_bits_size),	// HellaCache.scala:278:25
    .io_cpu_req_bits_signed            (_dcacheArb_io_mem_req_bits_signed),	// HellaCache.scala:278:25
    .io_cpu_req_bits_dprv              (_dcacheArb_io_mem_req_bits_dprv),	// HellaCache.scala:278:25
    .io_cpu_req_bits_no_xcpt           (_dcacheArb_io_mem_req_bits_no_xcpt),	// HellaCache.scala:278:25
    .io_cpu_s1_kill                    (_dcacheArb_io_mem_s1_kill),	// HellaCache.scala:278:25
    .io_cpu_s1_data_data               (_dcacheArb_io_mem_s1_data_data),	// HellaCache.scala:278:25
    .io_cpu_s1_data_mask               (_dcacheArb_io_mem_s1_data_mask),	// HellaCache.scala:278:25
    .io_ptw_status_debug               (_ptw_io_requestor_0_status_debug),	// PTW.scala:793:19
    .io_ptw_pmp_0_cfg_l                (_ptw_io_requestor_0_pmp_0_cfg_l),	// PTW.scala:793:19
    .io_ptw_pmp_0_cfg_a                (_ptw_io_requestor_0_pmp_0_cfg_a),	// PTW.scala:793:19
    .io_ptw_pmp_0_cfg_w                (_ptw_io_requestor_0_pmp_0_cfg_w),	// PTW.scala:793:19
    .io_ptw_pmp_0_cfg_r                (_ptw_io_requestor_0_pmp_0_cfg_r),	// PTW.scala:793:19
    .io_ptw_pmp_0_addr                 (_ptw_io_requestor_0_pmp_0_addr),	// PTW.scala:793:19
    .io_ptw_pmp_0_mask                 (_ptw_io_requestor_0_pmp_0_mask),	// PTW.scala:793:19
    .io_ptw_pmp_1_cfg_l                (_ptw_io_requestor_0_pmp_1_cfg_l),	// PTW.scala:793:19
    .io_ptw_pmp_1_cfg_a                (_ptw_io_requestor_0_pmp_1_cfg_a),	// PTW.scala:793:19
    .io_ptw_pmp_1_cfg_w                (_ptw_io_requestor_0_pmp_1_cfg_w),	// PTW.scala:793:19
    .io_ptw_pmp_1_cfg_r                (_ptw_io_requestor_0_pmp_1_cfg_r),	// PTW.scala:793:19
    .io_ptw_pmp_1_addr                 (_ptw_io_requestor_0_pmp_1_addr),	// PTW.scala:793:19
    .io_ptw_pmp_1_mask                 (_ptw_io_requestor_0_pmp_1_mask),	// PTW.scala:793:19
    .io_ptw_pmp_2_cfg_l                (_ptw_io_requestor_0_pmp_2_cfg_l),	// PTW.scala:793:19
    .io_ptw_pmp_2_cfg_a                (_ptw_io_requestor_0_pmp_2_cfg_a),	// PTW.scala:793:19
    .io_ptw_pmp_2_cfg_w                (_ptw_io_requestor_0_pmp_2_cfg_w),	// PTW.scala:793:19
    .io_ptw_pmp_2_cfg_r                (_ptw_io_requestor_0_pmp_2_cfg_r),	// PTW.scala:793:19
    .io_ptw_pmp_2_addr                 (_ptw_io_requestor_0_pmp_2_addr),	// PTW.scala:793:19
    .io_ptw_pmp_2_mask                 (_ptw_io_requestor_0_pmp_2_mask),	// PTW.scala:793:19
    .io_ptw_pmp_3_cfg_l                (_ptw_io_requestor_0_pmp_3_cfg_l),	// PTW.scala:793:19
    .io_ptw_pmp_3_cfg_a                (_ptw_io_requestor_0_pmp_3_cfg_a),	// PTW.scala:793:19
    .io_ptw_pmp_3_cfg_w                (_ptw_io_requestor_0_pmp_3_cfg_w),	// PTW.scala:793:19
    .io_ptw_pmp_3_cfg_r                (_ptw_io_requestor_0_pmp_3_cfg_r),	// PTW.scala:793:19
    .io_ptw_pmp_3_addr                 (_ptw_io_requestor_0_pmp_3_addr),	// PTW.scala:793:19
    .io_ptw_pmp_3_mask                 (_ptw_io_requestor_0_pmp_3_mask),	// PTW.scala:793:19
    .io_ptw_pmp_4_cfg_l                (_ptw_io_requestor_0_pmp_4_cfg_l),	// PTW.scala:793:19
    .io_ptw_pmp_4_cfg_a                (_ptw_io_requestor_0_pmp_4_cfg_a),	// PTW.scala:793:19
    .io_ptw_pmp_4_cfg_w                (_ptw_io_requestor_0_pmp_4_cfg_w),	// PTW.scala:793:19
    .io_ptw_pmp_4_cfg_r                (_ptw_io_requestor_0_pmp_4_cfg_r),	// PTW.scala:793:19
    .io_ptw_pmp_4_addr                 (_ptw_io_requestor_0_pmp_4_addr),	// PTW.scala:793:19
    .io_ptw_pmp_4_mask                 (_ptw_io_requestor_0_pmp_4_mask),	// PTW.scala:793:19
    .io_ptw_pmp_5_cfg_l                (_ptw_io_requestor_0_pmp_5_cfg_l),	// PTW.scala:793:19
    .io_ptw_pmp_5_cfg_a                (_ptw_io_requestor_0_pmp_5_cfg_a),	// PTW.scala:793:19
    .io_ptw_pmp_5_cfg_w                (_ptw_io_requestor_0_pmp_5_cfg_w),	// PTW.scala:793:19
    .io_ptw_pmp_5_cfg_r                (_ptw_io_requestor_0_pmp_5_cfg_r),	// PTW.scala:793:19
    .io_ptw_pmp_5_addr                 (_ptw_io_requestor_0_pmp_5_addr),	// PTW.scala:793:19
    .io_ptw_pmp_5_mask                 (_ptw_io_requestor_0_pmp_5_mask),	// PTW.scala:793:19
    .io_ptw_pmp_6_cfg_l                (_ptw_io_requestor_0_pmp_6_cfg_l),	// PTW.scala:793:19
    .io_ptw_pmp_6_cfg_a                (_ptw_io_requestor_0_pmp_6_cfg_a),	// PTW.scala:793:19
    .io_ptw_pmp_6_cfg_w                (_ptw_io_requestor_0_pmp_6_cfg_w),	// PTW.scala:793:19
    .io_ptw_pmp_6_cfg_r                (_ptw_io_requestor_0_pmp_6_cfg_r),	// PTW.scala:793:19
    .io_ptw_pmp_6_addr                 (_ptw_io_requestor_0_pmp_6_addr),	// PTW.scala:793:19
    .io_ptw_pmp_6_mask                 (_ptw_io_requestor_0_pmp_6_mask),	// PTW.scala:793:19
    .io_ptw_pmp_7_cfg_l                (_ptw_io_requestor_0_pmp_7_cfg_l),	// PTW.scala:793:19
    .io_ptw_pmp_7_cfg_a                (_ptw_io_requestor_0_pmp_7_cfg_a),	// PTW.scala:793:19
    .io_ptw_pmp_7_cfg_w                (_ptw_io_requestor_0_pmp_7_cfg_w),	// PTW.scala:793:19
    .io_ptw_pmp_7_cfg_r                (_ptw_io_requestor_0_pmp_7_cfg_r),	// PTW.scala:793:19
    .io_ptw_pmp_7_addr                 (_ptw_io_requestor_0_pmp_7_addr),	// PTW.scala:793:19
    .io_ptw_pmp_7_mask                 (_ptw_io_requestor_0_pmp_7_mask),	// PTW.scala:793:19
    .auto_out_a_valid                  (_dcache_auto_out_a_valid),
    .auto_out_a_bits_opcode            (_dcache_auto_out_a_bits_opcode),
    .auto_out_a_bits_param             (_dcache_auto_out_a_bits_param),
    .auto_out_a_bits_size              (_dcache_auto_out_a_bits_size),
    .auto_out_a_bits_address           (_dcache_auto_out_a_bits_address),
    .auto_out_a_bits_mask              (_dcache_auto_out_a_bits_mask),
    .auto_out_a_bits_data              (_dcache_auto_out_a_bits_data),
    .auto_out_d_ready                  (_dcache_auto_out_d_ready),
    .io_cpu_req_ready                  (_dcache_io_cpu_req_ready),
    .io_cpu_s2_nack                    (_dcache_io_cpu_s2_nack),
    .io_cpu_resp_valid                 (_dcache_io_cpu_resp_valid),
    .io_cpu_resp_bits_tag              (_dcache_io_cpu_resp_bits_tag),
    .io_cpu_resp_bits_data             (_dcache_io_cpu_resp_bits_data),
    .io_cpu_resp_bits_replay           (_dcache_io_cpu_resp_bits_replay),
    .io_cpu_resp_bits_has_data         (_dcache_io_cpu_resp_bits_has_data),
    .io_cpu_resp_bits_data_word_bypass (_dcache_io_cpu_resp_bits_data_word_bypass),
    .io_cpu_resp_bits_data_raw         (_dcache_io_cpu_resp_bits_data_raw),
    .io_cpu_replay_next                (_dcache_io_cpu_replay_next),
    .io_cpu_s2_xcpt_ma_ld              (_dcache_io_cpu_s2_xcpt_ma_ld),
    .io_cpu_s2_xcpt_ma_st              (_dcache_io_cpu_s2_xcpt_ma_st),
    .io_cpu_s2_xcpt_pf_ld              (_dcache_io_cpu_s2_xcpt_pf_ld),
    .io_cpu_s2_xcpt_pf_st              (_dcache_io_cpu_s2_xcpt_pf_st),
    .io_cpu_s2_xcpt_gf_ld              (_dcache_io_cpu_s2_xcpt_gf_ld),
    .io_cpu_s2_xcpt_gf_st              (_dcache_io_cpu_s2_xcpt_gf_st),
    .io_cpu_s2_xcpt_ae_ld              (_dcache_io_cpu_s2_xcpt_ae_ld),
    .io_cpu_s2_xcpt_ae_st              (_dcache_io_cpu_s2_xcpt_ae_st),
    .io_cpu_ordered                    (_dcache_io_cpu_ordered),
    .io_cpu_perf_grant                 (_dcache_io_cpu_perf_grant)
  );
  Frontend frontend (	// Frontend.scala:385:28
    .clock                                 (clock),
    .reset                                 (reset),
    .auto_icache_master_out_a_ready        (_tlMasterXbar_auto_in_1_a_ready),	// BaseTile.scala:222:42
    .auto_icache_master_out_d_valid        (_tlMasterXbar_auto_in_1_d_valid),	// BaseTile.scala:222:42
    .auto_icache_master_out_d_bits_opcode  (_tlMasterXbar_auto_in_1_d_bits_opcode),	// BaseTile.scala:222:42
    .auto_icache_master_out_d_bits_size    (_tlMasterXbar_auto_in_1_d_bits_size),	// BaseTile.scala:222:42
    .auto_icache_master_out_d_bits_data    (_tlMasterXbar_auto_in_1_d_bits_data),	// BaseTile.scala:222:42
    .auto_icache_master_out_d_bits_corrupt (_tlMasterXbar_auto_in_1_d_bits_corrupt),	// BaseTile.scala:222:42
    .io_cpu_might_request                  (_core_io_imem_might_request),	// RocketTile.scala:128:20
    .io_cpu_req_valid                      (_core_io_imem_req_valid),	// RocketTile.scala:128:20
    .io_cpu_req_bits_pc                    (_core_io_imem_req_bits_pc),	// RocketTile.scala:128:20
    .io_cpu_req_bits_speculative           (_core_io_imem_req_bits_speculative),	// RocketTile.scala:128:20
    .io_cpu_sfence_valid                   (_core_io_imem_sfence_valid),	// RocketTile.scala:128:20
    .io_cpu_resp_ready                     (_core_io_imem_resp_ready),	// RocketTile.scala:128:20
    .io_cpu_btb_update_valid               (_core_io_imem_btb_update_valid),	// RocketTile.scala:128:20
    .io_cpu_bht_update_valid               (_core_io_imem_bht_update_valid),	// RocketTile.scala:128:20
    .io_cpu_flush_icache                   (_core_io_imem_flush_icache),	// RocketTile.scala:128:20
    .io_ptw_status_debug                   (_ptw_io_requestor_1_status_debug),	// PTW.scala:793:19
    .io_ptw_pmp_0_cfg_l                    (_ptw_io_requestor_1_pmp_0_cfg_l),	// PTW.scala:793:19
    .io_ptw_pmp_0_cfg_a                    (_ptw_io_requestor_1_pmp_0_cfg_a),	// PTW.scala:793:19
    .io_ptw_pmp_0_cfg_x                    (_ptw_io_requestor_1_pmp_0_cfg_x),	// PTW.scala:793:19
    .io_ptw_pmp_0_addr                     (_ptw_io_requestor_1_pmp_0_addr),	// PTW.scala:793:19
    .io_ptw_pmp_0_mask                     (_ptw_io_requestor_1_pmp_0_mask),	// PTW.scala:793:19
    .io_ptw_pmp_1_cfg_l                    (_ptw_io_requestor_1_pmp_1_cfg_l),	// PTW.scala:793:19
    .io_ptw_pmp_1_cfg_a                    (_ptw_io_requestor_1_pmp_1_cfg_a),	// PTW.scala:793:19
    .io_ptw_pmp_1_cfg_x                    (_ptw_io_requestor_1_pmp_1_cfg_x),	// PTW.scala:793:19
    .io_ptw_pmp_1_addr                     (_ptw_io_requestor_1_pmp_1_addr),	// PTW.scala:793:19
    .io_ptw_pmp_1_mask                     (_ptw_io_requestor_1_pmp_1_mask),	// PTW.scala:793:19
    .io_ptw_pmp_2_cfg_l                    (_ptw_io_requestor_1_pmp_2_cfg_l),	// PTW.scala:793:19
    .io_ptw_pmp_2_cfg_a                    (_ptw_io_requestor_1_pmp_2_cfg_a),	// PTW.scala:793:19
    .io_ptw_pmp_2_cfg_x                    (_ptw_io_requestor_1_pmp_2_cfg_x),	// PTW.scala:793:19
    .io_ptw_pmp_2_addr                     (_ptw_io_requestor_1_pmp_2_addr),	// PTW.scala:793:19
    .io_ptw_pmp_2_mask                     (_ptw_io_requestor_1_pmp_2_mask),	// PTW.scala:793:19
    .io_ptw_pmp_3_cfg_l                    (_ptw_io_requestor_1_pmp_3_cfg_l),	// PTW.scala:793:19
    .io_ptw_pmp_3_cfg_a                    (_ptw_io_requestor_1_pmp_3_cfg_a),	// PTW.scala:793:19
    .io_ptw_pmp_3_cfg_x                    (_ptw_io_requestor_1_pmp_3_cfg_x),	// PTW.scala:793:19
    .io_ptw_pmp_3_addr                     (_ptw_io_requestor_1_pmp_3_addr),	// PTW.scala:793:19
    .io_ptw_pmp_3_mask                     (_ptw_io_requestor_1_pmp_3_mask),	// PTW.scala:793:19
    .io_ptw_pmp_4_cfg_l                    (_ptw_io_requestor_1_pmp_4_cfg_l),	// PTW.scala:793:19
    .io_ptw_pmp_4_cfg_a                    (_ptw_io_requestor_1_pmp_4_cfg_a),	// PTW.scala:793:19
    .io_ptw_pmp_4_cfg_x                    (_ptw_io_requestor_1_pmp_4_cfg_x),	// PTW.scala:793:19
    .io_ptw_pmp_4_addr                     (_ptw_io_requestor_1_pmp_4_addr),	// PTW.scala:793:19
    .io_ptw_pmp_4_mask                     (_ptw_io_requestor_1_pmp_4_mask),	// PTW.scala:793:19
    .io_ptw_pmp_5_cfg_l                    (_ptw_io_requestor_1_pmp_5_cfg_l),	// PTW.scala:793:19
    .io_ptw_pmp_5_cfg_a                    (_ptw_io_requestor_1_pmp_5_cfg_a),	// PTW.scala:793:19
    .io_ptw_pmp_5_cfg_x                    (_ptw_io_requestor_1_pmp_5_cfg_x),	// PTW.scala:793:19
    .io_ptw_pmp_5_addr                     (_ptw_io_requestor_1_pmp_5_addr),	// PTW.scala:793:19
    .io_ptw_pmp_5_mask                     (_ptw_io_requestor_1_pmp_5_mask),	// PTW.scala:793:19
    .io_ptw_pmp_6_cfg_l                    (_ptw_io_requestor_1_pmp_6_cfg_l),	// PTW.scala:793:19
    .io_ptw_pmp_6_cfg_a                    (_ptw_io_requestor_1_pmp_6_cfg_a),	// PTW.scala:793:19
    .io_ptw_pmp_6_cfg_x                    (_ptw_io_requestor_1_pmp_6_cfg_x),	// PTW.scala:793:19
    .io_ptw_pmp_6_addr                     (_ptw_io_requestor_1_pmp_6_addr),	// PTW.scala:793:19
    .io_ptw_pmp_6_mask                     (_ptw_io_requestor_1_pmp_6_mask),	// PTW.scala:793:19
    .io_ptw_pmp_7_cfg_l                    (_ptw_io_requestor_1_pmp_7_cfg_l),	// PTW.scala:793:19
    .io_ptw_pmp_7_cfg_a                    (_ptw_io_requestor_1_pmp_7_cfg_a),	// PTW.scala:793:19
    .io_ptw_pmp_7_cfg_x                    (_ptw_io_requestor_1_pmp_7_cfg_x),	// PTW.scala:793:19
    .io_ptw_pmp_7_addr                     (_ptw_io_requestor_1_pmp_7_addr),	// PTW.scala:793:19
    .io_ptw_pmp_7_mask                     (_ptw_io_requestor_1_pmp_7_mask),	// PTW.scala:793:19
    .io_ptw_customCSRs_csrs_0_value        (_ptw_io_requestor_1_customCSRs_csrs_0_value),	// PTW.scala:793:19
    .auto_icache_master_out_a_valid        (_frontend_auto_icache_master_out_a_valid),
    .auto_icache_master_out_a_bits_address
      (_frontend_auto_icache_master_out_a_bits_address),
    .io_cpu_resp_valid                     (_frontend_io_cpu_resp_valid),
    .io_cpu_resp_bits_btb_taken            (_frontend_io_cpu_resp_bits_btb_taken),
    .io_cpu_resp_bits_btb_bridx            (_frontend_io_cpu_resp_bits_btb_bridx),
    .io_cpu_resp_bits_pc                   (_frontend_io_cpu_resp_bits_pc),
    .io_cpu_resp_bits_data                 (_frontend_io_cpu_resp_bits_data),
    .io_cpu_resp_bits_xcpt_pf_inst         (_frontend_io_cpu_resp_bits_xcpt_pf_inst),
    .io_cpu_resp_bits_xcpt_gf_inst         (_frontend_io_cpu_resp_bits_xcpt_gf_inst),
    .io_cpu_resp_bits_xcpt_ae_inst         (_frontend_io_cpu_resp_bits_xcpt_ae_inst),
    .io_cpu_resp_bits_replay               (_frontend_io_cpu_resp_bits_replay),
    .io_cpu_gpa_valid                      (_frontend_io_cpu_gpa_valid)
  );
  ScratchpadSlavePort dtim_adapter (	// RocketTile.scala:59:15
    .clock                      (clock),
    .reset                      (reset),
    .auto_in_a_valid            (_fragmenter_1_auto_out_a_valid),	// Fragmenter.scala:334:34
    .auto_in_a_bits_opcode      (_fragmenter_1_auto_out_a_bits_opcode),	// Fragmenter.scala:334:34
    .auto_in_a_bits_param       (_fragmenter_1_auto_out_a_bits_param),	// Fragmenter.scala:334:34
    .auto_in_a_bits_size        (_fragmenter_1_auto_out_a_bits_size),	// Fragmenter.scala:334:34
    .auto_in_a_bits_source      (_fragmenter_1_auto_out_a_bits_source),	// Fragmenter.scala:334:34
    .auto_in_a_bits_address     (_fragmenter_1_auto_out_a_bits_address),	// Fragmenter.scala:334:34
    .auto_in_a_bits_mask        (_fragmenter_1_auto_out_a_bits_mask),	// Fragmenter.scala:334:34
    .auto_in_a_bits_data        (_fragmenter_1_auto_out_a_bits_data),	// Fragmenter.scala:334:34
    .auto_in_d_ready            (_fragmenter_1_auto_out_d_ready),	// Fragmenter.scala:334:34
    .io_dmem_req_ready          (_dcacheArb_io_requestor_1_req_ready),	// HellaCache.scala:278:25
    .io_dmem_s2_nack            (_dcacheArb_io_requestor_1_s2_nack),	// HellaCache.scala:278:25
    .io_dmem_resp_valid         (_dcacheArb_io_requestor_1_resp_valid),	// HellaCache.scala:278:25
    .io_dmem_resp_bits_data_raw (_dcacheArb_io_requestor_1_resp_bits_data_raw),	// HellaCache.scala:278:25
    .auto_in_a_ready            (_dtim_adapter_auto_in_a_ready),
    .auto_in_d_valid            (_dtim_adapter_auto_in_d_valid),
    .auto_in_d_bits_opcode      (_dtim_adapter_auto_in_d_bits_opcode),
    .auto_in_d_bits_size        (_dtim_adapter_auto_in_d_bits_size),
    .auto_in_d_bits_source      (_dtim_adapter_auto_in_d_bits_source),
    .auto_in_d_bits_data        (_dtim_adapter_auto_in_d_bits_data),
    .io_dmem_req_valid          (_dtim_adapter_io_dmem_req_valid),
    .io_dmem_req_bits_addr      (_dtim_adapter_io_dmem_req_bits_addr),
    .io_dmem_req_bits_cmd       (_dtim_adapter_io_dmem_req_bits_cmd),
    .io_dmem_req_bits_size      (_dtim_adapter_io_dmem_req_bits_size),
    .io_dmem_s1_kill            (_dtim_adapter_io_dmem_s1_kill),
    .io_dmem_s1_data_data       (_dtim_adapter_io_dmem_s1_data_data),
    .io_dmem_s1_data_mask       (_dtim_adapter_io_dmem_s1_data_mask)
  );
  TLFragmenter_9 fragmenter_1 (	// Fragmenter.scala:334:34
    .clock                   (clock),
    .reset                   (reset),
    .auto_in_a_valid         (_tlSlaveXbar_auto_out_a_valid),	// BaseTile.scala:223:41
    .auto_in_a_bits_opcode   (_tlSlaveXbar_auto_out_a_bits_opcode),	// BaseTile.scala:223:41
    .auto_in_a_bits_param    (_tlSlaveXbar_auto_out_a_bits_param),	// BaseTile.scala:223:41
    .auto_in_a_bits_size     (_tlSlaveXbar_auto_out_a_bits_size),	// BaseTile.scala:223:41
    .auto_in_a_bits_source   (_tlSlaveXbar_auto_out_a_bits_source),	// BaseTile.scala:223:41
    .auto_in_a_bits_address  (_tlSlaveXbar_auto_out_a_bits_address),	// BaseTile.scala:223:41
    .auto_in_a_bits_mask     (_tlSlaveXbar_auto_out_a_bits_mask),	// BaseTile.scala:223:41
    .auto_in_a_bits_data     (_tlSlaveXbar_auto_out_a_bits_data),	// BaseTile.scala:223:41
    .auto_in_d_ready         (_tlSlaveXbar_auto_out_d_ready),	// BaseTile.scala:223:41
    .auto_out_a_ready        (_dtim_adapter_auto_in_a_ready),	// RocketTile.scala:59:15
    .auto_out_d_valid        (_dtim_adapter_auto_in_d_valid),	// RocketTile.scala:59:15
    .auto_out_d_bits_opcode  (_dtim_adapter_auto_in_d_bits_opcode),	// RocketTile.scala:59:15
    .auto_out_d_bits_size    (_dtim_adapter_auto_in_d_bits_size),	// RocketTile.scala:59:15
    .auto_out_d_bits_source  (_dtim_adapter_auto_in_d_bits_source),	// RocketTile.scala:59:15
    .auto_out_d_bits_data    (_dtim_adapter_auto_in_d_bits_data),	// RocketTile.scala:59:15
    .auto_in_a_ready         (_fragmenter_1_auto_in_a_ready),
    .auto_in_d_valid         (_fragmenter_1_auto_in_d_valid),
    .auto_in_d_bits_opcode   (_fragmenter_1_auto_in_d_bits_opcode),
    .auto_in_d_bits_size     (_fragmenter_1_auto_in_d_bits_size),
    .auto_in_d_bits_source   (_fragmenter_1_auto_in_d_bits_source),
    .auto_in_d_bits_data     (_fragmenter_1_auto_in_d_bits_data),
    .auto_out_a_valid        (_fragmenter_1_auto_out_a_valid),
    .auto_out_a_bits_opcode  (_fragmenter_1_auto_out_a_bits_opcode),
    .auto_out_a_bits_param   (_fragmenter_1_auto_out_a_bits_param),
    .auto_out_a_bits_size    (_fragmenter_1_auto_out_a_bits_size),
    .auto_out_a_bits_source  (_fragmenter_1_auto_out_a_bits_source),
    .auto_out_a_bits_address (_fragmenter_1_auto_out_a_bits_address),
    .auto_out_a_bits_mask    (_fragmenter_1_auto_out_a_bits_mask),
    .auto_out_a_bits_data    (_fragmenter_1_auto_out_a_bits_data),
    .auto_out_d_ready        (_fragmenter_1_auto_out_d_ready)
  );
  HellaCacheArbiter dcacheArb (	// HellaCache.scala:278:25
    .clock                                     (clock),
    .io_requestor_0_req_valid                  (_core_io_dmem_req_valid),	// RocketTile.scala:128:20
    .io_requestor_0_req_bits_addr              (_core_io_dmem_req_bits_addr),	// RocketTile.scala:128:20
    .io_requestor_0_req_bits_tag               (_core_io_dmem_req_bits_tag),	// RocketTile.scala:128:20
    .io_requestor_0_req_bits_cmd               (_core_io_dmem_req_bits_cmd),	// RocketTile.scala:128:20
    .io_requestor_0_req_bits_size              (_core_io_dmem_req_bits_size),	// RocketTile.scala:128:20
    .io_requestor_0_req_bits_signed            (_core_io_dmem_req_bits_signed),	// RocketTile.scala:128:20
    .io_requestor_0_req_bits_dprv              (_core_io_dmem_req_bits_dprv),	// RocketTile.scala:128:20
    .io_requestor_0_s1_kill                    (_core_io_dmem_s1_kill),	// RocketTile.scala:128:20
    .io_requestor_0_s1_data_data               (_core_io_dmem_s1_data_data),	// RocketTile.scala:128:20
    .io_requestor_1_req_valid                  (_dtim_adapter_io_dmem_req_valid),	// RocketTile.scala:59:15
    .io_requestor_1_req_bits_addr              (_dtim_adapter_io_dmem_req_bits_addr),	// RocketTile.scala:59:15
    .io_requestor_1_req_bits_cmd               (_dtim_adapter_io_dmem_req_bits_cmd),	// RocketTile.scala:59:15
    .io_requestor_1_req_bits_size              (_dtim_adapter_io_dmem_req_bits_size),	// RocketTile.scala:59:15
    .io_requestor_1_s1_kill                    (_dtim_adapter_io_dmem_s1_kill),	// RocketTile.scala:59:15
    .io_requestor_1_s1_data_data               (_dtim_adapter_io_dmem_s1_data_data),	// RocketTile.scala:59:15
    .io_requestor_1_s1_data_mask               (_dtim_adapter_io_dmem_s1_data_mask),	// RocketTile.scala:59:15
    .io_mem_req_ready                          (_dcache_io_cpu_req_ready),	// HellaCache.scala:267:43
    .io_mem_s2_nack                            (_dcache_io_cpu_s2_nack),	// HellaCache.scala:267:43
    .io_mem_resp_valid                         (_dcache_io_cpu_resp_valid),	// HellaCache.scala:267:43
    .io_mem_resp_bits_tag                      (_dcache_io_cpu_resp_bits_tag),	// HellaCache.scala:267:43
    .io_mem_resp_bits_data                     (_dcache_io_cpu_resp_bits_data),	// HellaCache.scala:267:43
    .io_mem_resp_bits_replay                   (_dcache_io_cpu_resp_bits_replay),	// HellaCache.scala:267:43
    .io_mem_resp_bits_has_data                 (_dcache_io_cpu_resp_bits_has_data),	// HellaCache.scala:267:43
    .io_mem_resp_bits_data_word_bypass
      (_dcache_io_cpu_resp_bits_data_word_bypass),	// HellaCache.scala:267:43
    .io_mem_resp_bits_data_raw                 (_dcache_io_cpu_resp_bits_data_raw),	// HellaCache.scala:267:43
    .io_mem_replay_next                        (_dcache_io_cpu_replay_next),	// HellaCache.scala:267:43
    .io_mem_s2_xcpt_ma_ld                      (_dcache_io_cpu_s2_xcpt_ma_ld),	// HellaCache.scala:267:43
    .io_mem_s2_xcpt_ma_st                      (_dcache_io_cpu_s2_xcpt_ma_st),	// HellaCache.scala:267:43
    .io_mem_s2_xcpt_pf_ld                      (_dcache_io_cpu_s2_xcpt_pf_ld),	// HellaCache.scala:267:43
    .io_mem_s2_xcpt_pf_st                      (_dcache_io_cpu_s2_xcpt_pf_st),	// HellaCache.scala:267:43
    .io_mem_s2_xcpt_gf_ld                      (_dcache_io_cpu_s2_xcpt_gf_ld),	// HellaCache.scala:267:43
    .io_mem_s2_xcpt_gf_st                      (_dcache_io_cpu_s2_xcpt_gf_st),	// HellaCache.scala:267:43
    .io_mem_s2_xcpt_ae_ld                      (_dcache_io_cpu_s2_xcpt_ae_ld),	// HellaCache.scala:267:43
    .io_mem_s2_xcpt_ae_st                      (_dcache_io_cpu_s2_xcpt_ae_st),	// HellaCache.scala:267:43
    .io_mem_ordered                            (_dcache_io_cpu_ordered),	// HellaCache.scala:267:43
    .io_mem_perf_grant                         (_dcache_io_cpu_perf_grant),	// HellaCache.scala:267:43
    .io_requestor_0_req_ready                  (_dcacheArb_io_requestor_0_req_ready),
    .io_requestor_0_s2_nack                    (_dcacheArb_io_requestor_0_s2_nack),
    .io_requestor_0_resp_valid                 (_dcacheArb_io_requestor_0_resp_valid),
    .io_requestor_0_resp_bits_tag              (_dcacheArb_io_requestor_0_resp_bits_tag),
    .io_requestor_0_resp_bits_data             (_dcacheArb_io_requestor_0_resp_bits_data),
    .io_requestor_0_resp_bits_replay
      (_dcacheArb_io_requestor_0_resp_bits_replay),
    .io_requestor_0_resp_bits_has_data
      (_dcacheArb_io_requestor_0_resp_bits_has_data),
    .io_requestor_0_resp_bits_data_word_bypass
      (_dcacheArb_io_requestor_0_resp_bits_data_word_bypass),
    .io_requestor_0_replay_next                (_dcacheArb_io_requestor_0_replay_next),
    .io_requestor_0_s2_xcpt_ma_ld              (_dcacheArb_io_requestor_0_s2_xcpt_ma_ld),
    .io_requestor_0_s2_xcpt_ma_st              (_dcacheArb_io_requestor_0_s2_xcpt_ma_st),
    .io_requestor_0_s2_xcpt_pf_ld              (_dcacheArb_io_requestor_0_s2_xcpt_pf_ld),
    .io_requestor_0_s2_xcpt_pf_st              (_dcacheArb_io_requestor_0_s2_xcpt_pf_st),
    .io_requestor_0_s2_xcpt_gf_ld              (_dcacheArb_io_requestor_0_s2_xcpt_gf_ld),
    .io_requestor_0_s2_xcpt_gf_st              (_dcacheArb_io_requestor_0_s2_xcpt_gf_st),
    .io_requestor_0_s2_xcpt_ae_ld              (_dcacheArb_io_requestor_0_s2_xcpt_ae_ld),
    .io_requestor_0_s2_xcpt_ae_st              (_dcacheArb_io_requestor_0_s2_xcpt_ae_st),
    .io_requestor_0_ordered                    (_dcacheArb_io_requestor_0_ordered),
    .io_requestor_0_perf_grant                 (_dcacheArb_io_requestor_0_perf_grant),
    .io_requestor_1_req_ready                  (_dcacheArb_io_requestor_1_req_ready),
    .io_requestor_1_s2_nack                    (_dcacheArb_io_requestor_1_s2_nack),
    .io_requestor_1_resp_valid                 (_dcacheArb_io_requestor_1_resp_valid),
    .io_requestor_1_resp_bits_data_raw
      (_dcacheArb_io_requestor_1_resp_bits_data_raw),
    .io_mem_req_valid                          (_dcacheArb_io_mem_req_valid),
    .io_mem_req_bits_addr                      (_dcacheArb_io_mem_req_bits_addr),
    .io_mem_req_bits_tag                       (_dcacheArb_io_mem_req_bits_tag),
    .io_mem_req_bits_cmd                       (_dcacheArb_io_mem_req_bits_cmd),
    .io_mem_req_bits_size                      (_dcacheArb_io_mem_req_bits_size),
    .io_mem_req_bits_signed                    (_dcacheArb_io_mem_req_bits_signed),
    .io_mem_req_bits_dprv                      (_dcacheArb_io_mem_req_bits_dprv),
    .io_mem_req_bits_no_xcpt                   (_dcacheArb_io_mem_req_bits_no_xcpt),
    .io_mem_s1_kill                            (_dcacheArb_io_mem_s1_kill),
    .io_mem_s1_data_data                       (_dcacheArb_io_mem_s1_data_data),
    .io_mem_s1_data_mask                       (_dcacheArb_io_mem_s1_data_mask)
  );
  PTW ptw (	// PTW.scala:793:19
    .io_dpath_status_debug                  (_core_io_ptw_status_debug),	// RocketTile.scala:128:20
    .io_dpath_pmp_0_cfg_l                   (_core_io_ptw_pmp_0_cfg_l),	// RocketTile.scala:128:20
    .io_dpath_pmp_0_cfg_a                   (_core_io_ptw_pmp_0_cfg_a),	// RocketTile.scala:128:20
    .io_dpath_pmp_0_cfg_x                   (_core_io_ptw_pmp_0_cfg_x),	// RocketTile.scala:128:20
    .io_dpath_pmp_0_cfg_w                   (_core_io_ptw_pmp_0_cfg_w),	// RocketTile.scala:128:20
    .io_dpath_pmp_0_cfg_r                   (_core_io_ptw_pmp_0_cfg_r),	// RocketTile.scala:128:20
    .io_dpath_pmp_0_addr                    (_core_io_ptw_pmp_0_addr),	// RocketTile.scala:128:20
    .io_dpath_pmp_0_mask                    (_core_io_ptw_pmp_0_mask),	// RocketTile.scala:128:20
    .io_dpath_pmp_1_cfg_l                   (_core_io_ptw_pmp_1_cfg_l),	// RocketTile.scala:128:20
    .io_dpath_pmp_1_cfg_a                   (_core_io_ptw_pmp_1_cfg_a),	// RocketTile.scala:128:20
    .io_dpath_pmp_1_cfg_x                   (_core_io_ptw_pmp_1_cfg_x),	// RocketTile.scala:128:20
    .io_dpath_pmp_1_cfg_w                   (_core_io_ptw_pmp_1_cfg_w),	// RocketTile.scala:128:20
    .io_dpath_pmp_1_cfg_r                   (_core_io_ptw_pmp_1_cfg_r),	// RocketTile.scala:128:20
    .io_dpath_pmp_1_addr                    (_core_io_ptw_pmp_1_addr),	// RocketTile.scala:128:20
    .io_dpath_pmp_1_mask                    (_core_io_ptw_pmp_1_mask),	// RocketTile.scala:128:20
    .io_dpath_pmp_2_cfg_l                   (_core_io_ptw_pmp_2_cfg_l),	// RocketTile.scala:128:20
    .io_dpath_pmp_2_cfg_a                   (_core_io_ptw_pmp_2_cfg_a),	// RocketTile.scala:128:20
    .io_dpath_pmp_2_cfg_x                   (_core_io_ptw_pmp_2_cfg_x),	// RocketTile.scala:128:20
    .io_dpath_pmp_2_cfg_w                   (_core_io_ptw_pmp_2_cfg_w),	// RocketTile.scala:128:20
    .io_dpath_pmp_2_cfg_r                   (_core_io_ptw_pmp_2_cfg_r),	// RocketTile.scala:128:20
    .io_dpath_pmp_2_addr                    (_core_io_ptw_pmp_2_addr),	// RocketTile.scala:128:20
    .io_dpath_pmp_2_mask                    (_core_io_ptw_pmp_2_mask),	// RocketTile.scala:128:20
    .io_dpath_pmp_3_cfg_l                   (_core_io_ptw_pmp_3_cfg_l),	// RocketTile.scala:128:20
    .io_dpath_pmp_3_cfg_a                   (_core_io_ptw_pmp_3_cfg_a),	// RocketTile.scala:128:20
    .io_dpath_pmp_3_cfg_x                   (_core_io_ptw_pmp_3_cfg_x),	// RocketTile.scala:128:20
    .io_dpath_pmp_3_cfg_w                   (_core_io_ptw_pmp_3_cfg_w),	// RocketTile.scala:128:20
    .io_dpath_pmp_3_cfg_r                   (_core_io_ptw_pmp_3_cfg_r),	// RocketTile.scala:128:20
    .io_dpath_pmp_3_addr                    (_core_io_ptw_pmp_3_addr),	// RocketTile.scala:128:20
    .io_dpath_pmp_3_mask                    (_core_io_ptw_pmp_3_mask),	// RocketTile.scala:128:20
    .io_dpath_pmp_4_cfg_l                   (_core_io_ptw_pmp_4_cfg_l),	// RocketTile.scala:128:20
    .io_dpath_pmp_4_cfg_a                   (_core_io_ptw_pmp_4_cfg_a),	// RocketTile.scala:128:20
    .io_dpath_pmp_4_cfg_x                   (_core_io_ptw_pmp_4_cfg_x),	// RocketTile.scala:128:20
    .io_dpath_pmp_4_cfg_w                   (_core_io_ptw_pmp_4_cfg_w),	// RocketTile.scala:128:20
    .io_dpath_pmp_4_cfg_r                   (_core_io_ptw_pmp_4_cfg_r),	// RocketTile.scala:128:20
    .io_dpath_pmp_4_addr                    (_core_io_ptw_pmp_4_addr),	// RocketTile.scala:128:20
    .io_dpath_pmp_4_mask                    (_core_io_ptw_pmp_4_mask),	// RocketTile.scala:128:20
    .io_dpath_pmp_5_cfg_l                   (_core_io_ptw_pmp_5_cfg_l),	// RocketTile.scala:128:20
    .io_dpath_pmp_5_cfg_a                   (_core_io_ptw_pmp_5_cfg_a),	// RocketTile.scala:128:20
    .io_dpath_pmp_5_cfg_x                   (_core_io_ptw_pmp_5_cfg_x),	// RocketTile.scala:128:20
    .io_dpath_pmp_5_cfg_w                   (_core_io_ptw_pmp_5_cfg_w),	// RocketTile.scala:128:20
    .io_dpath_pmp_5_cfg_r                   (_core_io_ptw_pmp_5_cfg_r),	// RocketTile.scala:128:20
    .io_dpath_pmp_5_addr                    (_core_io_ptw_pmp_5_addr),	// RocketTile.scala:128:20
    .io_dpath_pmp_5_mask                    (_core_io_ptw_pmp_5_mask),	// RocketTile.scala:128:20
    .io_dpath_pmp_6_cfg_l                   (_core_io_ptw_pmp_6_cfg_l),	// RocketTile.scala:128:20
    .io_dpath_pmp_6_cfg_a                   (_core_io_ptw_pmp_6_cfg_a),	// RocketTile.scala:128:20
    .io_dpath_pmp_6_cfg_x                   (_core_io_ptw_pmp_6_cfg_x),	// RocketTile.scala:128:20
    .io_dpath_pmp_6_cfg_w                   (_core_io_ptw_pmp_6_cfg_w),	// RocketTile.scala:128:20
    .io_dpath_pmp_6_cfg_r                   (_core_io_ptw_pmp_6_cfg_r),	// RocketTile.scala:128:20
    .io_dpath_pmp_6_addr                    (_core_io_ptw_pmp_6_addr),	// RocketTile.scala:128:20
    .io_dpath_pmp_6_mask                    (_core_io_ptw_pmp_6_mask),	// RocketTile.scala:128:20
    .io_dpath_pmp_7_cfg_l                   (_core_io_ptw_pmp_7_cfg_l),	// RocketTile.scala:128:20
    .io_dpath_pmp_7_cfg_a                   (_core_io_ptw_pmp_7_cfg_a),	// RocketTile.scala:128:20
    .io_dpath_pmp_7_cfg_x                   (_core_io_ptw_pmp_7_cfg_x),	// RocketTile.scala:128:20
    .io_dpath_pmp_7_cfg_w                   (_core_io_ptw_pmp_7_cfg_w),	// RocketTile.scala:128:20
    .io_dpath_pmp_7_cfg_r                   (_core_io_ptw_pmp_7_cfg_r),	// RocketTile.scala:128:20
    .io_dpath_pmp_7_addr                    (_core_io_ptw_pmp_7_addr),	// RocketTile.scala:128:20
    .io_dpath_pmp_7_mask                    (_core_io_ptw_pmp_7_mask),	// RocketTile.scala:128:20
    .io_dpath_customCSRs_csrs_0_value       (_core_io_ptw_customCSRs_csrs_0_value),	// RocketTile.scala:128:20
    .io_requestor_0_status_debug            (_ptw_io_requestor_0_status_debug),
    .io_requestor_0_pmp_0_cfg_l             (_ptw_io_requestor_0_pmp_0_cfg_l),
    .io_requestor_0_pmp_0_cfg_a             (_ptw_io_requestor_0_pmp_0_cfg_a),
    .io_requestor_0_pmp_0_cfg_w             (_ptw_io_requestor_0_pmp_0_cfg_w),
    .io_requestor_0_pmp_0_cfg_r             (_ptw_io_requestor_0_pmp_0_cfg_r),
    .io_requestor_0_pmp_0_addr              (_ptw_io_requestor_0_pmp_0_addr),
    .io_requestor_0_pmp_0_mask              (_ptw_io_requestor_0_pmp_0_mask),
    .io_requestor_0_pmp_1_cfg_l             (_ptw_io_requestor_0_pmp_1_cfg_l),
    .io_requestor_0_pmp_1_cfg_a             (_ptw_io_requestor_0_pmp_1_cfg_a),
    .io_requestor_0_pmp_1_cfg_w             (_ptw_io_requestor_0_pmp_1_cfg_w),
    .io_requestor_0_pmp_1_cfg_r             (_ptw_io_requestor_0_pmp_1_cfg_r),
    .io_requestor_0_pmp_1_addr              (_ptw_io_requestor_0_pmp_1_addr),
    .io_requestor_0_pmp_1_mask              (_ptw_io_requestor_0_pmp_1_mask),
    .io_requestor_0_pmp_2_cfg_l             (_ptw_io_requestor_0_pmp_2_cfg_l),
    .io_requestor_0_pmp_2_cfg_a             (_ptw_io_requestor_0_pmp_2_cfg_a),
    .io_requestor_0_pmp_2_cfg_w             (_ptw_io_requestor_0_pmp_2_cfg_w),
    .io_requestor_0_pmp_2_cfg_r             (_ptw_io_requestor_0_pmp_2_cfg_r),
    .io_requestor_0_pmp_2_addr              (_ptw_io_requestor_0_pmp_2_addr),
    .io_requestor_0_pmp_2_mask              (_ptw_io_requestor_0_pmp_2_mask),
    .io_requestor_0_pmp_3_cfg_l             (_ptw_io_requestor_0_pmp_3_cfg_l),
    .io_requestor_0_pmp_3_cfg_a             (_ptw_io_requestor_0_pmp_3_cfg_a),
    .io_requestor_0_pmp_3_cfg_w             (_ptw_io_requestor_0_pmp_3_cfg_w),
    .io_requestor_0_pmp_3_cfg_r             (_ptw_io_requestor_0_pmp_3_cfg_r),
    .io_requestor_0_pmp_3_addr              (_ptw_io_requestor_0_pmp_3_addr),
    .io_requestor_0_pmp_3_mask              (_ptw_io_requestor_0_pmp_3_mask),
    .io_requestor_0_pmp_4_cfg_l             (_ptw_io_requestor_0_pmp_4_cfg_l),
    .io_requestor_0_pmp_4_cfg_a             (_ptw_io_requestor_0_pmp_4_cfg_a),
    .io_requestor_0_pmp_4_cfg_w             (_ptw_io_requestor_0_pmp_4_cfg_w),
    .io_requestor_0_pmp_4_cfg_r             (_ptw_io_requestor_0_pmp_4_cfg_r),
    .io_requestor_0_pmp_4_addr              (_ptw_io_requestor_0_pmp_4_addr),
    .io_requestor_0_pmp_4_mask              (_ptw_io_requestor_0_pmp_4_mask),
    .io_requestor_0_pmp_5_cfg_l             (_ptw_io_requestor_0_pmp_5_cfg_l),
    .io_requestor_0_pmp_5_cfg_a             (_ptw_io_requestor_0_pmp_5_cfg_a),
    .io_requestor_0_pmp_5_cfg_w             (_ptw_io_requestor_0_pmp_5_cfg_w),
    .io_requestor_0_pmp_5_cfg_r             (_ptw_io_requestor_0_pmp_5_cfg_r),
    .io_requestor_0_pmp_5_addr              (_ptw_io_requestor_0_pmp_5_addr),
    .io_requestor_0_pmp_5_mask              (_ptw_io_requestor_0_pmp_5_mask),
    .io_requestor_0_pmp_6_cfg_l             (_ptw_io_requestor_0_pmp_6_cfg_l),
    .io_requestor_0_pmp_6_cfg_a             (_ptw_io_requestor_0_pmp_6_cfg_a),
    .io_requestor_0_pmp_6_cfg_w             (_ptw_io_requestor_0_pmp_6_cfg_w),
    .io_requestor_0_pmp_6_cfg_r             (_ptw_io_requestor_0_pmp_6_cfg_r),
    .io_requestor_0_pmp_6_addr              (_ptw_io_requestor_0_pmp_6_addr),
    .io_requestor_0_pmp_6_mask              (_ptw_io_requestor_0_pmp_6_mask),
    .io_requestor_0_pmp_7_cfg_l             (_ptw_io_requestor_0_pmp_7_cfg_l),
    .io_requestor_0_pmp_7_cfg_a             (_ptw_io_requestor_0_pmp_7_cfg_a),
    .io_requestor_0_pmp_7_cfg_w             (_ptw_io_requestor_0_pmp_7_cfg_w),
    .io_requestor_0_pmp_7_cfg_r             (_ptw_io_requestor_0_pmp_7_cfg_r),
    .io_requestor_0_pmp_7_addr              (_ptw_io_requestor_0_pmp_7_addr),
    .io_requestor_0_pmp_7_mask              (_ptw_io_requestor_0_pmp_7_mask),
    .io_requestor_1_status_debug            (_ptw_io_requestor_1_status_debug),
    .io_requestor_1_pmp_0_cfg_l             (_ptw_io_requestor_1_pmp_0_cfg_l),
    .io_requestor_1_pmp_0_cfg_a             (_ptw_io_requestor_1_pmp_0_cfg_a),
    .io_requestor_1_pmp_0_cfg_x             (_ptw_io_requestor_1_pmp_0_cfg_x),
    .io_requestor_1_pmp_0_addr              (_ptw_io_requestor_1_pmp_0_addr),
    .io_requestor_1_pmp_0_mask              (_ptw_io_requestor_1_pmp_0_mask),
    .io_requestor_1_pmp_1_cfg_l             (_ptw_io_requestor_1_pmp_1_cfg_l),
    .io_requestor_1_pmp_1_cfg_a             (_ptw_io_requestor_1_pmp_1_cfg_a),
    .io_requestor_1_pmp_1_cfg_x             (_ptw_io_requestor_1_pmp_1_cfg_x),
    .io_requestor_1_pmp_1_addr              (_ptw_io_requestor_1_pmp_1_addr),
    .io_requestor_1_pmp_1_mask              (_ptw_io_requestor_1_pmp_1_mask),
    .io_requestor_1_pmp_2_cfg_l             (_ptw_io_requestor_1_pmp_2_cfg_l),
    .io_requestor_1_pmp_2_cfg_a             (_ptw_io_requestor_1_pmp_2_cfg_a),
    .io_requestor_1_pmp_2_cfg_x             (_ptw_io_requestor_1_pmp_2_cfg_x),
    .io_requestor_1_pmp_2_addr              (_ptw_io_requestor_1_pmp_2_addr),
    .io_requestor_1_pmp_2_mask              (_ptw_io_requestor_1_pmp_2_mask),
    .io_requestor_1_pmp_3_cfg_l             (_ptw_io_requestor_1_pmp_3_cfg_l),
    .io_requestor_1_pmp_3_cfg_a             (_ptw_io_requestor_1_pmp_3_cfg_a),
    .io_requestor_1_pmp_3_cfg_x             (_ptw_io_requestor_1_pmp_3_cfg_x),
    .io_requestor_1_pmp_3_addr              (_ptw_io_requestor_1_pmp_3_addr),
    .io_requestor_1_pmp_3_mask              (_ptw_io_requestor_1_pmp_3_mask),
    .io_requestor_1_pmp_4_cfg_l             (_ptw_io_requestor_1_pmp_4_cfg_l),
    .io_requestor_1_pmp_4_cfg_a             (_ptw_io_requestor_1_pmp_4_cfg_a),
    .io_requestor_1_pmp_4_cfg_x             (_ptw_io_requestor_1_pmp_4_cfg_x),
    .io_requestor_1_pmp_4_addr              (_ptw_io_requestor_1_pmp_4_addr),
    .io_requestor_1_pmp_4_mask              (_ptw_io_requestor_1_pmp_4_mask),
    .io_requestor_1_pmp_5_cfg_l             (_ptw_io_requestor_1_pmp_5_cfg_l),
    .io_requestor_1_pmp_5_cfg_a             (_ptw_io_requestor_1_pmp_5_cfg_a),
    .io_requestor_1_pmp_5_cfg_x             (_ptw_io_requestor_1_pmp_5_cfg_x),
    .io_requestor_1_pmp_5_addr              (_ptw_io_requestor_1_pmp_5_addr),
    .io_requestor_1_pmp_5_mask              (_ptw_io_requestor_1_pmp_5_mask),
    .io_requestor_1_pmp_6_cfg_l             (_ptw_io_requestor_1_pmp_6_cfg_l),
    .io_requestor_1_pmp_6_cfg_a             (_ptw_io_requestor_1_pmp_6_cfg_a),
    .io_requestor_1_pmp_6_cfg_x             (_ptw_io_requestor_1_pmp_6_cfg_x),
    .io_requestor_1_pmp_6_addr              (_ptw_io_requestor_1_pmp_6_addr),
    .io_requestor_1_pmp_6_mask              (_ptw_io_requestor_1_pmp_6_mask),
    .io_requestor_1_pmp_7_cfg_l             (_ptw_io_requestor_1_pmp_7_cfg_l),
    .io_requestor_1_pmp_7_cfg_a             (_ptw_io_requestor_1_pmp_7_cfg_a),
    .io_requestor_1_pmp_7_cfg_x             (_ptw_io_requestor_1_pmp_7_cfg_x),
    .io_requestor_1_pmp_7_addr              (_ptw_io_requestor_1_pmp_7_addr),
    .io_requestor_1_pmp_7_mask              (_ptw_io_requestor_1_pmp_7_mask),
    .io_requestor_1_customCSRs_csrs_0_value (_ptw_io_requestor_1_customCSRs_csrs_0_value)
  );
  Rocket core (	// RocketTile.scala:128:20
    .clock                              (clock),
    .reset                              (reset),
    .io_interrupts_debug                (_intXbar_auto_int_out_0),	// BaseTile.scala:224:37
    .io_interrupts_mtip                 (_intXbar_auto_int_out_2),	// BaseTile.scala:224:37
    .io_interrupts_msip                 (_intXbar_auto_int_out_1),	// BaseTile.scala:224:37
    .io_interrupts_meip                 (_intXbar_auto_int_out_3),	// BaseTile.scala:224:37
    .io_imem_resp_valid                 (_frontend_io_cpu_resp_valid),	// Frontend.scala:385:28
    .io_imem_resp_bits_btb_taken        (_frontend_io_cpu_resp_bits_btb_taken),	// Frontend.scala:385:28
    .io_imem_resp_bits_btb_bridx        (_frontend_io_cpu_resp_bits_btb_bridx),	// Frontend.scala:385:28
    .io_imem_resp_bits_pc               (_frontend_io_cpu_resp_bits_pc),	// Frontend.scala:385:28
    .io_imem_resp_bits_data             (_frontend_io_cpu_resp_bits_data),	// Frontend.scala:385:28
    .io_imem_resp_bits_xcpt_pf_inst     (_frontend_io_cpu_resp_bits_xcpt_pf_inst),	// Frontend.scala:385:28
    .io_imem_resp_bits_xcpt_gf_inst     (_frontend_io_cpu_resp_bits_xcpt_gf_inst),	// Frontend.scala:385:28
    .io_imem_resp_bits_xcpt_ae_inst     (_frontend_io_cpu_resp_bits_xcpt_ae_inst),	// Frontend.scala:385:28
    .io_imem_resp_bits_replay           (_frontend_io_cpu_resp_bits_replay),	// Frontend.scala:385:28
    .io_imem_gpa_valid                  (_frontend_io_cpu_gpa_valid),	// Frontend.scala:385:28
    .io_dmem_req_ready                  (_dcacheArb_io_requestor_0_req_ready),	// HellaCache.scala:278:25
    .io_dmem_s2_nack                    (_dcacheArb_io_requestor_0_s2_nack),	// HellaCache.scala:278:25
    .io_dmem_resp_valid                 (_dcacheArb_io_requestor_0_resp_valid),	// HellaCache.scala:278:25
    .io_dmem_resp_bits_tag              (_dcacheArb_io_requestor_0_resp_bits_tag),	// HellaCache.scala:278:25
    .io_dmem_resp_bits_data             (_dcacheArb_io_requestor_0_resp_bits_data),	// HellaCache.scala:278:25
    .io_dmem_resp_bits_replay           (_dcacheArb_io_requestor_0_resp_bits_replay),	// HellaCache.scala:278:25
    .io_dmem_resp_bits_has_data         (_dcacheArb_io_requestor_0_resp_bits_has_data),	// HellaCache.scala:278:25
    .io_dmem_resp_bits_data_word_bypass
      (_dcacheArb_io_requestor_0_resp_bits_data_word_bypass),	// HellaCache.scala:278:25
    .io_dmem_replay_next                (_dcacheArb_io_requestor_0_replay_next),	// HellaCache.scala:278:25
    .io_dmem_s2_xcpt_ma_ld              (_dcacheArb_io_requestor_0_s2_xcpt_ma_ld),	// HellaCache.scala:278:25
    .io_dmem_s2_xcpt_ma_st              (_dcacheArb_io_requestor_0_s2_xcpt_ma_st),	// HellaCache.scala:278:25
    .io_dmem_s2_xcpt_pf_ld              (_dcacheArb_io_requestor_0_s2_xcpt_pf_ld),	// HellaCache.scala:278:25
    .io_dmem_s2_xcpt_pf_st              (_dcacheArb_io_requestor_0_s2_xcpt_pf_st),	// HellaCache.scala:278:25
    .io_dmem_s2_xcpt_gf_ld              (_dcacheArb_io_requestor_0_s2_xcpt_gf_ld),	// HellaCache.scala:278:25
    .io_dmem_s2_xcpt_gf_st              (_dcacheArb_io_requestor_0_s2_xcpt_gf_st),	// HellaCache.scala:278:25
    .io_dmem_s2_xcpt_ae_ld              (_dcacheArb_io_requestor_0_s2_xcpt_ae_ld),	// HellaCache.scala:278:25
    .io_dmem_s2_xcpt_ae_st              (_dcacheArb_io_requestor_0_s2_xcpt_ae_st),	// HellaCache.scala:278:25
    .io_dmem_ordered                    (_dcacheArb_io_requestor_0_ordered),	// HellaCache.scala:278:25
    .io_dmem_perf_grant                 (_dcacheArb_io_requestor_0_perf_grant),	// HellaCache.scala:278:25
    .io_imem_might_request              (_core_io_imem_might_request),
    .io_imem_req_valid                  (_core_io_imem_req_valid),
    .io_imem_req_bits_pc                (_core_io_imem_req_bits_pc),
    .io_imem_req_bits_speculative       (_core_io_imem_req_bits_speculative),
    .io_imem_sfence_valid               (_core_io_imem_sfence_valid),
    .io_imem_resp_ready                 (_core_io_imem_resp_ready),
    .io_imem_btb_update_valid           (_core_io_imem_btb_update_valid),
    .io_imem_bht_update_valid           (_core_io_imem_bht_update_valid),
    .io_imem_flush_icache               (_core_io_imem_flush_icache),
    .io_dmem_req_valid                  (_core_io_dmem_req_valid),
    .io_dmem_req_bits_addr              (_core_io_dmem_req_bits_addr),
    .io_dmem_req_bits_tag               (_core_io_dmem_req_bits_tag),
    .io_dmem_req_bits_cmd               (_core_io_dmem_req_bits_cmd),
    .io_dmem_req_bits_size              (_core_io_dmem_req_bits_size),
    .io_dmem_req_bits_signed            (_core_io_dmem_req_bits_signed),
    .io_dmem_req_bits_dprv              (_core_io_dmem_req_bits_dprv),
    .io_dmem_s1_kill                    (_core_io_dmem_s1_kill),
    .io_dmem_s1_data_data               (_core_io_dmem_s1_data_data),
    .io_ptw_status_debug                (_core_io_ptw_status_debug),
    .io_ptw_pmp_0_cfg_l                 (_core_io_ptw_pmp_0_cfg_l),
    .io_ptw_pmp_0_cfg_a                 (_core_io_ptw_pmp_0_cfg_a),
    .io_ptw_pmp_0_cfg_x                 (_core_io_ptw_pmp_0_cfg_x),
    .io_ptw_pmp_0_cfg_w                 (_core_io_ptw_pmp_0_cfg_w),
    .io_ptw_pmp_0_cfg_r                 (_core_io_ptw_pmp_0_cfg_r),
    .io_ptw_pmp_0_addr                  (_core_io_ptw_pmp_0_addr),
    .io_ptw_pmp_0_mask                  (_core_io_ptw_pmp_0_mask),
    .io_ptw_pmp_1_cfg_l                 (_core_io_ptw_pmp_1_cfg_l),
    .io_ptw_pmp_1_cfg_a                 (_core_io_ptw_pmp_1_cfg_a),
    .io_ptw_pmp_1_cfg_x                 (_core_io_ptw_pmp_1_cfg_x),
    .io_ptw_pmp_1_cfg_w                 (_core_io_ptw_pmp_1_cfg_w),
    .io_ptw_pmp_1_cfg_r                 (_core_io_ptw_pmp_1_cfg_r),
    .io_ptw_pmp_1_addr                  (_core_io_ptw_pmp_1_addr),
    .io_ptw_pmp_1_mask                  (_core_io_ptw_pmp_1_mask),
    .io_ptw_pmp_2_cfg_l                 (_core_io_ptw_pmp_2_cfg_l),
    .io_ptw_pmp_2_cfg_a                 (_core_io_ptw_pmp_2_cfg_a),
    .io_ptw_pmp_2_cfg_x                 (_core_io_ptw_pmp_2_cfg_x),
    .io_ptw_pmp_2_cfg_w                 (_core_io_ptw_pmp_2_cfg_w),
    .io_ptw_pmp_2_cfg_r                 (_core_io_ptw_pmp_2_cfg_r),
    .io_ptw_pmp_2_addr                  (_core_io_ptw_pmp_2_addr),
    .io_ptw_pmp_2_mask                  (_core_io_ptw_pmp_2_mask),
    .io_ptw_pmp_3_cfg_l                 (_core_io_ptw_pmp_3_cfg_l),
    .io_ptw_pmp_3_cfg_a                 (_core_io_ptw_pmp_3_cfg_a),
    .io_ptw_pmp_3_cfg_x                 (_core_io_ptw_pmp_3_cfg_x),
    .io_ptw_pmp_3_cfg_w                 (_core_io_ptw_pmp_3_cfg_w),
    .io_ptw_pmp_3_cfg_r                 (_core_io_ptw_pmp_3_cfg_r),
    .io_ptw_pmp_3_addr                  (_core_io_ptw_pmp_3_addr),
    .io_ptw_pmp_3_mask                  (_core_io_ptw_pmp_3_mask),
    .io_ptw_pmp_4_cfg_l                 (_core_io_ptw_pmp_4_cfg_l),
    .io_ptw_pmp_4_cfg_a                 (_core_io_ptw_pmp_4_cfg_a),
    .io_ptw_pmp_4_cfg_x                 (_core_io_ptw_pmp_4_cfg_x),
    .io_ptw_pmp_4_cfg_w                 (_core_io_ptw_pmp_4_cfg_w),
    .io_ptw_pmp_4_cfg_r                 (_core_io_ptw_pmp_4_cfg_r),
    .io_ptw_pmp_4_addr                  (_core_io_ptw_pmp_4_addr),
    .io_ptw_pmp_4_mask                  (_core_io_ptw_pmp_4_mask),
    .io_ptw_pmp_5_cfg_l                 (_core_io_ptw_pmp_5_cfg_l),
    .io_ptw_pmp_5_cfg_a                 (_core_io_ptw_pmp_5_cfg_a),
    .io_ptw_pmp_5_cfg_x                 (_core_io_ptw_pmp_5_cfg_x),
    .io_ptw_pmp_5_cfg_w                 (_core_io_ptw_pmp_5_cfg_w),
    .io_ptw_pmp_5_cfg_r                 (_core_io_ptw_pmp_5_cfg_r),
    .io_ptw_pmp_5_addr                  (_core_io_ptw_pmp_5_addr),
    .io_ptw_pmp_5_mask                  (_core_io_ptw_pmp_5_mask),
    .io_ptw_pmp_6_cfg_l                 (_core_io_ptw_pmp_6_cfg_l),
    .io_ptw_pmp_6_cfg_a                 (_core_io_ptw_pmp_6_cfg_a),
    .io_ptw_pmp_6_cfg_x                 (_core_io_ptw_pmp_6_cfg_x),
    .io_ptw_pmp_6_cfg_w                 (_core_io_ptw_pmp_6_cfg_w),
    .io_ptw_pmp_6_cfg_r                 (_core_io_ptw_pmp_6_cfg_r),
    .io_ptw_pmp_6_addr                  (_core_io_ptw_pmp_6_addr),
    .io_ptw_pmp_6_mask                  (_core_io_ptw_pmp_6_mask),
    .io_ptw_pmp_7_cfg_l                 (_core_io_ptw_pmp_7_cfg_l),
    .io_ptw_pmp_7_cfg_a                 (_core_io_ptw_pmp_7_cfg_a),
    .io_ptw_pmp_7_cfg_x                 (_core_io_ptw_pmp_7_cfg_x),
    .io_ptw_pmp_7_cfg_w                 (_core_io_ptw_pmp_7_cfg_w),
    .io_ptw_pmp_7_cfg_r                 (_core_io_ptw_pmp_7_cfg_r),
    .io_ptw_pmp_7_addr                  (_core_io_ptw_pmp_7_addr),
    .io_ptw_pmp_7_mask                  (_core_io_ptw_pmp_7_mask),
    .io_ptw_customCSRs_csrs_0_value     (_core_io_ptw_customCSRs_csrs_0_value)
  );
endmodule

